// src/lib/nex-agent/core/proposed-diff.ts
//
// NEX Agent v1.1 · Proposed-diff preview generator.
// nex1 composes realistic template content for each planned file so the founder
// can PREVIEW the code before approving. Nothing is written to disk in V1.1 —
// the preview is a courtesy so the founder can spot problems before the engineer
// starts building.
//
// Templates are deterministic. No LLM. Content includes the CLAUDE.md-mandated
// leading `//` summary comment, the ADR-compliant defaults, and TODO markers
// where the engineer must decide details.

import type { Plan, ProposedFile, Intent } from "./orchestrator-types";

const TS_TIMESTAMP = new Date().toISOString().slice(0, 10);

function tsHeader(path: string, oneLineSummary: string): string {
  return `// ${path}
//
// ${oneLineSummary}
// Generated by NEX Agent v1.1 · ${TS_TIMESTAMP}
`;
}

// ─── Templates per intent kind ──────────────────────────────────

function apiRouteTemplate(routePath: string, promptSubject: string): ProposedFile {
  const relPath = `src/app/api/${routePath.replace(/^\/api\//, "").replace(/\/$/, "")}/route.ts`;
  const content = `${tsHeader(relPath, `${promptSubject}`)}
import { NextResponse } from "next/server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET(_req: Request) {
  const ts_iso = new Date().toISOString();
  // TODO(nex1): confirm response shape with founder before shipping.
  return NextResponse.json({ ok: true, ts_iso }, { headers: { "cache-control": "no-store" } });
}

// export async function POST(req: Request) {
//   let body: unknown = null;
//   try { body = await req.json(); } catch { /* empty body ok */ }
//   // TODO(nex1): validate + handle
//   return NextResponse.json({ ok: true, echoed: body });
// }
`;
  return {
    path: relPath, action: "create", language: "typescript",
    why: "Canonical API-route location per ADR-0001 · leading comment per CLAUDE.md · runtime=nodejs.",
    preview_content: content,
  };
}

function libraryTemplate(name: string, promptSubject: string): ProposedFile {
  const relPath = `src/lib/nex/${name}/index.ts`;
  const content = `${tsHeader(relPath, `${promptSubject}`)}
// Public surface of this library. Add exports here as you build.

export interface ${toPascalCase(name)}Options {
  // TODO(nex1): define input options
}

export interface ${toPascalCase(name)}Result {
  ok: boolean;
  // TODO(nex1): define result shape
}

export function ${toCamelCase(name)}(_opts: ${toPascalCase(name)}Options): ${toPascalCase(name)}Result {
  // TODO(nex1): implement
  return { ok: false };
}
`;
  return {
    path: relPath, action: "create", language: "typescript",
    why: "Canonical library location per CLAUDE.md · leading comment · index.ts entry point.",
    preview_content: content,
  };
}

function migrationTemplate(subject: string): ProposedFile {
  // V1.3 · scan db/migrations/ to pick the next available number.
  let nextNum = "TBD";
  try {
    // Lazy load to avoid pulling fs into files that don't need it
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const fs = require("node:fs");
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const path = require("node:path");
    const dir = path.resolve(process.cwd(), "db/migrations");
    if (fs.existsSync(dir)) {
      const entries = fs.readdirSync(dir) as string[];
      let max = 0;
      for (const e of entries) {
        const m = /^(\d+)_/.exec(e);
        if (m) { const n = parseInt(m[1], 10); if (Number.isFinite(n) && n > max) max = n; }
      }
      nextNum = String(max + 1).padStart(3, "0");
    }
  } catch { /* ignore · fall back to TBD */ }
  // Also derive a slug from the subject
  const slug = subject.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 40) || "new_migration";
  const relPath = `db/migrations/${nextNum}_${slug}.sql`;
  const content = `-- ${relPath}
--
-- ${subject}
-- Generated by NEX Agent v1.3 · ${TS_TIMESTAMP}
--
-- APPEND-ONLY · IMMUTABLE once applied. To roll back, add a NEW numbered
-- migration with the inverse SQL. Never edit this file after apply.
--
-- Doctrine references honoured by this template:
--   D-003 · migrations append-only · never modify existing numbered file
--   D-006 · nex1 does not claim complete until postgres_dry_run_migration passes
--
-- Nex1 workflow (V1.3):
--   1. postgres_schema_introspect · confirm target tables exist / don't exist
--   2. write CREATE/ALTER statements below in IDEMPOTENT form (IF NOT EXISTS)
--   3. postgres_dry_run_migration · verify SQL syntax + no constraint violations
--   4. Founder types 'APPLY MIGRATION' → postgres_apply_migration
--
-- ============================================================================
-- SCHEMA CHANGE
-- ============================================================================

-- Example (replace with founder's actual spec):
--
-- CREATE TABLE IF NOT EXISTS nex.example_table (
--   id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
--   updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
--   -- TODO(nex1): add columns per founder's spec
--   note         TEXT
-- );
--
-- CREATE INDEX IF NOT EXISTS ix_example_table_created_at
--   ON nex.example_table (created_at DESC);

-- ============================================================================
-- ROLLBACK (for reference · put into a NEW numbered migration if needed)
-- ============================================================================

-- DROP INDEX IF EXISTS ix_example_table_created_at;
-- DROP TABLE IF EXISTS nex.example_table;
`;
  return {
    path: relPath, action: "create", language: "sql",
    why: `Canonical migration location · next number ${nextNum} picked by scanning db/migrations/ · idempotent form · doctrine D-003+D-006 honoured.`,
    preview_content: content,
  };
}

function bugFixTemplate(promptSubject: string, filePath?: string): ProposedFile {
  const relPath = filePath ?? "src/{TODO}/{TODO}.ts";
  const content = `// ${relPath} (MODIFY)
//
// ${promptSubject}
// Generated by NEX Agent v1.1 · ${TS_TIMESTAMP}
//
// This is a PATCH PREVIEW, not the full file. Engineer applies these changes
// only. Read the target file first · locate the failing code path.

// Step 1: Add a regression test that reproduces the bug BEFORE fixing.
//   file: tests/{module}/bug-{ticket}.test.ts (or vitest equivalent)
//   the test should FAIL on current main.

// Step 2: Fix the minimum lines needed to make the test pass.
//   No error handling for cases that can't happen (CLAUDE.md rule).
//   No refactor beyond what the fix requires.

// Step 3: Confirm existing tests still pass.
// Step 4: Update ADR ONLY if the fix changes documented behaviour.
`;
  return {
    path: relPath, action: "modify", language: "typescript",
    why: "Bug-fix flow · test-first · minimum-diff · no unrelated refactor.",
    preview_content: content,
  };
}

// ─── Helpers ────────────────────────────────────────────────────
function toCamelCase(s: string): string { return s.split(/[-_\s]+/).map((w, i) => i === 0 ? w.toLowerCase() : w[0].toUpperCase() + w.slice(1).toLowerCase()).join(""); }
function toPascalCase(s: string): string { return s.split(/[-_\s]+/).map(w => w[0].toUpperCase() + w.slice(1).toLowerCase()).join(""); }

// ─── Main entry · called by orchestrator after nex1 has a plan ──
export function generateProposedFiles(intent: Intent, prompt: string): ProposedFile[] {
  const out: ProposedFile[] = [];
  switch (intent.kind) {
    case "add_api_route": {
      // Extract route path from prompt if present
      const m = prompt.match(/\/api\/[\w\-\/]+/);
      const route = m ? m[0] : "/api/nex/TODO";
      out.push(apiRouteTemplate(route, prompt.slice(0, 120)));
      break;
    }
    case "add_feature": {
      // Try to guess module name from prompt keywords
      const words = prompt.toLowerCase().match(/\b[a-z][a-z\-]{3,}\b/g) ?? [];
      const stopwords = new Set(["that", "should", "would", "could", "with", "from", "into", "then", "when", "next", "some", "this", "them", "have", "your", "which", "return", "returns"]);
      const candidate = words.find(w => !stopwords.has(w)) ?? "todo-module";
      out.push(libraryTemplate(candidate, prompt.slice(0, 120)));
      break;
    }
    case "add_migration": {
      out.push(migrationTemplate(prompt.slice(0, 200)));
      break;
    }
    case "fix_bug": {
      const filePath = intent.hints.file_hints[0];
      out.push(bugFixTemplate(prompt.slice(0, 120), filePath));
      break;
    }
    case "explain":
    case "refactor":
    case "unknown":
      // These intents don't produce proposed files · nex1's brief covers them
      break;
  }
  return out;
}

// ─── Diff-style rendering for the UI ────────────────────────────
export function toDiffPreview(pf: ProposedFile): { header: string; body_lines: Array<{ kind: "add" | "context"; text: string }> } {
  const header = `${pf.action === "create" ? "NEW FILE" : "MODIFY"} · ${pf.path} · ${pf.language}`;
  const lines = pf.preview_content.split("\n").map(l => ({ kind: "add" as const, text: l }));
  return { header, body_lines: lines };
}
