// src/lib/nex/lab/rollback.ts
//
// Founder ADR-0304 · Rollback promotion.
//
// Executes the pre-computed rollback_sql for a promotion, then marks
// it status='rolled_back' in nex_lab.promotion_events. Immutable audit:
// the ORIGINAL promotion row stays · we just append a new status.
//
// GOLDEN RULE:
//   · Only 'succeeded' promotions can be rolled back
//   · rollback_sql was computed at approval time (deterministic · not user input)
//   · founder signature required (same HMAC scheme as approval)
//   · every rollback logs founder_user_id + timestamp

import { createHmac } from "node:crypto";
import type { Pool } from "pg";

export interface RollbackInput {
  promotion_id:        string;
  rolled_back_by_user_id: string;
  rolled_back_at_iso:  string;   // must match signed timestamp
  signature_hmac:      string;   // HMAC over `${brief_id}|${room_slug}|ROLLBACK|${ts}|${user_id}`
}

export function signRollbackPayload(input: {
  brief_id: string;
  room_slug: string;
  rolled_back_at_iso: string;
  user_id: string;
}): string {
  const secret = process.env.NEX_LAB_PROMOTION_SECRET ?? "";
  if (secret.length < 32) throw new Error("secret_not_configured");
  const payload = `${input.brief_id}|${input.room_slug}|ROLLBACK|${input.rolled_back_at_iso}|${input.user_id}`;
  return createHmac("sha256", secret).update(payload).digest("hex");
}

function verifyRollbackSignature(input: {
  brief_id: string;
  room_slug: string;
  rolled_back_at_iso: string;
  user_id: string;
  signature: string;
}): boolean {
  try {
    const expected = signRollbackPayload(input);
    if (expected.length !== input.signature.length) return false;
    let diff = 0;
    for (let i = 0; i < expected.length; i++) diff |= expected.charCodeAt(i) ^ input.signature.charCodeAt(i);
    return diff === 0;
  } catch { return false; }
}

export async function rollbackPromotion(pool: Pool, input: RollbackInput): Promise<{
  status: "rolled_back";
  rows_removed: number;
  promotion_id: string;
}> {
  // Load the promotion
  const p = (await pool.query(
    `SELECT promotion_id, brief_id, room_slug, status, rollback_sql
     FROM nex_lab.promotion_events WHERE promotion_id = $1`,
    [input.promotion_id],
  )).rows[0];
  if (!p) throw new Error("promotion_not_found");
  if (p.status !== "succeeded") throw new Error(`cannot_rollback_status:${p.status}`);
  if (!p.rollback_sql || String(p.rollback_sql).trim().length === 0) throw new Error("no_rollback_sql");

  // Verify timestamp drift
  const drift = Math.abs(Date.now() - Date.parse(input.rolled_back_at_iso));
  if (!Number.isFinite(drift) || drift > 300_000) throw new Error("signature_timestamp_drift");

  // Verify signature
  const valid = verifyRollbackSignature({
    brief_id: p.brief_id, room_slug: p.room_slug,
    rolled_back_at_iso: input.rolled_back_at_iso, user_id: input.rolled_back_by_user_id,
    signature: input.signature_hmac,
  });
  if (!valid) throw new Error("signature_invalid");

  // Execute rollback SQL · in a txn · count affected rows
  const client = await pool.connect();
  let rowsRemoved = 0;
  try {
    await client.query("BEGIN");
    // The rollback_sql is one or more statements separated by ";"
    // Each statement runs and we sum up rowCount. This is not
    // untrusted input — the SQL was generated by the promotion
    // executor itself at approval time.
    // Step 1 · strip full-line SQL comments (-- ... to end of line)
    // Step 2 · split on top-level semicolons
    // Step 3 · run every non-empty statement · sum rowCounts
    const stripped = String(p.rollback_sql).split("\n")
      .filter((ln) => !/^\s*--/.test(ln))
      .join("\n");
    for (const stmt of stripped.split(/;\s*(?:$|\n)/m).map((s) => s.trim()).filter(Boolean)) {
      const r = await client.query(stmt);
      rowsRemoved += r.rowCount ?? 0;
    }
    await client.query(
      `UPDATE nex_lab.promotion_events
       SET status='rolled_back',
           error_reason = coalesce(error_reason, '') || ' · rolled_back_by=' || $1 || ' at ' || $2
       WHERE promotion_id = $3`,
      [input.rolled_back_by_user_id, input.rolled_back_at_iso, input.promotion_id],
    );
    await client.query("COMMIT");
  } catch (err) {
    await client.query("ROLLBACK").catch(() => { /* ignore */ });
    throw err;
  } finally { client.release(); }

  return { status: "rolled_back", rows_removed: rowsRemoved, promotion_id: input.promotion_id };
}
