// NEX Design Catalogue · ST-CH01 · Branded Customer Chat (v2)
// (Philip 2026-08-15 · full rebuild for the world-class UX pass).
//
// The customer opened Summit's chat window. This surface must feel
// like Summit greeted them, not like a template. No NEX chrome from
// the outer product; instead a dual-agent flow inside:
//   · Summit    · the human business (tan "S" serif mark)
//   · NEX       · Summit's assistant (small olive "N" — clearly labelled)
//   · Customer  · tan-filled bubbles on the right
//
// Alive-details in this v2:
//   1. Typing indicator arrives BEFORE Summit's greeting (700ms)
//   2. Greeting rotates from a per-time-of-day pool
//   3. Bubbles slide + fade in with a spring
//   4. Presence dot slow-pulses
//   5. First customer message triggers NEX to introduce herself
//      (~1200ms after send) and set expectations honestly
//   6. Placeholder in the composer morphs through prompts
//   7. Send button subtle hover glow + tap scale
//   8. Fresh warm-frosted glass on floating header + composer
//      (Philip 2026-08-15 · "not shaded")

"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { MT1_TOKENS as T } from "../tokens";

type Agent = "summit" | "nex" | "customer";
type Msg = { agent: Agent; text: string };

type Config = {
  brandName?: string;
  brandInitial?: string;
  presence?: "online" | "away";
  presenceCaption?: string;
  suggestedPrompts?: string[];
  initialConversation?: Msg[];
  /** If true, skip the auto-greeting flow (useful for testing empty state). */
  skipGreeting?: boolean;
  /**
   * Chat wallpaper (Philip 2026-08-15). Owner-swappable later via
   * NEX Assist ("change my chat wallpaper"). Default is Summit's
   * Premium Architectural wallpaper on ImageKit.
   */
  chatBackgroundUrl?: string;
};

const DEFAULTS: Required<Config> = {
  brandName:       "Summit",
  brandInitial:    "S",
  presence:        "online",
  presenceCaption: "Typically replies within an hour",
  suggestedPrompts: [
    "I want a floating oak staircase — how much roughly?",
    "Do you install in my area?",
    "Can I see examples of your work?",
    "How long does a staircase project take?"
  ],
  initialConversation: [],
  skipGreeting: false,
  chatBackgroundUrl: "https://ik.imagekit.io/5vv5pw26q/ChatGPT%20Image%20Aug%2015,%202026,%2001_05_08%20AM.png"
};

/* Time-of-day welcome pool · rotates on every mount so no visitor
 * sees the same greeting twice in a row. */
const GREETINGS = {
  morning: [
    "Good morning — welcome to Summit. What's on your mind about your staircase today?",
    "Morning. Great to have you. Are you exploring designs, or ready for a quote?",
    "Hello and good morning. Tell us a little about your project."
  ],
  afternoon: [
    "Good afternoon. Thanks for stopping by — how can we help with your staircase?",
    "Afternoon. Welcome in. Something specific in mind, or just browsing?",
    "Hello. Are you looking at ideas, checking if we cover your area, or after pricing?"
  ],
  evening: [
    "Good evening. Welcome to Summit. What brought you in tonight?",
    "Evening — glad you're here. Tell us what you're working on.",
    "Good evening. How can we help — designs, materials, or coverage?"
  ],
  neutral: [
    "Welcome to Summit. What are you working on?",
    "Hi there — we'd love to help. Where would you like to start?"
  ]
} as const;

// The NEX reply is generated by the local NEX conversation pipeline
// (ADR-0044 · POST /api/nex-conv/chat → processTurn → local Qwen).
// No canned line is used in the normal flow. If the very first call fails
// (server booting, Ollama not running, etc.) the customer sees the fallback
// once and can retry.
const NEX_ERROR_FALLBACK = "Give me a moment — the assistant is still starting up. Please send that again in a few seconds.";

const COMPOSER_PLACEHOLDERS = [
  "Ask Summit anything about your staircase…",
  "Try: how much for a floating oak staircase?",
  "Try: do you install in my area?",
  "Try: can I see examples of your work?",
  "Try: how long does a project take?"
];

export function STCH01(props: Config = {}) {
  const c = { ...DEFAULTS, ...props };
  const [messages, setMessages] = useState<Msg[]>(c.initialConversation);
  const [input, setInput] = useState("");
  const [thinking, setThinking] = useState<Agent | null>(null);
  const [customerHasSpoken, setCustomerHasSpoken] = useState(false);
  const [placeholderIdx, setPlaceholderIdx] = useState(0);
  const streamRef = useRef<HTMLDivElement | null>(null);

  const isEmpty = messages.length === 0 && thinking === null;

  /* ── Auto-greeting on mount ─────────────────────────────────────
   * 700ms of Summit "typing" · then the greeting bubble slides in. */
  useEffect(() => {
    if (c.skipGreeting || c.initialConversation.length > 0) return;
    const greeting = pickGreeting();
    setThinking("summit");
    const timer = window.setTimeout(() => {
      setThinking(null);
      setMessages([{ agent: "summit", text: greeting }]);
    }, 900);
    return () => window.clearTimeout(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  /* ── Placeholder morph · cycles the composer hint every 4s ───── */
  useEffect(() => {
    if (input.length > 0) return;
    const t = window.setInterval(() => {
      setPlaceholderIdx((i) => (i + 1) % COMPOSER_PLACEHOLDERS.length);
    }, 4000);
    return () => window.clearInterval(t);
  }, [input]);

  // Per-browser conversation id · one-shot on mount · persisted in
  // localStorage so a page reload resumes the same conversation state
  // that Postgres has for it.
  const conversationIdRef = useRef<string | null>(null);
  useEffect(() => {
    if (typeof window === "undefined") return;
    const KEY = "nex-conv-id-mt1";
    let id = window.localStorage.getItem(KEY);
    if (!id) {
      id = (window.crypto?.randomUUID?.() ?? `mt1-${Math.random().toString(36).slice(2)}-${Date.now().toString(36)}`);
      window.localStorage.setItem(KEY, id);
    }
    conversationIdRef.current = id;
    // Fire-and-forget warmup so the customer's first real message doesn't
    // wait through store-init + Ollama cold-load (~15-30s).
    fetch("/api/nex-conv/chat", { method: "GET" }).catch(() => { /* silent */ });
  }, []);

  const send = useCallback(async (raw: string) => {
    const text = raw.trim();
    if (!text) return;
    setInput("");
    setMessages((m) => [...m, { agent: "customer", text }]);
    if (!customerHasSpoken) setCustomerHasSpoken(true);

    // NEX is the one actually responding · routed via the local NEX
    // conversation pipeline (ADR-0044). Summit stays quiet until we
    // wire her separately (out-of-hours handoff etc). Zero canned
    // replies · zero third-party AI · everything through local Qwen.
    setThinking("nex");
    try {
      const resp = await fetch("/api/nex-conv/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          conversation_id: conversationIdRef.current,
          message: text,
        }),
      });
      const j = (await resp.json().catch(() => null)) as { reply?: string; conversation_id?: string; error?: string } | null;
      if (!resp.ok) {
        const errMsg = j?.error ? `Hmm — ${j.error}` : NEX_ERROR_FALLBACK;
        setMessages((m) => [...m, { agent: "nex", text: errMsg }]);
      } else if (!j?.reply) {
        setMessages((m) => [...m, { agent: "nex", text: NEX_ERROR_FALLBACK }]);
      } else {
        setMessages((m) => [...m, { agent: "nex", text: j.reply as string }]);
        if (typeof j.conversation_id === "string") {
          conversationIdRef.current = j.conversation_id;
        }
      }
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      setMessages((m) => [...m, { agent: "nex", text: `${NEX_ERROR_FALLBACK} (${message.slice(0, 80)})` }]);
    } finally {
      setThinking(null);
    }
  }, [customerHasSpoken]);

  useEffect(() => {
    const el = streamRef.current;
    if (!el) return;
    el.scrollTo({ top: el.scrollHeight, behavior: "smooth" });
  }, [messages, thinking]);

  const onSubmit = useCallback((e: React.FormEvent) => {
    e.preventDefault();
    send(input);
  }, [send, input]);

  const rotatedPlaceholder = COMPOSER_PLACEHOLDERS[placeholderIdx];

  return (
    <div
      data-section-id="ST-CH01"
      data-master-template="1"
      data-vertical="staircase"
      data-family="premium-architectural"
      style={{
        position: "relative",
        minHeight: "100dvh",
        // Wallpaper set on the container · owner-swappable later via
        // NEX Assist ("change my chat wallpaper"). Cream fallback under
        // the image in case it fails to load.
        background: `${T.color.surface} url(${c.chatBackgroundUrl}) center/cover fixed no-repeat`,
        color: T.color.ink,
        fontFamily: T.font.sans,
        display: "flex",
        flexDirection: "column"
      }}
    >
      <FloatingHeader c={c} />

      <div
        ref={streamRef}
        style={{
          flex: 1,
          overflowY: "auto",
          scrollBehavior: "smooth",
          padding: "112px clamp(16px, 4vw, 40px) 24px",
          display: "flex",
          flexDirection: "column"
        }}
      >
        <div style={{ maxWidth: 760, width: "100%", margin: "0 auto", flex: 1, display: "flex", flexDirection: "column" }}>
          {isEmpty && messages.length === 0 && (
            <EmptyState c={c} onPrompt={send} />
          )}

          {messages.length > 0 && (
            <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
              {messages.map((m, i) => (
                <MessageBubble
                  key={i}
                  msg={m}
                  brandInitial={c.brandInitial}
                  index={i}
                />
              ))}
            </div>
          )}

          {thinking && (
            <div style={{ marginTop: messages.length > 0 ? 14 : 0 }}>
              <ThinkingBubble
                agent={thinking}
                brandInitial={c.brandInitial}
              />
            </div>
          )}
        </div>
      </div>

      <Composer
        value={input}
        onChange={setInput}
        onSubmit={onSubmit}
        placeholder={rotatedPlaceholder}
      />

      {/* Global animations · used by bubbles + presence pulse */}
      <style>{`
        @keyframes mt1-msg-in {
          from { opacity: 0; transform: translateY(8px) scale(0.98); }
          to   { opacity: 1; transform: translateY(0)   scale(1); }
        }
        @keyframes mt1-presence-pulse {
          0%, 100% { box-shadow: 0 0 0 0   rgba(76, 179, 125, 0.55); }
          70%      { box-shadow: 0 0 0 8px rgba(76, 179, 125, 0);    }
        }
        @keyframes mt1-think-bob {
          0%, 80%, 100% { transform: translateY(0);  opacity: 0.35; }
          40%           { transform: translateY(-4px); opacity: 1; }
        }
        @keyframes mt1-placeholder-fade {
          0%   { opacity: 0; transform: translateY(4px); }
          100% { opacity: 1; transform: translateY(0); }
        }
        .mt1-bubble-in { animation: mt1-msg-in 320ms cubic-bezier(0.22, 1, 0.36, 1) both; }
        .mt1-presence  { animation: mt1-presence-pulse 2.6s ease-out infinite; }
        @media (prefers-reduced-motion: reduce) {
          .mt1-bubble-in, .mt1-presence { animation: none !important; }
        }
        /* Hide the Next.js dev-tools indicator (yellow burger top-right)
           on the chat surface · Philip 2026-08-15. Dev-only artefact,
           never shipped to customers anyway. */
        nextjs-portal,
        [data-nextjs-toast],
        [data-nextjs-dialog-overlay],
        #__next-build-watcher,
        #vercel-live-feedback { display: none !important; }
      `}</style>
    </div>
  );
}

/* ══════════════════════════════════════════════════════════════════
   FLOATING HEADER · fresh warm-frosted glass (Philip 2026-08-15)
   ══════════════════════════════════════════════════════════════════ */

function FloatingHeader({ c }: { c: Required<Config> }) {
  return (
    <header
      style={{
        position: "fixed",
        top: "clamp(12px, 2vw, 20px)",
        left: "50%",
        transform: "translateX(-50%)",
        zIndex: 40,
        maxWidth: "min(720px, calc(100vw - 24px))",
        width: "100%"
      }}
    >
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 12,
          padding: "10px 14px",
          borderRadius: 999,
          // Fresh warm-frosted glass · Philip 2026-08-15 (not the
          // heavier brown we had before). Cream tint + heavy blur.
          background: "rgba(253, 249, 240, 0.65)",
          backdropFilter: "blur(28px) saturate(200%)",
          WebkitBackdropFilter: "blur(28px) saturate(200%)",
          border: "1px solid rgba(58, 52, 40, 0.06)",
          boxShadow: "0 8px 32px -12px rgba(58, 52, 40, 0.18)"
        }}
      >
        {/* Summit brand mark */}
        <div
          aria-hidden
          style={{
            width: 36,
            height: 36,
            borderRadius: "50%",
            background: T.color.accent,
            color: "#FFFFFF",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            fontFamily: T.font.serif,
            fontSize: 18,
            fontWeight: 500,
            flexShrink: 0,
            boxShadow: "0 4px 12px -4px rgba(181, 143, 94, 0.5)"
          }}
        >
          {c.brandInitial}
        </div>

        <div style={{ minWidth: 0, flex: 1, lineHeight: 1.15 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <span style={{ fontFamily: T.font.serif, fontSize: 16, fontWeight: 500, color: T.color.ink, letterSpacing: "-0.005em" }}>
              {c.brandName}
            </span>
            <span
              aria-hidden
              className={c.presence === "online" ? "mt1-presence" : undefined}
              style={{
                width: 8,
                height: 8,
                borderRadius: "50%",
                background: c.presence === "online" ? "#4CB37D" : "#B58F5E"
              }}
            />
          </div>
          <div style={{ fontSize: 11, color: T.color.inkMuted, marginTop: 2 }}>
            {c.presenceCaption}
          </div>
        </div>

        {/* Home button on the right · returns to Summit's landing page.
            Circle inside the header container · Philip 2026-08-15. */}
        <a
          href="/nex-app/design-catalogue/staircase/master-template-1"
          aria-label="Home"
          title="Home"
          style={{
            width: 32,
            height: 32,
            flexShrink: 0,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            borderRadius: "50%",
            background: "rgba(58, 52, 40, 0.06)",
            color: T.color.ink,
            textDecoration: "none",
            transition: "background 120ms, color 120ms"
          }}
          onMouseEnter={(e) => { e.currentTarget.style.background = "rgba(58, 52, 40, 0.12)"; e.currentTarget.style.color = T.color.accent; }}
          onMouseLeave={(e) => { e.currentTarget.style.background = "rgba(58, 52, 40, 0.06)"; e.currentTarget.style.color = T.color.ink; }}
        >
          <svg width={14} height={14} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8} strokeLinecap="round" strokeLinejoin="round" aria-hidden>
            <path d="m3 11 9-8 9 8" />
            <path d="M5 10v10h5v-6h4v6h5V10" />
          </svg>
        </a>
      </div>
    </header>
  );
}

/* ══════════════════════════════════════════════════════════════════
   EMPTY STATE · shown only briefly if the greeting is skipped
   ══════════════════════════════════════════════════════════════════ */

function EmptyState({ c, onPrompt }: { c: Required<Config>; onPrompt: (t: string) => void }) {
  return (
    <div
      style={{
        flex: 1,
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "flex-start",
        gap: 22
      }}
    >
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))",
          gap: 10,
          width: "100%"
        }}
      >
        {c.suggestedPrompts.map((p) => (
          <button
            key={p}
            type="button"
            onClick={() => onPrompt(p)}
            style={{
              display: "flex",
              alignItems: "flex-start",
              gap: 10,
              padding: "14px 16px",
              background: T.color.surfaceCard,
              border: `1px solid ${T.color.hairline}`,
              borderRadius: 12,
              textAlign: "left",
              cursor: "pointer",
              fontFamily: T.font.sans,
              fontSize: 13.5,
              lineHeight: 1.45,
              color: T.color.ink,
              transition: "border-color 120ms, transform 120ms, box-shadow 120ms"
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.borderColor = T.color.accent;
              e.currentTarget.style.transform = "translateY(-2px)";
              e.currentTarget.style.boxShadow = "0 8px 20px -12px rgba(58, 52, 40, 0.18)";
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.borderColor = T.color.hairline;
              e.currentTarget.style.transform = "translateY(0)";
              e.currentTarget.style.boxShadow = "none";
            }}
          >
            <span aria-hidden style={{ color: T.color.accent, flexShrink: 0, marginTop: 1 }}>
              <svg width={14} height={14} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
                <path d="M4 12h16" /><path d="m14 6 6 6-6 6" />
              </svg>
            </span>
            <span>{p}</span>
          </button>
        ))}
      </div>
    </div>
  );
}

/* ══════════════════════════════════════════════════════════════════
   MESSAGE BUBBLES · Summit · NEX · Customer · distinct visual language
   ══════════════════════════════════════════════════════════════════ */

function MessageBubble({ msg, brandInitial, index }: { msg: Msg; brandInitial: string; index: number }) {
  if (msg.agent === "customer") {
    return (
      <div className="mt1-bubble-in" style={{ display: "flex", justifyContent: "flex-end" }}>
        <div
          style={{
            background: T.color.accent,
            color: "#FFFFFF",
            borderRadius: 18,
            borderBottomRightRadius: 4,
            padding: "12px 16px",
            fontSize: 14.5,
            lineHeight: 1.5,
            maxWidth: "78%",
            whiteSpace: "pre-wrap",
            boxShadow: "0 8px 20px -14px rgba(181, 143, 94, 0.6)"
          }}
        >
          {msg.text}
        </div>
      </div>
    );
  }

  // NEX + Summit share the "left bubble" pattern but with distinct
  // avatar treatments so the customer can tell who's speaking.
  const isNex = msg.agent === "nex";
  return (
    <div className="mt1-bubble-in" style={{ display: "flex", gap: 10, alignItems: "flex-end" }}>
      <AgentAvatar agent={msg.agent} brandInitial={brandInitial} />
      <div style={{ display: "flex", flexDirection: "column", gap: 4, maxWidth: "78%" }}>
        {isNex && (
          <div style={{ fontSize: 10, letterSpacing: "0.18em", textTransform: "uppercase", color: "#C6906F", fontWeight: 700, marginLeft: 2 }}>
            Nex · Assistant
          </div>
        )}
        <div
          style={{
            background: T.color.surfaceCard,
            border: `1px solid ${isNex ? "rgba(198, 144, 111, 0.28)" : T.color.hairline}`,
            borderRadius: 18,
            borderBottomLeftRadius: 4,
            padding: "12px 16px",
            fontSize: 14.5,
            lineHeight: 1.55,
            color: T.color.ink,
            whiteSpace: "pre-wrap",
            boxShadow: "0 2px 8px -4px rgba(58, 52, 40, 0.06)"
          }}
        >
          {msg.text}
        </div>
      </div>
    </div>
  );
}

function AgentAvatar({ agent, brandInitial }: { agent: Agent; brandInitial: string }) {
  if (agent === "nex") {
    // NEX · orange · "Nex" text (Philip 2026-08-15) · clearly a
    // system helper, distinct from Summit's tan brand mark.
    return (
      <div
        aria-hidden
        style={{
          width: 30, height: 30, flexShrink: 0,
          borderRadius: "50%",
          background: "#C6906F",
          color: "#FFFFFF",
          display: "flex", alignItems: "center", justifyContent: "center",
          fontFamily: T.font.sans, fontSize: 11, fontWeight: 700, letterSpacing: "-0.01em"
        }}
      >
        Nex
      </div>
    );
  }
  // Summit · warm tan, serif "S", concierge feel
  return (
    <div
      aria-hidden
      style={{
        width: 28, height: 28, flexShrink: 0,
        borderRadius: "50%",
        background: T.color.accent,
        color: "#FFFFFF",
        display: "flex", alignItems: "center", justifyContent: "center",
        fontFamily: T.font.serif, fontSize: 14, fontWeight: 500
      }}
    >
      {brandInitial}
    </div>
  );
}

function ThinkingBubble({ agent, brandInitial }: { agent: Agent; brandInitial: string }) {
  return (
    <div className="mt1-bubble-in" style={{ display: "flex", gap: 10, alignItems: "flex-end" }}>
      <AgentAvatar agent={agent} brandInitial={brandInitial} />
      <div
        style={{
          background: T.color.surfaceCard,
          border: `1px solid ${T.color.hairline}`,
          borderRadius: 18,
          borderBottomLeftRadius: 4,
          padding: "14px 18px",
          display: "flex",
          alignItems: "center",
          gap: 6
        }}
      >
        <ThinkDot delay={0} />
        <ThinkDot delay={0.15} />
        <ThinkDot delay={0.3} />
      </div>
    </div>
  );
}

function ThinkDot({ delay }: { delay: number }) {
  return (
    <span
      aria-hidden
      style={{
        width: 6, height: 6, borderRadius: "50%",
        background: T.color.inkFaint,
        animation: `mt1-think-bob 1.2s ease-in-out ${delay}s infinite`
      }}
    />
  );
}

/* ══════════════════════════════════════════════════════════════════
   COMPOSER · fresh warm-frosted glass · action buttons · morphing hint
   ══════════════════════════════════════════════════════════════════ */

function Composer({
  value,
  onChange,
  onSubmit,
  placeholder
}: {
  value: string;
  onChange: (v: string) => void;
  onSubmit: (e: React.FormEvent) => void;
  placeholder: string;
}) {
  return (
    <form
      onSubmit={onSubmit}
      style={{
        position: "sticky",
        bottom: 0,
        padding: "12px clamp(16px, 4vw, 40px) clamp(16px, 3vw, 24px)",
        // Transparent so the wallpaper shows through; the composer's
        // own frosted glass provides the anchor.
        background: "transparent",
        zIndex: 30
      }}
    >
      <div
        style={{
          maxWidth: 760,
          margin: "0 auto",
          display: "flex",
          alignItems: "center",
          gap: 8
        }}
      >
        {/* Wide input pill · takes all remaining width · Philip 2026-08-15 */}
        <div
          style={{
            flex: 1,
            display: "flex",
            alignItems: "center",
            gap: 6,
            padding: "8px 8px 8px 18px",
            background: "rgba(253, 249, 240, 0.75)",
            backdropFilter: "blur(28px) saturate(200%)",
            WebkitBackdropFilter: "blur(28px) saturate(200%)",
            border: "1px solid rgba(58, 52, 40, 0.06)",
            borderRadius: 999,
            boxShadow: "0 12px 28px -14px rgba(58, 52, 40, 0.15)",
            minWidth: 0
          }}
        >
          <input
            type="text"
            value={value}
            onChange={(e) => onChange(e.target.value)}
            placeholder={placeholder}
            key={placeholder /* trigger the fade animation on morph */}
            style={{
              flex: 1,
              border: "none",
              outline: "none",
              background: "transparent",
              fontSize: 14.5,
              fontFamily: T.font.sans,
              color: T.color.ink,
              padding: "10px 4px",
              animation: value.length === 0 ? "mt1-placeholder-fade 420ms ease-out" : "none",
              minWidth: 0
            }}
            className="mt1-chat-input"
          />
          <button
            type="submit"
            aria-label="Send"
            disabled={!value.trim()}
            className="mt1-send-btn"
            style={{
              width: 40,
              height: 40,
              flexShrink: 0,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              // Philip 2026-08-15 · always coloured (tan) · fingerprint
              // glyph replaces the arrow. Disabled state dims to a
              // softer tan rather than dropping to grey.
              background: value.trim() ? T.color.accent : "#D9B58C",
              color: "#FFFFFF",
              border: "none",
              borderRadius: "50%",
              cursor: value.trim() ? "pointer" : "default",
              transition: "background 160ms, transform 120ms, box-shadow 160ms",
              boxShadow: value.trim()
                ? "0 6px 18px -6px rgba(181, 143, 94, 0.65)"
                : "0 4px 12px -6px rgba(181, 143, 94, 0.35)"
            }}
          >
            <FingerprintGlyph />
          </button>
        </div>

        {/* Outside-right icons · attachment + video · Philip 2026-08-15
            Sit as separate glass circles so the text field owns the full
            width of the pill. */}
        <OutsideIcon icon="attach" label="Attach a file" />
        <OutsideIcon icon="video"  label="Send a video" />
      </div>

      <style>{`
        .mt1-chat-input::placeholder { color: rgba(58, 52, 40, 0.42); }
        .mt1-send-btn:not(:disabled):hover { box-shadow: 0 10px 24px -6px rgba(181, 143, 94, 0.8); }
        .mt1-send-btn:not(:disabled):active { transform: scale(0.94); }
      `}</style>
    </form>
  );
}

/**
 * Standalone circular icon button sitting OUTSIDE the input pill.
 * Same frosted glass as the pill so the row reads as one system.
 */
function OutsideIcon({ icon, label }: { icon: "attach" | "video"; label: string }) {
  return (
    <button
      type="button"
      aria-label={label}
      title={label}
      style={{
        width: 44,
        height: 44,
        flexShrink: 0,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "rgba(253, 249, 240, 0.75)",
        backdropFilter: "blur(28px) saturate(200%)",
        WebkitBackdropFilter: "blur(28px) saturate(200%)",
        color: T.color.ink,
        border: "1px solid rgba(58, 52, 40, 0.06)",
        borderRadius: "50%",
        cursor: "pointer",
        transition: "color 120ms, transform 120ms, box-shadow 160ms",
        boxShadow: "0 12px 28px -14px rgba(58, 52, 40, 0.15)"
      }}
      onMouseEnter={(e) => { e.currentTarget.style.color = T.color.accent; e.currentTarget.style.transform = "translateY(-1px)"; }}
      onMouseLeave={(e) => { e.currentTarget.style.color = T.color.ink; e.currentTarget.style.transform = "translateY(0)"; }}
    >
      <OutsideIconGlyph slug={icon} />
    </button>
  );
}

/**
 * Fingerprint · signature send glyph (Philip 2026-08-15). Nested arcs
 * mimic finger ridges — the message is "signed" by the customer, not
 * just fired off. Feels more considered than a paper-plane / arrow.
 */
function FingerprintGlyph() {
  return (
    <svg width={18} height={18} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.6} strokeLinecap="round" strokeLinejoin="round" aria-hidden>
      <path d="M12 3.5a8.5 8.5 0 0 0-8.5 8.5" />
      <path d="M12 3.5a8.5 8.5 0 0 1 8.5 8.5v2" />
      <path d="M12 6.75a5.25 5.25 0 0 0-5.25 5.25v4" />
      <path d="M12 6.75a5.25 5.25 0 0 1 5.25 5.25v4a3.5 3.5 0 0 1-1.2 2.7" />
      <path d="M12 10a2 2 0 0 0-2 2v5.5" />
      <path d="M12 10a2 2 0 0 1 2 2v5a4 4 0 0 1-1 1.6" />
    </svg>
  );
}

function OutsideIconGlyph({ slug }: { slug: "attach" | "video" }) {
  const props = { width: 18, height: 18, viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: 1.6, strokeLinecap: "round" as const, strokeLinejoin: "round" as const, "aria-hidden": true };
  switch (slug) {
    case "attach":
      return (
        <svg {...props}>
          <path d="M20 12 12 20a5 5 0 0 1-7-7l9-9a3.5 3.5 0 0 1 5 5l-9 9a2 2 0 0 1-3-3l8-8" />
        </svg>
      );
    case "video":
      return (
        <svg {...props}>
          <rect x="3" y="6" width="13" height="12" rx="2" />
          <path d="m16 10 5-3v10l-5-3z" />
        </svg>
      );
  }
}

/* ══════════════════════════════════════════════════════════════════
   Helpers · greeting picker + stub Summit replies
   ══════════════════════════════════════════════════════════════════ */

function pickGreeting(): string {
  const hour = new Date().getHours();
  let pool: readonly string[];
  if (hour < 12) pool = GREETINGS.morning;
  else if (hour < 18) pool = GREETINGS.afternoon;
  else if (hour < 22) pool = GREETINGS.evening;
  else pool = GREETINGS.neutral;
  return pool[Math.floor(Math.random() * pool.length)];
}

// stubReplyFor removed 2026-08-15 · replies now come from
// POST /api/nex-conv/chat → NEX pipeline → local Qwen (ADR-0044).
// The regex-keyword canned replies (with a fabricated £8,900 price!) are
// exactly the pattern Philip called out as unacceptable. Do not re-add
// per-keyword canned copy — extend the NEX knowledge packet instead.
