// canteenFeedTileLibrary — types + static seed for the Live Feed Tile
// library. The DB table `hammerex_feed_tile_library` is the runtime
// source of truth (managed via /admin/feed-tile-library); this file
// is the fallback seed when the DB is unreachable AND provides pure
// filter helpers used by client components.
//
// Every seed entry is Philip-approved per the image copyright rule
// (see feedback_image_copyright_risk_rules.md):
//   • AI-generated by Philip
//   • licensed stock
//   • trade-submitted with T&C warrant
//   • commissioned

export type FeedTileTextTone = "white" | "black" | "gray";

export type FeedTileLibraryImage = {
  /** Stable identifier — used as React key and analytics slug. */
  id: string;
  /** Canonical hosted URL (CDN or Supabase Storage). */
  url: string;
  /** Short human description shown as alt text + hover title. */
  alt: string;
  /** Recommended feed-text tone against this background. `white`
   *  (default) pairs with the standard dark scrim overlay; `black`
   *  is used for genuinely light images that would drown white
   *  text even with scrim (e.g. freshly-taped drywall). Render
   *  pipeline uses this to swap the scrim + text colour. */
  textTone?: FeedTileTextTone;
};

// Entries used as the fallback seed AND as the initial payload the
// DB was populated from (see the seed SQL in the B1 migration).
// Kept together so re-seeding is trivial: DB truncate → run the
// same INSERT that mirrors this list.
const IMG = {
  plumbing:            { url: "https://ik.imagekit.io/9mrgsv2rp/ChatGPT%20Image%20Jul%2016,%202026,%2007_42_12%20PM.png", alt: "Chrome plumbing tools laid against a deep blue underwater backdrop" },
  toolbelts_hammerex:  { url: "https://ik.imagekit.io/9mrgsv2rp/ChatGPT%20Image%20Jul%2017,%202026,%2001_37_15%20AM.png", alt: "Hammerex tool bag with drivers, drills and circular saw on black backdrop" },
  bricklayer:          { url: "https://ik.imagekit.io/9mrgsv2rp/ChatGPT%20Image%20Jul%2017,%202026,%2001_41_56%20AM.png", alt: "Red brick wall with wheelbarrow, trowels and stacked bricks" },
  plasterer:           { url: "https://ik.imagekit.io/9mrgsv2rp/ChatGPT%20Image%20Jul%2017,%202026,%2001_46_02%20AM.png", alt: "Textured grey plaster wall with float, hawk and mixing bucket" },
  landscaping:         { url: "https://ik.imagekit.io/9mrgsv2rp/ChatGPT%20Image%20Jul%2017,%202026,%2001_49_05%20AM.png", alt: "Stone garden wall with planted border, wheelbarrow, shovel and rake" },
  electrician:         { url: "https://ik.imagekit.io/9mrgsv2rp/ChatGPT%20Image%20Jul%2017,%202026,%2001_54_55%20AM.png", alt: "Wired consumer unit with tester, drill and full electrician tool pouch" },
  carpenter_wood:      { url: "https://ik.imagekit.io/9mrgsv2rp/ChatGPT%20Image%20Jul%2017,%202026,%2002_10_47%20AM.png", alt: "Rustic carpenter workshop with leather tool belt, saws, drill and shavings" },
  garden_shed:         { url: "https://ik.imagekit.io/9mrgsv2rp/ChatGPT%20Image%20Jul%2017,%202026,%2002_15_01%20AM.png", alt: "Timber garden shed exterior with rakes, watering can, boots and toolbox" },
  lawn_seeding:        { url: "https://ik.imagekit.io/9mrgsv2rp/ChatGPT%20Image%20Jul%2017,%202026,%2002_21_34%20AM.png", alt: "Petrol tiller on freshly turned soil with heather, hand tools and twine" },
  tiling:              { url: "https://ik.imagekit.io/9mrgsv2rp/ChatGPT%20Image%20Jul%2017,%202026,%2002_32_29%20AM.png", alt: "Dark slate wall tiles with notched trowel, level, tile spacers and cutter" },
  drywall_taping:      { url: "https://ik.imagekit.io/9mrgsv2rp/ChatGPT%20Image%20Jul%2017,%202026,%2002_49_00%20AM.png", alt: "Freshly-taped drywall joints in white compound with mud pan, hawks and knife" },
  tool_hire:           { url: "https://ik.imagekit.io/9mrgsv2rp/ChatGPT%20Image%20Jul%2017,%202026,%2002_50_33%20AM.png", alt: "Yellow-branded rentable plant — breaker, ladder, mixer, saw — on concrete floor" },
  carpenter_roofing:   { url: "https://ik.imagekit.io/9mrgsv2rp/ChatGPT%20Image%20Jul%2017,%202026,%2002_56_42%20AM.png", alt: "Roofing job with slate stack, timber battens, tool belt, saw and hammer" },
  skip_hire:           { url: "https://ik.imagekit.io/9mrgsv2rp/ChatGPT%20Image%20Jul%2017,%202026,%2003_02_23%20AM.png", alt: "Yellow skip full of rubble beside safety cone, barrier and wheelbarrow" },
  pool_supplies:       { url: "https://ik.imagekit.io/9mrgsv2rp/ChatGPT%20Image%20Jul%2017,%202026,%2003_07_12%20AM.png", alt: "Pool maintenance kit — pump, chlorine, hose, test strips — beside a tiled pool" },
  pool_builders:       { url: "https://ik.imagekit.io/9mrgsv2rp/ChatGPT%20Image%20Jul%2017,%202026,%2003_29_09%20AM.png", alt: "Half-built pool with blue mosaic tiles, pool-mortar bags and wheelbarrow" },
  kitchen_manufacture: { url: "https://ik.imagekit.io/9mrgsv2rp/ChatGPT%20Image%20Jul%2017,%202026,%2003_39_50%20AM.png", alt: "Kitchen cabinet build in progress with shaker doors, hinges and drill" }
} as const;

/** Static fallback seed. Used when the DB is unreachable so previews
 *  never blank out. Trade-agnostic list; filtering happens in
 *  `filterByTrade` on the client. */
export const STATIC_FEED_TILE_LIBRARY: Array<FeedTileLibraryImage & { trade_slugs: string[] }> = [
  { id: "plumbing-01",            trade_slugs: ["plumber"],                                                     ...IMG.plumbing },
  { id: "toolbelts-hammerex-01",  trade_slugs: ["scaffolder", "building-merchant", "tool-supplier"],            ...IMG.toolbelts_hammerex },
  { id: "bricklayer-01",          trade_slugs: ["bricklayer"],                                                  ...IMG.bricklayer },
  { id: "plasterer-01",           trade_slugs: ["plasterer"],                                                   ...IMG.plasterer },
  { id: "landscaping-01",         trade_slugs: ["landscaper", "garden-designer", "luxury-garden-designer"],     ...IMG.landscaping },
  { id: "electrician-01",         trade_slugs: ["electrician"],                                                 ...IMG.electrician },
  { id: "carpenter-wood-01",      trade_slugs: ["carpenter", "bespoke-joiner", "master-carpenter"],             ...IMG.carpenter_wood },
  { id: "garden-shed-01",         trade_slugs: ["garden-buildings", "shed-supplier", "carpenter"],              ...IMG.garden_shed },
  { id: "lawn-seed-01",           trade_slugs: ["landscaper"],                                                  ...IMG.lawn_seeding },
  { id: "tiling-01",              trade_slugs: ["tiler"],                                                       ...IMG.tiling },
  { id: "drywall-taping-01",      trade_slugs: ["drywaller", "drywall-taper", "plasterboard-fitter"], textTone: "black", ...IMG.drywall_taping },
  { id: "tool-hire-01",           trade_slugs: ["tool-hire", "plant-hire"],                                     ...IMG.tool_hire },
  { id: "carpenter-roofing-01",   trade_slugs: ["roofer", "roofer-tile", "carpenter"],                          ...IMG.carpenter_roofing },
  { id: "skip-hire-01",           trade_slugs: ["skip-hire", "waste-clearance"],                                ...IMG.skip_hire },
  { id: "pool-supplies-01",       trade_slugs: ["swimming-pool-supplier", "pool-builder"],                      ...IMG.pool_supplies },
  { id: "pool-builders-01",       trade_slugs: ["pool-builder"],                                                ...IMG.pool_builders },
  { id: "kitchen-manufacture-01", trade_slugs: ["kitchen-fitter", "kitchen-manufacturer"],                      ...IMG.kitchen_manufacture }
];

/** Pure filter — return every library entry that lists this trade
 *  slug. Client callers pass the DB-loaded (or static-seed) list. */
export function filterByTrade(
  library: ReadonlyArray<FeedTileLibraryImage & { trade_slugs: string[] }>,
  tradeSlug: string | null | undefined
): FeedTileLibraryImage[] {
  if (!tradeSlug) return [];
  return library
    .filter((e) => e.trade_slugs.includes(tradeSlug))
    .map((e) => ({ id: e.id, url: e.url, alt: e.alt, textTone: e.textTone }));
}

/** Pure URL lookup — used by the canteen renderer to fetch the
 *  recommended textTone for a saved feed_tile_image_url. */
export function libraryEntryByUrl(
  library: ReadonlyArray<FeedTileLibraryImage & { trade_slugs: string[] }>,
  url: string | null | undefined
): FeedTileLibraryImage | null {
  if (!url) return null;
  return library.find((e) => e.url === url) ?? null;
}

// ── Back-compat exports ─────────────────────────────────────
// Existing call sites imported `libraryImagesForTrade` and the
// URL lookup with different signatures. Wrappers below preserve
// those signatures so unmigrated callers keep compiling; both
// wrappers use STATIC_FEED_TILE_LIBRARY (the seed) rather than DB.
// New code should call the pure functions above and pass a
// DB-loaded library array.

export function libraryImagesForTrade(tradeSlug: string | null | undefined): FeedTileLibraryImage[] {
  return filterByTrade(STATIC_FEED_TILE_LIBRARY, tradeSlug);
}

/** Single-arg URL lookup — back-compat shim for callers that don't
 *  yet receive the DB-loaded library as a prop. Uses the static seed.
 *  Prefer `libraryEntryByUrl(library, url)` (two-arg) in new code. */
export function libraryEntryByUrlStatic(url: string | null | undefined): FeedTileLibraryImage | null {
  return libraryEntryByUrl(STATIC_FEED_TILE_LIBRARY, url);
}
