// AUTO-GENERATED placeholder for scripts/populate-demo-videos.mjs.
// Maps trade_slug → Pexels video URL for demo-profile intro videos.
//
// RULE (see the public profile page):
//  - Demo profiles (slug starts with "demo-") fall back to this map when
//    their own video_url is null, so visitors always see a relevant
//    theme video on the demo profile.
//  - Real tradespeople NEVER read from this map — if they haven't
//    uploaded a clip the video section is hidden entirely.
//
// Empty string ("") means "no fallback yet — skip the section even on a
// demo profile". A scheduled populator script fills these in with real
// Pexels theme videos keyed by trade.

export const DEMO_TRADE_VIDEOS: Record<string, string> = {
  drywaller: "",
  plasterer: "",
  electrician:
    "https://msdonkkechxzgagyguoe.supabase.co/storage/v1/object/public/product-images/demo-videos/electrician-intro.mp4",
  scaffolder: "",
  tiler: "",
  plumber: "",
  carpenter: "",
  joiner: "",
  painter: "",
  roofer: "",
  bricklayer: "",
  stonemason: "",
  groundworker: "",
  "general-builder": "",
  "concrete-specialist": "",
  renderer: "",
  "taper-and-finisher": "",
  "building-merchant": "",
  "metal-engineer": "",
  "heavy-machinery": "",
  "tool-hire": "",
  landscaper: "",
  "gas-engineer": "",
  "concrete-finisher": "",
  "stair-fitter": "",
  "kitchen-fitter": "",
  "window-fitter": "",
  "crane-operator": "",
  "security-installer": "",
  "builders-supplies": "",
  formworker: "",
  "insulation-installer": "",
  "trim-carpenter": "",
  "block-layer": "",
  "site-safety": "",
  "water-drilling": "",
  "fascia-and-soffit": "",
  demolition: "",
  "site-canteen": "",
  "damp-proofer": "",
  "drainage-engineer": "",
  "chimney-sweep": "",
  "tree-surgeon": "",
  "pest-control": "",
  "asbestos-removal": "",
  "lead-worker": "",
  "sash-window-restorer": "",
  "post-construction-cleaner": "",
  "garden-designer": "",
  "mobile-mechanic": "",
  "pump-service": "",
  "door-fitter": "",
  "flooring-installer": "",
  "bathroom-fitter": "",
  "conservatory-installer": "",
  "solar-installer": "",
  "ev-charger-installer": "",
  "heat-pump-installer": "",
  "smart-home-installer": "",
  "garage-door-installer": "",
  "gutter-installer": "",
  "driveway-installer": "",
  "fencing-installer": "",
  "shutter-installer": "",
  "aerial-satellite-installer": "",
  "garden-room-installer": "",
  "awning-installer": "",
  "kitchen-manufacturer": "",
  "staircase-manufacturer": "",
  "door-manufacturer": "",
  "window-manufacturer": "",
  "flooring-manufacturer": "",
  "conservatory-manufacturer": "",
  "wardrobe-maker": "",
  "furniture-maker": "",
  "joinery-workshop": "",
  "worktop-manufacturer": "",
  "glass-manufacturer": "",
  "shed-manufacturer": "",
  "garden-room-manufacturer": "",
  "steel-fabricator": "",
  "timber-merchant": "",
  "plumbing-merchant": "",
  "electrical-wholesaler": "",
  "tile-shop": "",
  "flooring-shop": "",
  "door-showroom": "",
  "kitchen-showroom": "",
  "window-showroom": "",
  "bathroom-showroom": "",
  "paint-merchant": "",
  ironmongery: "",
  "ppe-supplier": "",
  "tool-shop": "",
  "landscape-supplies": "",
  "aggregate-supplier": "",
  "roofing-supplies": "",
  "insulation-supplies": "",
  "plant-hire": "",
  "skip-hire": "",
  "portaloo-hire": "",
  "scaffolding-hire": "",
  "generator-hire": "",
  "van-hire": "",
  "crane-hire": "",
  "waste-removal": "",
  "minidigger-hire": "",
  "storage-container-hire": ""
};

export function demoVideoFor(tradeSlug: string): string | null {
  const url = DEMO_TRADE_VIDEOS[tradeSlug];
  return url && url.length > 0 ? url : null;
}
