// src/lib/nex-native/auto-slug.ts
//
// Auto-generate a Gratis-tier business slug when the seller doesn't
// have Bisnis (which unlocks custom .nex names per the sealed
// 2026-09-27 package doctrine).
//
// Pattern: shop-<6 lowercase base-36 chars> · e.g. shop-a3f8kx.
// * Deliberately different from the nex_account handle namespace
//   (nex-XXXXX which is reserved for system accounts + human
//   handles) so a business slug never collides with an account handle.
// * Uniqueness is checked against nex_business.slug and retried up
//   to 5 times before falling back to a longer suffix.

import "server-only";
import { nexSupabaseAdmin } from "./supabase-admin";

const AUTO_SLUG_PREFIX = "shop-";
const AUTO_SLUG_CORE_LEN = 6;
const AUTO_SLUG_ALPHABET = "abcdefghijkmnpqrstuvwxyz23456789"; // no 1/i/l/o/0
const MAX_RETRIES = 5;

function randomCore(len: number): string {
  let out = "";
  for (let i = 0; i < len; i++) {
    const idx = Math.floor(Math.random() * AUTO_SLUG_ALPHABET.length);
    out += AUTO_SLUG_ALPHABET[idx];
  }
  return out;
}

/** Try up to MAX_RETRIES random slugs · widen the core by 2 chars on
 *  failure so we never loop forever in a saturated namespace. */
export async function generateAutoBusinessSlug(): Promise<string> {
  for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
    const core = randomCore(AUTO_SLUG_CORE_LEN + Math.floor(attempt / 2) * 2);
    const candidate = `${AUTO_SLUG_PREFIX}${core}`;
    const hit = await nexSupabaseAdmin
      .from("nex_business")
      .select("id")
      .eq("slug", candidate)
      .maybeSingle();
    if (!hit.data) return candidate;
  }
  // Extreme fallback · timestamp core.
  return `${AUTO_SLUG_PREFIX}${Date.now().toString(36)}`;
}

/** Detect a slug we generated ourselves (as opposed to a human-picked
 *  custom name). Useful for the seller-facing "upgrade to Bisnis to
 *  pick a custom name" prompt on /manage/shop. */
export function isAutoGeneratedBusinessSlug(slug: string): boolean {
  if (!slug.startsWith(AUTO_SLUG_PREFIX)) return false;
  const core = slug.slice(AUTO_SLUG_PREFIX.length);
  return (
    core.length >= AUTO_SLUG_CORE_LEN &&
    core.length <= AUTO_SLUG_CORE_LEN + 8 &&
    /^[a-z2-9]+$/.test(core)
  );
}
