// src/lib/nex/live/rights.ts
//
// NEX LIVE · Phase A · Rights Declaration & Evidence Discipline
// Philip 2026-09-06 · FOUNDER AUTHORIZATION · PHASE A
//
// PURPOSE (§7)
//   NEX must never assume "user uploaded it = NEX can commercially
//   exploit it". Every upload/publish carries a rights declaration.
//   Unknown rights MUST stay UNKNOWN, not silently become APPROVED.
//
// COMPOSITION
//   Extends the provenance model already used by asset-platform/
//   asset-library.ts (source + licence). Adds:
//     · uploader NEX ID
//     · explicit rights declaration
//     · monetization eligibility
//     · moderation status
//     · rights evidence state (§26 UNKNOWN ≠ APPROVED)
//
// SCOPE (Phase A)
//   Pure types + validator. Zero persistence. Zero UI. Zero policy
//   enforcement at the network layer (that is Phase D / Phase G).

// ── Source · matches asset-platform/asset-library.ts vocabulary ─────

export type RightsSource =
  | "authored"          // creator uploaded their own work
  | "ai_generated"      // AI generated by the uploader
  | "photographed"      // uploader captured
  | "rendered"          // uploader rendered
  | "imported"          // uploader imported from another source they own
  | "screenshot"        // uploader screenshot
  | "licensed"          // uploader holds an external licence
  | "unknown";          // no claim provided — MUST route to UNKNOWN state

// ── Licence · matches asset-library.ts vocabulary + additions ───────

export type RightsLicence =
  | "internal"
  | "royalty_free"
  | "creative_commons"
  | "commercial_licensed"
  | "custom_agreement"
  | "personal_use_only"       // e.g. artist's own material, no third-party monetisation
  | "unknown";

// ── Evidence state · mirrors the 6-state AttributeState discipline ──
// (Same mechanical guarantee that UNKNOWN ≠ NO applies here to rights.)

export type RightsState =
  | "KNOWN_OWNED"       // uploader-declared ownership + evidence tier permits
  | "KNOWN_LICENSED"    // valid external licence recorded
  | "UNVERIFIED"        // declaration made but no evidence tier
  | "UNKNOWN"           // no declaration — never rendered as "cleared"
  | "DISPUTED"          // claim challenge in progress
  | "EXPIRED"           // previously licensed, term ended
  | "CONFLICTING";      // two conflicting claims exist

export type ModerationStatus =
  | "PENDING"
  | "APPROVED"
  | "REJECTED"
  | "REMOVED";

// ── Monetization eligibility · derived, not asserted ────────────────
// NEX must not decide monetization eligibility from source/licence alone
// — Phase Creator-Economy will layer real evidence gates on top. This
// enum lets Phase A record the current status honestly.

export type MonetizationEligibility =
  | "NOT_ELIGIBLE"
  | "PENDING_REVIEW"
  | "ELIGIBLE_LIMITED"
  | "ELIGIBLE_FULL"
  | "UNKNOWN";

// ── Rights declaration record ───────────────────────────────────────

export type RightsDeclaration = {
  /** The NEX ID of the uploader making the declaration. Required. */
  uploader_nex_id: string;

  /** What the uploader claims about the origin of the content. */
  declared_source: RightsSource;

  /** What licence (if any) the uploader claims applies. */
  declared_licence: RightsLicence;

  /** Free-text extra notes the uploader provided (e.g. named party in a
   *  custom agreement). Never rendered as evidence — user-supplied text
   *  is UNVERIFIED by default. */
  declared_notes: string | null;

  /** The system's assessed rights state — the ONLY field downstream
   *  publish/monetization gates should read. Never trust declared_source
   *  alone. */
  state: RightsState;

  /** Monetization eligibility — derived by policy at review time. */
  monetization: MonetizationEligibility;

  /** Moderation status — independent of rights state. */
  moderation: ModerationStatus;

  /** ISO timestamp of the declaration. */
  declared_at_iso: string;

  /** ISO timestamp of the last policy assessment (may equal
   *  declared_at_iso for automated assessments). */
  assessed_at_iso: string;
};

// ── Publish gate ────────────────────────────────────────────────────
// The single question downstream code should ask: "can this content be
// published under current NEX rights policy?" — mirrors the immutable
// discipline that Interest slice's canInterestFireSend enforces.

export function canPublishUnderRights(decl: RightsDeclaration): boolean {
  if (decl.moderation === "REJECTED" || decl.moderation === "REMOVED") return false;
  if (decl.state === "KNOWN_OWNED" || decl.state === "KNOWN_LICENSED") return true;
  return false;   // UNVERIFIED · UNKNOWN · DISPUTED · EXPIRED · CONFLICTING all refuse publish
}

/** Throws with a descriptive reason. Used at publish seams to make the
 *  refusal explicit in server logs and test failures. */
export function assertRightsForPublish(decl: RightsDeclaration): void {
  if (canPublishUnderRights(decl)) return;
  throw new Error(
    `nex-live:rights_refused_publish:${decl.state}:moderation=${decl.moderation}`,
  );
}

/** Returns a fresh declaration in the safest possible state. Callers
 *  supply what they know; everything else stays honest UNKNOWN. */
export function newEmptyDeclaration(uploaderNexId: string, nowIso: string): RightsDeclaration {
  return {
    uploader_nex_id: uploaderNexId,
    declared_source: "unknown",
    declared_licence: "unknown",
    declared_notes: null,
    state: "UNKNOWN",
    monetization: "UNKNOWN",
    moderation: "PENDING",
    declared_at_iso: nowIso,
    assessed_at_iso: nowIso,
  };
}
