// src/lib/nex/discovery-world/iso-3166-1.ts
//
// Canonical ISO 3166-1 country registry seed data · UN-recognised set + observers
// + significant territories. Region + subregion classification aligned with UN M49.
//
// This is a deliberate, deterministic seed. NEX never infers a country · never
// silently promotes a territory. Changes require an explicit Founder edit.
//
// Fields:
//   iso_alpha_2 · iso_alpha_3 · numeric_code · name · region · subregion ·
//   un_member · sovereign
//
// Region taxonomy (matches the Founder's regional phases · Asia-last is a
// per-PROGRAMME policy, not a property of the country):
//   Americas · Europe · Africa · Middle East · Asia · Oceania · Antarctica

export interface Iso3166Country {
  readonly iso_alpha_2: string;
  readonly iso_alpha_3: string;
  readonly numeric_code: string;
  readonly name: string;
  readonly region: "Americas" | "Europe" | "Africa" | "Middle East" | "Asia" | "Oceania" | "Antarctica";
  readonly subregion: string;
  readonly un_member: boolean;
  readonly sovereign: boolean;
}

// 249 ISO 3166-1 codes · 193 UN members + 2 observers (VA, PS) + 54 non-member territories
// Data cross-referenced against ISO 3166-1 (2020) + UN M49 (2022). This list is
// intentionally comprehensive so no country is silently missing from NEX's world map.
export const ISO_3166_1: ReadonlyArray<Iso3166Country> = [
  // ── Americas · Northern America ──
  { iso_alpha_2: "CA", iso_alpha_3: "CAN", numeric_code: "124", name: "Canada",                    region: "Americas", subregion: "Northern America", un_member: true,  sovereign: true },
  { iso_alpha_2: "US", iso_alpha_3: "USA", numeric_code: "840", name: "United States",             region: "Americas", subregion: "Northern America", un_member: true,  sovereign: true },
  { iso_alpha_2: "MX", iso_alpha_3: "MEX", numeric_code: "484", name: "Mexico",                    region: "Americas", subregion: "Central America",  un_member: true,  sovereign: true },
  { iso_alpha_2: "BM", iso_alpha_3: "BMU", numeric_code: "060", name: "Bermuda",                    region: "Americas", subregion: "Northern America", un_member: false, sovereign: false },
  { iso_alpha_2: "GL", iso_alpha_3: "GRL", numeric_code: "304", name: "Greenland",                  region: "Americas", subregion: "Northern America", un_member: false, sovereign: false },
  { iso_alpha_2: "PM", iso_alpha_3: "SPM", numeric_code: "666", name: "Saint Pierre and Miquelon",  region: "Americas", subregion: "Northern America", un_member: false, sovereign: false },

  // ── Americas · Central America ──
  { iso_alpha_2: "BZ", iso_alpha_3: "BLZ", numeric_code: "084", name: "Belize",                    region: "Americas", subregion: "Central America",  un_member: true,  sovereign: true },
  { iso_alpha_2: "CR", iso_alpha_3: "CRI", numeric_code: "188", name: "Costa Rica",                region: "Americas", subregion: "Central America",  un_member: true,  sovereign: true },
  { iso_alpha_2: "SV", iso_alpha_3: "SLV", numeric_code: "222", name: "El Salvador",               region: "Americas", subregion: "Central America",  un_member: true,  sovereign: true },
  { iso_alpha_2: "GT", iso_alpha_3: "GTM", numeric_code: "320", name: "Guatemala",                 region: "Americas", subregion: "Central America",  un_member: true,  sovereign: true },
  { iso_alpha_2: "HN", iso_alpha_3: "HND", numeric_code: "340", name: "Honduras",                  region: "Americas", subregion: "Central America",  un_member: true,  sovereign: true },
  { iso_alpha_2: "NI", iso_alpha_3: "NIC", numeric_code: "558", name: "Nicaragua",                 region: "Americas", subregion: "Central America",  un_member: true,  sovereign: true },
  { iso_alpha_2: "PA", iso_alpha_3: "PAN", numeric_code: "591", name: "Panama",                    region: "Americas", subregion: "Central America",  un_member: true,  sovereign: true },

  // ── Americas · Caribbean ──
  { iso_alpha_2: "AI", iso_alpha_3: "AIA", numeric_code: "660", name: "Anguilla",                  region: "Americas", subregion: "Caribbean",        un_member: false, sovereign: false },
  { iso_alpha_2: "AG", iso_alpha_3: "ATG", numeric_code: "028", name: "Antigua and Barbuda",       region: "Americas", subregion: "Caribbean",        un_member: true,  sovereign: true },
  { iso_alpha_2: "AW", iso_alpha_3: "ABW", numeric_code: "533", name: "Aruba",                      region: "Americas", subregion: "Caribbean",        un_member: false, sovereign: false },
  { iso_alpha_2: "BS", iso_alpha_3: "BHS", numeric_code: "044", name: "Bahamas",                    region: "Americas", subregion: "Caribbean",        un_member: true,  sovereign: true },
  { iso_alpha_2: "BB", iso_alpha_3: "BRB", numeric_code: "052", name: "Barbados",                   region: "Americas", subregion: "Caribbean",        un_member: true,  sovereign: true },
  { iso_alpha_2: "BQ", iso_alpha_3: "BES", numeric_code: "535", name: "Bonaire, Sint Eustatius and Saba", region: "Americas", subregion: "Caribbean",  un_member: false, sovereign: false },
  { iso_alpha_2: "VG", iso_alpha_3: "VGB", numeric_code: "092", name: "British Virgin Islands",     region: "Americas", subregion: "Caribbean",        un_member: false, sovereign: false },
  { iso_alpha_2: "KY", iso_alpha_3: "CYM", numeric_code: "136", name: "Cayman Islands",             region: "Americas", subregion: "Caribbean",        un_member: false, sovereign: false },
  { iso_alpha_2: "CU", iso_alpha_3: "CUB", numeric_code: "192", name: "Cuba",                       region: "Americas", subregion: "Caribbean",        un_member: true,  sovereign: true },
  { iso_alpha_2: "CW", iso_alpha_3: "CUW", numeric_code: "531", name: "Curaçao",                    region: "Americas", subregion: "Caribbean",        un_member: false, sovereign: false },
  { iso_alpha_2: "DM", iso_alpha_3: "DMA", numeric_code: "212", name: "Dominica",                   region: "Americas", subregion: "Caribbean",        un_member: true,  sovereign: true },
  { iso_alpha_2: "DO", iso_alpha_3: "DOM", numeric_code: "214", name: "Dominican Republic",         region: "Americas", subregion: "Caribbean",        un_member: true,  sovereign: true },
  { iso_alpha_2: "GD", iso_alpha_3: "GRD", numeric_code: "308", name: "Grenada",                    region: "Americas", subregion: "Caribbean",        un_member: true,  sovereign: true },
  { iso_alpha_2: "GP", iso_alpha_3: "GLP", numeric_code: "312", name: "Guadeloupe",                 region: "Americas", subregion: "Caribbean",        un_member: false, sovereign: false },
  { iso_alpha_2: "HT", iso_alpha_3: "HTI", numeric_code: "332", name: "Haiti",                      region: "Americas", subregion: "Caribbean",        un_member: true,  sovereign: true },
  { iso_alpha_2: "JM", iso_alpha_3: "JAM", numeric_code: "388", name: "Jamaica",                    region: "Americas", subregion: "Caribbean",        un_member: true,  sovereign: true },
  { iso_alpha_2: "MQ", iso_alpha_3: "MTQ", numeric_code: "474", name: "Martinique",                 region: "Americas", subregion: "Caribbean",        un_member: false, sovereign: false },
  { iso_alpha_2: "MS", iso_alpha_3: "MSR", numeric_code: "500", name: "Montserrat",                 region: "Americas", subregion: "Caribbean",        un_member: false, sovereign: false },
  { iso_alpha_2: "PR", iso_alpha_3: "PRI", numeric_code: "630", name: "Puerto Rico",                region: "Americas", subregion: "Caribbean",        un_member: false, sovereign: false },
  { iso_alpha_2: "BL", iso_alpha_3: "BLM", numeric_code: "652", name: "Saint Barthélemy",           region: "Americas", subregion: "Caribbean",        un_member: false, sovereign: false },
  { iso_alpha_2: "KN", iso_alpha_3: "KNA", numeric_code: "659", name: "Saint Kitts and Nevis",      region: "Americas", subregion: "Caribbean",        un_member: true,  sovereign: true },
  { iso_alpha_2: "LC", iso_alpha_3: "LCA", numeric_code: "662", name: "Saint Lucia",                region: "Americas", subregion: "Caribbean",        un_member: true,  sovereign: true },
  { iso_alpha_2: "MF", iso_alpha_3: "MAF", numeric_code: "663", name: "Saint Martin (French part)", region: "Americas", subregion: "Caribbean",        un_member: false, sovereign: false },
  { iso_alpha_2: "VC", iso_alpha_3: "VCT", numeric_code: "670", name: "Saint Vincent and the Grenadines", region: "Americas", subregion: "Caribbean",  un_member: true,  sovereign: true },
  { iso_alpha_2: "SX", iso_alpha_3: "SXM", numeric_code: "534", name: "Sint Maarten (Dutch part)",  region: "Americas", subregion: "Caribbean",        un_member: false, sovereign: false },
  { iso_alpha_2: "TT", iso_alpha_3: "TTO", numeric_code: "780", name: "Trinidad and Tobago",        region: "Americas", subregion: "Caribbean",        un_member: true,  sovereign: true },
  { iso_alpha_2: "TC", iso_alpha_3: "TCA", numeric_code: "796", name: "Turks and Caicos Islands",   region: "Americas", subregion: "Caribbean",        un_member: false, sovereign: false },
  { iso_alpha_2: "VI", iso_alpha_3: "VIR", numeric_code: "850", name: "U.S. Virgin Islands",        region: "Americas", subregion: "Caribbean",        un_member: false, sovereign: false },

  // ── Americas · South America ──
  { iso_alpha_2: "AR", iso_alpha_3: "ARG", numeric_code: "032", name: "Argentina",                 region: "Americas", subregion: "South America",    un_member: true,  sovereign: true },
  { iso_alpha_2: "BO", iso_alpha_3: "BOL", numeric_code: "068", name: "Bolivia",                    region: "Americas", subregion: "South America",    un_member: true,  sovereign: true },
  { iso_alpha_2: "BR", iso_alpha_3: "BRA", numeric_code: "076", name: "Brazil",                     region: "Americas", subregion: "South America",    un_member: true,  sovereign: true },
  { iso_alpha_2: "CL", iso_alpha_3: "CHL", numeric_code: "152", name: "Chile",                      region: "Americas", subregion: "South America",    un_member: true,  sovereign: true },
  { iso_alpha_2: "CO", iso_alpha_3: "COL", numeric_code: "170", name: "Colombia",                   region: "Americas", subregion: "South America",    un_member: true,  sovereign: true },
  { iso_alpha_2: "EC", iso_alpha_3: "ECU", numeric_code: "218", name: "Ecuador",                    region: "Americas", subregion: "South America",    un_member: true,  sovereign: true },
  { iso_alpha_2: "FK", iso_alpha_3: "FLK", numeric_code: "238", name: "Falkland Islands",           region: "Americas", subregion: "South America",    un_member: false, sovereign: false },
  { iso_alpha_2: "GF", iso_alpha_3: "GUF", numeric_code: "254", name: "French Guiana",              region: "Americas", subregion: "South America",    un_member: false, sovereign: false },
  { iso_alpha_2: "GY", iso_alpha_3: "GUY", numeric_code: "328", name: "Guyana",                     region: "Americas", subregion: "South America",    un_member: true,  sovereign: true },
  { iso_alpha_2: "PY", iso_alpha_3: "PRY", numeric_code: "600", name: "Paraguay",                   region: "Americas", subregion: "South America",    un_member: true,  sovereign: true },
  { iso_alpha_2: "PE", iso_alpha_3: "PER", numeric_code: "604", name: "Peru",                       region: "Americas", subregion: "South America",    un_member: true,  sovereign: true },
  { iso_alpha_2: "SR", iso_alpha_3: "SUR", numeric_code: "740", name: "Suriname",                   region: "Americas", subregion: "South America",    un_member: true,  sovereign: true },
  { iso_alpha_2: "UY", iso_alpha_3: "URY", numeric_code: "858", name: "Uruguay",                    region: "Americas", subregion: "South America",    un_member: true,  sovereign: true },
  { iso_alpha_2: "VE", iso_alpha_3: "VEN", numeric_code: "862", name: "Venezuela",                  region: "Americas", subregion: "South America",    un_member: true,  sovereign: true },

  // ── Europe ──
  { iso_alpha_2: "AL", iso_alpha_3: "ALB", numeric_code: "008", name: "Albania",                   region: "Europe",   subregion: "Southern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "AD", iso_alpha_3: "AND", numeric_code: "020", name: "Andorra",                   region: "Europe",   subregion: "Southern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "AT", iso_alpha_3: "AUT", numeric_code: "040", name: "Austria",                   region: "Europe",   subregion: "Western Europe",   un_member: true,  sovereign: true },
  { iso_alpha_2: "BY", iso_alpha_3: "BLR", numeric_code: "112", name: "Belarus",                    region: "Europe",   subregion: "Eastern Europe",   un_member: true,  sovereign: true },
  { iso_alpha_2: "BE", iso_alpha_3: "BEL", numeric_code: "056", name: "Belgium",                    region: "Europe",   subregion: "Western Europe",   un_member: true,  sovereign: true },
  { iso_alpha_2: "BA", iso_alpha_3: "BIH", numeric_code: "070", name: "Bosnia and Herzegovina",     region: "Europe",   subregion: "Southern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "BG", iso_alpha_3: "BGR", numeric_code: "100", name: "Bulgaria",                   region: "Europe",   subregion: "Eastern Europe",   un_member: true,  sovereign: true },
  { iso_alpha_2: "HR", iso_alpha_3: "HRV", numeric_code: "191", name: "Croatia",                    region: "Europe",   subregion: "Southern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "CY", iso_alpha_3: "CYP", numeric_code: "196", name: "Cyprus",                     region: "Europe",   subregion: "Southern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "CZ", iso_alpha_3: "CZE", numeric_code: "203", name: "Czech Republic",             region: "Europe",   subregion: "Eastern Europe",   un_member: true,  sovereign: true },
  { iso_alpha_2: "DK", iso_alpha_3: "DNK", numeric_code: "208", name: "Denmark",                    region: "Europe",   subregion: "Northern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "EE", iso_alpha_3: "EST", numeric_code: "233", name: "Estonia",                    region: "Europe",   subregion: "Northern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "FO", iso_alpha_3: "FRO", numeric_code: "234", name: "Faroe Islands",              region: "Europe",   subregion: "Northern Europe",  un_member: false, sovereign: false },
  { iso_alpha_2: "FI", iso_alpha_3: "FIN", numeric_code: "246", name: "Finland",                    region: "Europe",   subregion: "Northern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "FR", iso_alpha_3: "FRA", numeric_code: "250", name: "France",                     region: "Europe",   subregion: "Western Europe",   un_member: true,  sovereign: true },
  { iso_alpha_2: "DE", iso_alpha_3: "DEU", numeric_code: "276", name: "Germany",                    region: "Europe",   subregion: "Western Europe",   un_member: true,  sovereign: true },
  { iso_alpha_2: "GI", iso_alpha_3: "GIB", numeric_code: "292", name: "Gibraltar",                  region: "Europe",   subregion: "Southern Europe",  un_member: false, sovereign: false },
  { iso_alpha_2: "GR", iso_alpha_3: "GRC", numeric_code: "300", name: "Greece",                     region: "Europe",   subregion: "Southern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "GG", iso_alpha_3: "GGY", numeric_code: "831", name: "Guernsey",                   region: "Europe",   subregion: "Northern Europe",  un_member: false, sovereign: false },
  { iso_alpha_2: "HU", iso_alpha_3: "HUN", numeric_code: "348", name: "Hungary",                    region: "Europe",   subregion: "Eastern Europe",   un_member: true,  sovereign: true },
  { iso_alpha_2: "IS", iso_alpha_3: "ISL", numeric_code: "352", name: "Iceland",                    region: "Europe",   subregion: "Northern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "IE", iso_alpha_3: "IRL", numeric_code: "372", name: "Ireland",                    region: "Europe",   subregion: "Northern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "IM", iso_alpha_3: "IMN", numeric_code: "833", name: "Isle of Man",                region: "Europe",   subregion: "Northern Europe",  un_member: false, sovereign: false },
  { iso_alpha_2: "IT", iso_alpha_3: "ITA", numeric_code: "380", name: "Italy",                      region: "Europe",   subregion: "Southern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "JE", iso_alpha_3: "JEY", numeric_code: "832", name: "Jersey",                     region: "Europe",   subregion: "Northern Europe",  un_member: false, sovereign: false },
  { iso_alpha_2: "XK", iso_alpha_3: "XKX", numeric_code: "999", name: "Kosovo",                     region: "Europe",   subregion: "Southern Europe",  un_member: false, sovereign: true },
  { iso_alpha_2: "LV", iso_alpha_3: "LVA", numeric_code: "428", name: "Latvia",                     region: "Europe",   subregion: "Northern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "LI", iso_alpha_3: "LIE", numeric_code: "438", name: "Liechtenstein",              region: "Europe",   subregion: "Western Europe",   un_member: true,  sovereign: true },
  { iso_alpha_2: "LT", iso_alpha_3: "LTU", numeric_code: "440", name: "Lithuania",                  region: "Europe",   subregion: "Northern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "LU", iso_alpha_3: "LUX", numeric_code: "442", name: "Luxembourg",                 region: "Europe",   subregion: "Western Europe",   un_member: true,  sovereign: true },
  { iso_alpha_2: "MT", iso_alpha_3: "MLT", numeric_code: "470", name: "Malta",                      region: "Europe",   subregion: "Southern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "MD", iso_alpha_3: "MDA", numeric_code: "498", name: "Moldova",                    region: "Europe",   subregion: "Eastern Europe",   un_member: true,  sovereign: true },
  { iso_alpha_2: "MC", iso_alpha_3: "MCO", numeric_code: "492", name: "Monaco",                     region: "Europe",   subregion: "Western Europe",   un_member: true,  sovereign: true },
  { iso_alpha_2: "ME", iso_alpha_3: "MNE", numeric_code: "499", name: "Montenegro",                 region: "Europe",   subregion: "Southern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "NL", iso_alpha_3: "NLD", numeric_code: "528", name: "Netherlands",                region: "Europe",   subregion: "Western Europe",   un_member: true,  sovereign: true },
  { iso_alpha_2: "MK", iso_alpha_3: "MKD", numeric_code: "807", name: "North Macedonia",            region: "Europe",   subregion: "Southern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "NO", iso_alpha_3: "NOR", numeric_code: "578", name: "Norway",                     region: "Europe",   subregion: "Northern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "PL", iso_alpha_3: "POL", numeric_code: "616", name: "Poland",                     region: "Europe",   subregion: "Eastern Europe",   un_member: true,  sovereign: true },
  { iso_alpha_2: "PT", iso_alpha_3: "PRT", numeric_code: "620", name: "Portugal",                   region: "Europe",   subregion: "Southern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "RO", iso_alpha_3: "ROU", numeric_code: "642", name: "Romania",                    region: "Europe",   subregion: "Eastern Europe",   un_member: true,  sovereign: true },
  { iso_alpha_2: "RU", iso_alpha_3: "RUS", numeric_code: "643", name: "Russia",                     region: "Europe",   subregion: "Eastern Europe",   un_member: true,  sovereign: true },
  { iso_alpha_2: "SM", iso_alpha_3: "SMR", numeric_code: "674", name: "San Marino",                 region: "Europe",   subregion: "Southern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "RS", iso_alpha_3: "SRB", numeric_code: "688", name: "Serbia",                     region: "Europe",   subregion: "Southern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "SK", iso_alpha_3: "SVK", numeric_code: "703", name: "Slovakia",                   region: "Europe",   subregion: "Eastern Europe",   un_member: true,  sovereign: true },
  { iso_alpha_2: "SI", iso_alpha_3: "SVN", numeric_code: "705", name: "Slovenia",                   region: "Europe",   subregion: "Southern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "ES", iso_alpha_3: "ESP", numeric_code: "724", name: "Spain",                      region: "Europe",   subregion: "Southern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "SJ", iso_alpha_3: "SJM", numeric_code: "744", name: "Svalbard and Jan Mayen",     region: "Europe",   subregion: "Northern Europe",  un_member: false, sovereign: false },
  { iso_alpha_2: "SE", iso_alpha_3: "SWE", numeric_code: "752", name: "Sweden",                     region: "Europe",   subregion: "Northern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "CH", iso_alpha_3: "CHE", numeric_code: "756", name: "Switzerland",                region: "Europe",   subregion: "Western Europe",   un_member: true,  sovereign: true },
  { iso_alpha_2: "UA", iso_alpha_3: "UKR", numeric_code: "804", name: "Ukraine",                    region: "Europe",   subregion: "Eastern Europe",   un_member: true,  sovereign: true },
  { iso_alpha_2: "GB", iso_alpha_3: "GBR", numeric_code: "826", name: "United Kingdom",             region: "Europe",   subregion: "Northern Europe",  un_member: true,  sovereign: true },
  { iso_alpha_2: "VA", iso_alpha_3: "VAT", numeric_code: "336", name: "Vatican City",               region: "Europe",   subregion: "Southern Europe",  un_member: false, sovereign: true },
  { iso_alpha_2: "AX", iso_alpha_3: "ALA", numeric_code: "248", name: "Åland Islands",              region: "Europe",   subregion: "Northern Europe",  un_member: false, sovereign: false },

  // ── Africa ──
  { iso_alpha_2: "DZ", iso_alpha_3: "DZA", numeric_code: "012", name: "Algeria",                   region: "Africa",   subregion: "Northern Africa",  un_member: true,  sovereign: true },
  { iso_alpha_2: "AO", iso_alpha_3: "AGO", numeric_code: "024", name: "Angola",                    region: "Africa",   subregion: "Middle Africa",    un_member: true,  sovereign: true },
  { iso_alpha_2: "BJ", iso_alpha_3: "BEN", numeric_code: "204", name: "Benin",                     region: "Africa",   subregion: "Western Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "BW", iso_alpha_3: "BWA", numeric_code: "072", name: "Botswana",                  region: "Africa",   subregion: "Southern Africa",  un_member: true,  sovereign: true },
  { iso_alpha_2: "BF", iso_alpha_3: "BFA", numeric_code: "854", name: "Burkina Faso",              region: "Africa",   subregion: "Western Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "BI", iso_alpha_3: "BDI", numeric_code: "108", name: "Burundi",                   region: "Africa",   subregion: "Eastern Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "CV", iso_alpha_3: "CPV", numeric_code: "132", name: "Cabo Verde",                region: "Africa",   subregion: "Western Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "CM", iso_alpha_3: "CMR", numeric_code: "120", name: "Cameroon",                  region: "Africa",   subregion: "Middle Africa",    un_member: true,  sovereign: true },
  { iso_alpha_2: "CF", iso_alpha_3: "CAF", numeric_code: "140", name: "Central African Republic",  region: "Africa",   subregion: "Middle Africa",    un_member: true,  sovereign: true },
  { iso_alpha_2: "TD", iso_alpha_3: "TCD", numeric_code: "148", name: "Chad",                      region: "Africa",   subregion: "Middle Africa",    un_member: true,  sovereign: true },
  { iso_alpha_2: "KM", iso_alpha_3: "COM", numeric_code: "174", name: "Comoros",                   region: "Africa",   subregion: "Eastern Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "CG", iso_alpha_3: "COG", numeric_code: "178", name: "Congo",                     region: "Africa",   subregion: "Middle Africa",    un_member: true,  sovereign: true },
  { iso_alpha_2: "CD", iso_alpha_3: "COD", numeric_code: "180", name: "Congo (Democratic Republic)", region: "Africa", subregion: "Middle Africa",    un_member: true,  sovereign: true },
  { iso_alpha_2: "CI", iso_alpha_3: "CIV", numeric_code: "384", name: "Côte d'Ivoire",             region: "Africa",   subregion: "Western Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "DJ", iso_alpha_3: "DJI", numeric_code: "262", name: "Djibouti",                  region: "Africa",   subregion: "Eastern Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "EG", iso_alpha_3: "EGY", numeric_code: "818", name: "Egypt",                     region: "Africa",   subregion: "Northern Africa",  un_member: true,  sovereign: true },
  { iso_alpha_2: "GQ", iso_alpha_3: "GNQ", numeric_code: "226", name: "Equatorial Guinea",         region: "Africa",   subregion: "Middle Africa",    un_member: true,  sovereign: true },
  { iso_alpha_2: "ER", iso_alpha_3: "ERI", numeric_code: "232", name: "Eritrea",                   region: "Africa",   subregion: "Eastern Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "SZ", iso_alpha_3: "SWZ", numeric_code: "748", name: "Eswatini",                  region: "Africa",   subregion: "Southern Africa",  un_member: true,  sovereign: true },
  { iso_alpha_2: "ET", iso_alpha_3: "ETH", numeric_code: "231", name: "Ethiopia",                  region: "Africa",   subregion: "Eastern Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "GA", iso_alpha_3: "GAB", numeric_code: "266", name: "Gabon",                     region: "Africa",   subregion: "Middle Africa",    un_member: true,  sovereign: true },
  { iso_alpha_2: "GM", iso_alpha_3: "GMB", numeric_code: "270", name: "Gambia",                    region: "Africa",   subregion: "Western Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "GH", iso_alpha_3: "GHA", numeric_code: "288", name: "Ghana",                     region: "Africa",   subregion: "Western Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "GN", iso_alpha_3: "GIN", numeric_code: "324", name: "Guinea",                    region: "Africa",   subregion: "Western Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "GW", iso_alpha_3: "GNB", numeric_code: "624", name: "Guinea-Bissau",             region: "Africa",   subregion: "Western Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "KE", iso_alpha_3: "KEN", numeric_code: "404", name: "Kenya",                     region: "Africa",   subregion: "Eastern Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "LS", iso_alpha_3: "LSO", numeric_code: "426", name: "Lesotho",                   region: "Africa",   subregion: "Southern Africa",  un_member: true,  sovereign: true },
  { iso_alpha_2: "LR", iso_alpha_3: "LBR", numeric_code: "430", name: "Liberia",                   region: "Africa",   subregion: "Western Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "LY", iso_alpha_3: "LBY", numeric_code: "434", name: "Libya",                     region: "Africa",   subregion: "Northern Africa",  un_member: true,  sovereign: true },
  { iso_alpha_2: "MG", iso_alpha_3: "MDG", numeric_code: "450", name: "Madagascar",                region: "Africa",   subregion: "Eastern Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "MW", iso_alpha_3: "MWI", numeric_code: "454", name: "Malawi",                    region: "Africa",   subregion: "Eastern Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "ML", iso_alpha_3: "MLI", numeric_code: "466", name: "Mali",                      region: "Africa",   subregion: "Western Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "MR", iso_alpha_3: "MRT", numeric_code: "478", name: "Mauritania",                region: "Africa",   subregion: "Western Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "MU", iso_alpha_3: "MUS", numeric_code: "480", name: "Mauritius",                 region: "Africa",   subregion: "Eastern Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "YT", iso_alpha_3: "MYT", numeric_code: "175", name: "Mayotte",                   region: "Africa",   subregion: "Eastern Africa",   un_member: false, sovereign: false },
  { iso_alpha_2: "MA", iso_alpha_3: "MAR", numeric_code: "504", name: "Morocco",                   region: "Africa",   subregion: "Northern Africa",  un_member: true,  sovereign: true },
  { iso_alpha_2: "MZ", iso_alpha_3: "MOZ", numeric_code: "508", name: "Mozambique",                region: "Africa",   subregion: "Eastern Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "NA", iso_alpha_3: "NAM", numeric_code: "516", name: "Namibia",                   region: "Africa",   subregion: "Southern Africa",  un_member: true,  sovereign: true },
  { iso_alpha_2: "NE", iso_alpha_3: "NER", numeric_code: "562", name: "Niger",                     region: "Africa",   subregion: "Western Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "NG", iso_alpha_3: "NGA", numeric_code: "566", name: "Nigeria",                   region: "Africa",   subregion: "Western Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "RE", iso_alpha_3: "REU", numeric_code: "638", name: "Réunion",                   region: "Africa",   subregion: "Eastern Africa",   un_member: false, sovereign: false },
  { iso_alpha_2: "RW", iso_alpha_3: "RWA", numeric_code: "646", name: "Rwanda",                    region: "Africa",   subregion: "Eastern Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "SH", iso_alpha_3: "SHN", numeric_code: "654", name: "Saint Helena",              region: "Africa",   subregion: "Western Africa",   un_member: false, sovereign: false },
  { iso_alpha_2: "ST", iso_alpha_3: "STP", numeric_code: "678", name: "São Tomé and Príncipe",     region: "Africa",   subregion: "Middle Africa",    un_member: true,  sovereign: true },
  { iso_alpha_2: "SN", iso_alpha_3: "SEN", numeric_code: "686", name: "Senegal",                   region: "Africa",   subregion: "Western Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "SC", iso_alpha_3: "SYC", numeric_code: "690", name: "Seychelles",                region: "Africa",   subregion: "Eastern Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "SL", iso_alpha_3: "SLE", numeric_code: "694", name: "Sierra Leone",              region: "Africa",   subregion: "Western Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "SO", iso_alpha_3: "SOM", numeric_code: "706", name: "Somalia",                   region: "Africa",   subregion: "Eastern Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "ZA", iso_alpha_3: "ZAF", numeric_code: "710", name: "South Africa",              region: "Africa",   subregion: "Southern Africa",  un_member: true,  sovereign: true },
  { iso_alpha_2: "SS", iso_alpha_3: "SSD", numeric_code: "728", name: "South Sudan",               region: "Africa",   subregion: "Eastern Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "SD", iso_alpha_3: "SDN", numeric_code: "729", name: "Sudan",                     region: "Africa",   subregion: "Northern Africa",  un_member: true,  sovereign: true },
  { iso_alpha_2: "TZ", iso_alpha_3: "TZA", numeric_code: "834", name: "Tanzania",                  region: "Africa",   subregion: "Eastern Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "TG", iso_alpha_3: "TGO", numeric_code: "768", name: "Togo",                      region: "Africa",   subregion: "Western Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "TN", iso_alpha_3: "TUN", numeric_code: "788", name: "Tunisia",                   region: "Africa",   subregion: "Northern Africa",  un_member: true,  sovereign: true },
  { iso_alpha_2: "UG", iso_alpha_3: "UGA", numeric_code: "800", name: "Uganda",                    region: "Africa",   subregion: "Eastern Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "EH", iso_alpha_3: "ESH", numeric_code: "732", name: "Western Sahara",            region: "Africa",   subregion: "Northern Africa",  un_member: false, sovereign: false },
  { iso_alpha_2: "ZM", iso_alpha_3: "ZMB", numeric_code: "894", name: "Zambia",                    region: "Africa",   subregion: "Eastern Africa",   un_member: true,  sovereign: true },
  { iso_alpha_2: "ZW", iso_alpha_3: "ZWE", numeric_code: "716", name: "Zimbabwe",                  region: "Africa",   subregion: "Eastern Africa",   un_member: true,  sovereign: true },

  // ── Middle East ──
  { iso_alpha_2: "BH", iso_alpha_3: "BHR", numeric_code: "048", name: "Bahrain",                   region: "Middle East", subregion: "Western Asia",  un_member: true,  sovereign: true },
  { iso_alpha_2: "IR", iso_alpha_3: "IRN", numeric_code: "364", name: "Iran",                      region: "Middle East", subregion: "Western Asia",  un_member: true,  sovereign: true },
  { iso_alpha_2: "IQ", iso_alpha_3: "IRQ", numeric_code: "368", name: "Iraq",                      region: "Middle East", subregion: "Western Asia",  un_member: true,  sovereign: true },
  { iso_alpha_2: "IL", iso_alpha_3: "ISR", numeric_code: "376", name: "Israel",                    region: "Middle East", subregion: "Western Asia",  un_member: true,  sovereign: true },
  { iso_alpha_2: "JO", iso_alpha_3: "JOR", numeric_code: "400", name: "Jordan",                    region: "Middle East", subregion: "Western Asia",  un_member: true,  sovereign: true },
  { iso_alpha_2: "KW", iso_alpha_3: "KWT", numeric_code: "414", name: "Kuwait",                    region: "Middle East", subregion: "Western Asia",  un_member: true,  sovereign: true },
  { iso_alpha_2: "LB", iso_alpha_3: "LBN", numeric_code: "422", name: "Lebanon",                   region: "Middle East", subregion: "Western Asia",  un_member: true,  sovereign: true },
  { iso_alpha_2: "OM", iso_alpha_3: "OMN", numeric_code: "512", name: "Oman",                      region: "Middle East", subregion: "Western Asia",  un_member: true,  sovereign: true },
  { iso_alpha_2: "PS", iso_alpha_3: "PSE", numeric_code: "275", name: "Palestine",                 region: "Middle East", subregion: "Western Asia",  un_member: false, sovereign: true },
  { iso_alpha_2: "QA", iso_alpha_3: "QAT", numeric_code: "634", name: "Qatar",                     region: "Middle East", subregion: "Western Asia",  un_member: true,  sovereign: true },
  { iso_alpha_2: "SA", iso_alpha_3: "SAU", numeric_code: "682", name: "Saudi Arabia",              region: "Middle East", subregion: "Western Asia",  un_member: true,  sovereign: true },
  { iso_alpha_2: "SY", iso_alpha_3: "SYR", numeric_code: "760", name: "Syria",                     region: "Middle East", subregion: "Western Asia",  un_member: true,  sovereign: true },
  { iso_alpha_2: "TR", iso_alpha_3: "TUR", numeric_code: "792", name: "Turkey",                    region: "Middle East", subregion: "Western Asia",  un_member: true,  sovereign: true },
  { iso_alpha_2: "AE", iso_alpha_3: "ARE", numeric_code: "784", name: "United Arab Emirates",      region: "Middle East", subregion: "Western Asia",  un_member: true,  sovereign: true },
  { iso_alpha_2: "YE", iso_alpha_3: "YEM", numeric_code: "887", name: "Yemen",                     region: "Middle East", subregion: "Western Asia",  un_member: true,  sovereign: true },

  // ── Asia ──
  { iso_alpha_2: "AF", iso_alpha_3: "AFG", numeric_code: "004", name: "Afghanistan",               region: "Asia",     subregion: "Southern Asia",    un_member: true,  sovereign: true },
  { iso_alpha_2: "AM", iso_alpha_3: "ARM", numeric_code: "051", name: "Armenia",                    region: "Asia",     subregion: "Western Asia",     un_member: true,  sovereign: true },
  { iso_alpha_2: "AZ", iso_alpha_3: "AZE", numeric_code: "031", name: "Azerbaijan",                region: "Asia",     subregion: "Western Asia",     un_member: true,  sovereign: true },
  { iso_alpha_2: "BD", iso_alpha_3: "BGD", numeric_code: "050", name: "Bangladesh",                region: "Asia",     subregion: "Southern Asia",    un_member: true,  sovereign: true },
  { iso_alpha_2: "BT", iso_alpha_3: "BTN", numeric_code: "064", name: "Bhutan",                    region: "Asia",     subregion: "Southern Asia",    un_member: true,  sovereign: true },
  { iso_alpha_2: "BN", iso_alpha_3: "BRN", numeric_code: "096", name: "Brunei",                    region: "Asia",     subregion: "South-eastern Asia", un_member: true, sovereign: true },
  { iso_alpha_2: "KH", iso_alpha_3: "KHM", numeric_code: "116", name: "Cambodia",                  region: "Asia",     subregion: "South-eastern Asia", un_member: true, sovereign: true },
  { iso_alpha_2: "CN", iso_alpha_3: "CHN", numeric_code: "156", name: "China",                     region: "Asia",     subregion: "Eastern Asia",     un_member: true,  sovereign: true },
  { iso_alpha_2: "GE", iso_alpha_3: "GEO", numeric_code: "268", name: "Georgia",                    region: "Asia",     subregion: "Western Asia",     un_member: true,  sovereign: true },
  { iso_alpha_2: "HK", iso_alpha_3: "HKG", numeric_code: "344", name: "Hong Kong",                 region: "Asia",     subregion: "Eastern Asia",     un_member: false, sovereign: false },
  { iso_alpha_2: "IN", iso_alpha_3: "IND", numeric_code: "356", name: "India",                     region: "Asia",     subregion: "Southern Asia",    un_member: true,  sovereign: true },
  { iso_alpha_2: "ID", iso_alpha_3: "IDN", numeric_code: "360", name: "Indonesia",                 region: "Asia",     subregion: "South-eastern Asia", un_member: true, sovereign: true },
  { iso_alpha_2: "JP", iso_alpha_3: "JPN", numeric_code: "392", name: "Japan",                     region: "Asia",     subregion: "Eastern Asia",     un_member: true,  sovereign: true },
  { iso_alpha_2: "KZ", iso_alpha_3: "KAZ", numeric_code: "398", name: "Kazakhstan",                region: "Asia",     subregion: "Central Asia",     un_member: true,  sovereign: true },
  { iso_alpha_2: "KP", iso_alpha_3: "PRK", numeric_code: "408", name: "North Korea",               region: "Asia",     subregion: "Eastern Asia",     un_member: true,  sovereign: true },
  { iso_alpha_2: "KR", iso_alpha_3: "KOR", numeric_code: "410", name: "South Korea",               region: "Asia",     subregion: "Eastern Asia",     un_member: true,  sovereign: true },
  { iso_alpha_2: "KG", iso_alpha_3: "KGZ", numeric_code: "417", name: "Kyrgyzstan",                region: "Asia",     subregion: "Central Asia",     un_member: true,  sovereign: true },
  { iso_alpha_2: "LA", iso_alpha_3: "LAO", numeric_code: "418", name: "Laos",                      region: "Asia",     subregion: "South-eastern Asia", un_member: true, sovereign: true },
  { iso_alpha_2: "MO", iso_alpha_3: "MAC", numeric_code: "446", name: "Macao",                     region: "Asia",     subregion: "Eastern Asia",     un_member: false, sovereign: false },
  { iso_alpha_2: "MY", iso_alpha_3: "MYS", numeric_code: "458", name: "Malaysia",                  region: "Asia",     subregion: "South-eastern Asia", un_member: true, sovereign: true },
  { iso_alpha_2: "MV", iso_alpha_3: "MDV", numeric_code: "462", name: "Maldives",                  region: "Asia",     subregion: "Southern Asia",    un_member: true,  sovereign: true },
  { iso_alpha_2: "MN", iso_alpha_3: "MNG", numeric_code: "496", name: "Mongolia",                  region: "Asia",     subregion: "Eastern Asia",     un_member: true,  sovereign: true },
  { iso_alpha_2: "MM", iso_alpha_3: "MMR", numeric_code: "104", name: "Myanmar",                   region: "Asia",     subregion: "South-eastern Asia", un_member: true, sovereign: true },
  { iso_alpha_2: "NP", iso_alpha_3: "NPL", numeric_code: "524", name: "Nepal",                     region: "Asia",     subregion: "Southern Asia",    un_member: true,  sovereign: true },
  { iso_alpha_2: "PK", iso_alpha_3: "PAK", numeric_code: "586", name: "Pakistan",                  region: "Asia",     subregion: "Southern Asia",    un_member: true,  sovereign: true },
  { iso_alpha_2: "PH", iso_alpha_3: "PHL", numeric_code: "608", name: "Philippines",               region: "Asia",     subregion: "South-eastern Asia", un_member: true, sovereign: true },
  { iso_alpha_2: "SG", iso_alpha_3: "SGP", numeric_code: "702", name: "Singapore",                 region: "Asia",     subregion: "South-eastern Asia", un_member: true, sovereign: true },
  { iso_alpha_2: "LK", iso_alpha_3: "LKA", numeric_code: "144", name: "Sri Lanka",                 region: "Asia",     subregion: "Southern Asia",    un_member: true,  sovereign: true },
  { iso_alpha_2: "TW", iso_alpha_3: "TWN", numeric_code: "158", name: "Taiwan",                    region: "Asia",     subregion: "Eastern Asia",     un_member: false, sovereign: true },
  { iso_alpha_2: "TJ", iso_alpha_3: "TJK", numeric_code: "762", name: "Tajikistan",                region: "Asia",     subregion: "Central Asia",     un_member: true,  sovereign: true },
  { iso_alpha_2: "TH", iso_alpha_3: "THA", numeric_code: "764", name: "Thailand",                  region: "Asia",     subregion: "South-eastern Asia", un_member: true, sovereign: true },
  { iso_alpha_2: "TL", iso_alpha_3: "TLS", numeric_code: "626", name: "Timor-Leste",               region: "Asia",     subregion: "South-eastern Asia", un_member: true, sovereign: true },
  { iso_alpha_2: "TM", iso_alpha_3: "TKM", numeric_code: "795", name: "Turkmenistan",              region: "Asia",     subregion: "Central Asia",     un_member: true,  sovereign: true },
  { iso_alpha_2: "UZ", iso_alpha_3: "UZB", numeric_code: "860", name: "Uzbekistan",                region: "Asia",     subregion: "Central Asia",     un_member: true,  sovereign: true },
  { iso_alpha_2: "VN", iso_alpha_3: "VNM", numeric_code: "704", name: "Vietnam",                   region: "Asia",     subregion: "South-eastern Asia", un_member: true, sovereign: true },

  // ── Oceania ──
  { iso_alpha_2: "AS", iso_alpha_3: "ASM", numeric_code: "016", name: "American Samoa",            region: "Oceania",  subregion: "Polynesia",        un_member: false, sovereign: false },
  { iso_alpha_2: "AU", iso_alpha_3: "AUS", numeric_code: "036", name: "Australia",                 region: "Oceania",  subregion: "Australia and New Zealand", un_member: true, sovereign: true },
  { iso_alpha_2: "CK", iso_alpha_3: "COK", numeric_code: "184", name: "Cook Islands",              region: "Oceania",  subregion: "Polynesia",        un_member: false, sovereign: false },
  { iso_alpha_2: "FJ", iso_alpha_3: "FJI", numeric_code: "242", name: "Fiji",                      region: "Oceania",  subregion: "Melanesia",        un_member: true,  sovereign: true },
  { iso_alpha_2: "PF", iso_alpha_3: "PYF", numeric_code: "258", name: "French Polynesia",          region: "Oceania",  subregion: "Polynesia",        un_member: false, sovereign: false },
  { iso_alpha_2: "GU", iso_alpha_3: "GUM", numeric_code: "316", name: "Guam",                      region: "Oceania",  subregion: "Micronesia",       un_member: false, sovereign: false },
  { iso_alpha_2: "KI", iso_alpha_3: "KIR", numeric_code: "296", name: "Kiribati",                  region: "Oceania",  subregion: "Micronesia",       un_member: true,  sovereign: true },
  { iso_alpha_2: "MH", iso_alpha_3: "MHL", numeric_code: "584", name: "Marshall Islands",          region: "Oceania",  subregion: "Micronesia",       un_member: true,  sovereign: true },
  { iso_alpha_2: "FM", iso_alpha_3: "FSM", numeric_code: "583", name: "Micronesia",                region: "Oceania",  subregion: "Micronesia",       un_member: true,  sovereign: true },
  { iso_alpha_2: "NR", iso_alpha_3: "NRU", numeric_code: "520", name: "Nauru",                     region: "Oceania",  subregion: "Micronesia",       un_member: true,  sovereign: true },
  { iso_alpha_2: "NC", iso_alpha_3: "NCL", numeric_code: "540", name: "New Caledonia",             region: "Oceania",  subregion: "Melanesia",        un_member: false, sovereign: false },
  { iso_alpha_2: "NZ", iso_alpha_3: "NZL", numeric_code: "554", name: "New Zealand",               region: "Oceania",  subregion: "Australia and New Zealand", un_member: true, sovereign: true },
  { iso_alpha_2: "NU", iso_alpha_3: "NIU", numeric_code: "570", name: "Niue",                      region: "Oceania",  subregion: "Polynesia",        un_member: false, sovereign: false },
  { iso_alpha_2: "NF", iso_alpha_3: "NFK", numeric_code: "574", name: "Norfolk Island",            region: "Oceania",  subregion: "Australia and New Zealand", un_member: false, sovereign: false },
  { iso_alpha_2: "MP", iso_alpha_3: "MNP", numeric_code: "580", name: "Northern Mariana Islands",  region: "Oceania",  subregion: "Micronesia",       un_member: false, sovereign: false },
  { iso_alpha_2: "PW", iso_alpha_3: "PLW", numeric_code: "585", name: "Palau",                     region: "Oceania",  subregion: "Micronesia",       un_member: true,  sovereign: true },
  { iso_alpha_2: "PG", iso_alpha_3: "PNG", numeric_code: "598", name: "Papua New Guinea",          region: "Oceania",  subregion: "Melanesia",        un_member: true,  sovereign: true },
  { iso_alpha_2: "PN", iso_alpha_3: "PCN", numeric_code: "612", name: "Pitcairn",                  region: "Oceania",  subregion: "Polynesia",        un_member: false, sovereign: false },
  { iso_alpha_2: "WS", iso_alpha_3: "WSM", numeric_code: "882", name: "Samoa",                     region: "Oceania",  subregion: "Polynesia",        un_member: true,  sovereign: true },
  { iso_alpha_2: "SB", iso_alpha_3: "SLB", numeric_code: "090", name: "Solomon Islands",           region: "Oceania",  subregion: "Melanesia",        un_member: true,  sovereign: true },
  { iso_alpha_2: "TK", iso_alpha_3: "TKL", numeric_code: "772", name: "Tokelau",                   region: "Oceania",  subregion: "Polynesia",        un_member: false, sovereign: false },
  { iso_alpha_2: "TO", iso_alpha_3: "TON", numeric_code: "776", name: "Tonga",                     region: "Oceania",  subregion: "Polynesia",        un_member: true,  sovereign: true },
  { iso_alpha_2: "TV", iso_alpha_3: "TUV", numeric_code: "798", name: "Tuvalu",                    region: "Oceania",  subregion: "Polynesia",        un_member: true,  sovereign: true },
  { iso_alpha_2: "VU", iso_alpha_3: "VUT", numeric_code: "548", name: "Vanuatu",                   region: "Oceania",  subregion: "Melanesia",        un_member: true,  sovereign: true },
  { iso_alpha_2: "WF", iso_alpha_3: "WLF", numeric_code: "876", name: "Wallis and Futuna",         region: "Oceania",  subregion: "Polynesia",        un_member: false, sovereign: false },

  // ── Antarctica ──
  { iso_alpha_2: "AQ", iso_alpha_3: "ATA", numeric_code: "010", name: "Antarctica",                region: "Antarctica", subregion: "Antarctica",     un_member: false, sovereign: false },
];

// Summary constants (checked at test time · not asserted at build time)
export const UN_MEMBER_COUNT = ISO_3166_1.filter(c => c.un_member).length;
export const TOTAL_COUNTRY_COUNT = ISO_3166_1.length;
