// WO-WORKSTATION-03 · template registry
//
// Founder-authorised 2026-09-13 per ADR-0319 Workstation Activation Programme.
// Deterministic code-authoring templates. Templates are TypeScript functions
// that return strings — no external templating engine, no {{}} substitution
// magic, no LLM anywhere in the pipeline (P-S). Every template's output is
// a pure function of its typed params — same input, same bytes.
//
// The first slice of WO-03 provides a small but real template set: enough
// to author a plain Next.js App Router page (page.tsx), a simple JSON
// config, a package.json manifest, and a plain text README. That's
// sufficient for the 3-page-app acceptance test WO-11 will build toward.

import { z } from "zod";

// ── Template contract ───────────────────────────────────────────────────

export interface TemplateDefinition<TParams = unknown> {
  readonly template_ref: string;
  readonly description: string;
  /** Zod validator for the params object. Rejected params -> generator
   *  fails with a specific error before content is ever produced. */
  readonly paramsSchema: z.ZodType<TParams>;
  readonly render: (params: TParams) => string;
  /** File extension the template produces. Used by the syntax validator
   *  to pick the right check. */
  readonly file_extension: "tsx" | "ts" | "json" | "md" | "css" | "txt";
}

// ── Deterministic string escaping helpers ───────────────────────────────

/** Escape backslashes, quotes, and newlines for embedding in a TS string
 *  literal wrapped by double quotes. Deterministic. */
export function escapeForDoubleQuoted(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
}

/** Escape for use inside a JSX text node. Turns `<`, `>`, `&`, `{`, `}`
 *  into safe sequences. */
export function escapeForJsxText(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\{/g, "&#123;")
    .replace(/\}/g, "&#125;");
}

// ── Templates ───────────────────────────────────────────────────────────

// -- Next.js App Router page.tsx (server component, no client bailouts) --

const nextAppPageParams = z.object({
  route: z.string().min(1),                // used only in comment
  title: z.string().min(1),
  headline: z.string().min(1),
  paragraphs: z.array(z.string().min(1)).min(1),
});

export const NEXT_APP_PAGE_TEMPLATE: TemplateDefinition<z.infer<typeof nextAppPageParams>> = {
  template_ref: "next-app-page.v1",
  description: "Next.js 15/16 App Router page.tsx — server component, no hooks, no useSearchParams (so no Suspense wrap needed)",
  paramsSchema: nextAppPageParams,
  file_extension: "tsx",
  render: (p) => {
    const paragraphs = p.paragraphs
      .map((para) => `      <p>${escapeForJsxText(para)}</p>`)
      .join("\n");
    return (
      `// Auto-generated by NEX1 WO-03 · route ${p.route}\n` +
      `import type { Metadata } from "next";\n` +
      `\n` +
      `export const metadata: Metadata = {\n` +
      `  title: "${escapeForDoubleQuoted(p.title)}"\n` +
      `};\n` +
      `\n` +
      `export default function Page() {\n` +
      `  return (\n` +
      `    <main>\n` +
      `      <h1>${escapeForJsxText(p.headline)}</h1>\n` +
      `${paragraphs}\n` +
      `    </main>\n` +
      `  );\n` +
      `}\n`
    );
  },
};

// -- Next.js root layout for a generated project ------------------------

const nextRootLayoutParams = z.object({
  siteTitle: z.string().min(1),
});

export const NEXT_ROOT_LAYOUT_TEMPLATE: TemplateDefinition<z.infer<typeof nextRootLayoutParams>> = {
  template_ref: "next-root-layout.v1",
  description: "Next.js App Router root layout.tsx — minimal shell",
  paramsSchema: nextRootLayoutParams,
  file_extension: "tsx",
  render: (p) => (
    `// Auto-generated by NEX1 WO-03 · root layout\n` +
    `import type { Metadata } from "next";\n` +
    `\n` +
    `export const metadata: Metadata = {\n` +
    `  title: "${escapeForDoubleQuoted(p.siteTitle)}"\n` +
    `};\n` +
    `\n` +
    `export default function RootLayout({ children }: { children: React.ReactNode }) {\n` +
    `  return (\n` +
    `    <html lang="en">\n` +
    `      <body>{children}</body>\n` +
    `    </html>\n` +
    `  );\n` +
    `}\n`
  ),
};

// -- Minimal package.json for a generated project ----------------------

const packageJsonParams = z.object({
  name: z.string().regex(/^[a-z0-9][a-z0-9-]*$/, "npm package name: lowercase alnum + hyphen only"),
  version: z.string().regex(/^\d+\.\d+\.\d+$/, "semver x.y.z required"),
  description: z.string().default(""),
});

export const PACKAGE_JSON_TEMPLATE: TemplateDefinition<z.infer<typeof packageJsonParams>> = {
  template_ref: "package-json.v1",
  description: "Minimal package.json for a NEX1-generated Next.js project",
  paramsSchema: packageJsonParams,
  file_extension: "json",
  render: (p) => JSON.stringify({
    name: p.name,
    version: p.version,
    description: p.description,
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
    },
    dependencies: {
      next: "^16.2.9",
      react: "^19.0.0",
      "react-dom": "^19.0.0",
    },
  }, null, 2) + "\n",
};

// -- Plain README.md ---------------------------------------------------

const readmeParams = z.object({
  projectName: z.string().min(1),
  summary: z.string().min(1),
});

export const README_TEMPLATE: TemplateDefinition<z.infer<typeof readmeParams>> = {
  template_ref: "readme.v1",
  description: "Plain README.md for a generated project",
  paramsSchema: readmeParams,
  file_extension: "md",
  render: (p) => (
    `# ${p.projectName}\n` +
    `\n` +
    `${p.summary}\n` +
    `\n` +
    `Auto-generated by NEX1 WO-03. Every file in this project has an\n` +
    `authorisation record + diff hash in the workstation audit trail.\n`
  ),
};

// -- Plain text (used for tests / minimal cases) -----------------------

const plainTextParams = z.object({
  body: z.string(),
});

export const PLAIN_TEXT_TEMPLATE: TemplateDefinition<z.infer<typeof plainTextParams>> = {
  template_ref: "plain-text.v1",
  description: "Verbatim body text, no framing",
  paramsSchema: plainTextParams,
  file_extension: "txt",
  render: (p) => p.body,
};

// -- Plain Node HTTP server (used by WO-11 for the first-app acceptance
//    test). Deliberately zero-dependency so real build+runtime finish in
//    seconds instead of the 10 min a full `npm install`+`next build` needs.
//    Routes are configurable; each path returns its `body` verbatim with
//    200; every other path returns 404. The server reads its port from
//    the env var named by port_env_var (default PORT). Exits cleanly on
//    SIGTERM so WO-06 termination protocol works. -----------------

const plainNodeServerParams = z.object({
  port_env_var: z.string().min(1).default("PORT"),
  default_port: z.number().int().min(1).max(65_535).default(3000),
  routes: z.array(z.object({
    path: z.string().refine((s) => s.startsWith("/"), "route path must start with /"),
    body: z.string(),
  })).min(1),
});

export const PLAIN_NODE_SERVER_TEMPLATE: TemplateDefinition<z.infer<typeof plainNodeServerParams>> = {
  template_ref: "plain-node-server.v1",
  description: "Zero-dependency Node HTTP server with configurable routes; used for WO-11 first-app acceptance",
  paramsSchema: plainNodeServerParams,
  file_extension: "js",
  render: (p) => {
    const routesLiteral = p.routes
      .map((r) => `  ${JSON.stringify(r.path)}: ${JSON.stringify(r.body)}`)
      .join(",\n");
    return (
      `// Auto-generated by NEX1 WO-11 · plain Node HTTP server\n` +
      `const http = require('http');\n` +
      `const port = Number(process.env.${p.port_env_var} || ${p.default_port});\n` +
      `const routes = {\n${routesLiteral}\n};\n` +
      `const server = http.createServer((req, res) => {\n` +
      `  const key = req.url;\n` +
      `  if (Object.prototype.hasOwnProperty.call(routes, key)) {\n` +
      `    res.writeHead(200, { 'content-type': 'text/plain; charset=utf-8' });\n` +
      `    res.end(routes[key]);\n` +
      `  } else {\n` +
      `    res.writeHead(404, { 'content-type': 'text/plain; charset=utf-8' });\n` +
      `    res.end('Not Found');\n` +
      `  }\n` +
      `});\n` +
      `server.listen(port, '127.0.0.1', () => { console.log('listening on ' + port); });\n` +
      `process.on('SIGTERM', () => { server.close(() => process.exit(0)); });\n`
    );
  },
};

// ── Registry ────────────────────────────────────────────────────────────

const TEMPLATE_LIST: readonly TemplateDefinition<unknown>[] = [
  NEXT_APP_PAGE_TEMPLATE as TemplateDefinition<unknown>,
  NEXT_ROOT_LAYOUT_TEMPLATE as TemplateDefinition<unknown>,
  PACKAGE_JSON_TEMPLATE as TemplateDefinition<unknown>,
  README_TEMPLATE as TemplateDefinition<unknown>,
  PLAIN_TEXT_TEMPLATE as TemplateDefinition<unknown>,
  PLAIN_NODE_SERVER_TEMPLATE as TemplateDefinition<unknown>,
];

const TEMPLATE_MAP: ReadonlyMap<string, TemplateDefinition<unknown>> = new Map(
  TEMPLATE_LIST.map((t) => [t.template_ref, t] as const),
);

/** Look up a template by ref. Returns undefined if not registered — the
 *  generator surfaces this as a specific TEMPLATE_UNKNOWN failure. */
export function findTemplate(template_ref: string): TemplateDefinition<unknown> | undefined {
  return TEMPLATE_MAP.get(template_ref);
}

/** Sorted list of registered template refs. Useful for error messages
 *  ("did you mean …?") and telemetry. */
export function listTemplateRefs(): readonly string[] {
  return TEMPLATE_LIST.map((t) => t.template_ref).slice().sort();
}
