// src/lib/nex/context-management/summarization-anchor.ts
//
// WAVE-P-1.4 · Summarization anchor · replace dropped middle with summary
// Founder BEGIN WAVE-P-1 · 2026-09-08
//
// Given messages that don't fit under sliding window · replace the
// middle band (between anchors and tail) with a summary block. This
// module produces the STRUCTURED summary placeholder; the actual
// summary text is generated by a caller-supplied summarizer (which
// itself uses the LLM gateway from P-1.1).

import type { NexMessage } from "@/lib/nex/brain/provider";
import type { AnchorRule, ContextBudget, TruncationResult } from "./types";
import { DEFAULT_CONTEXT_BUDGET } from "./types";
import { estimateMessageTokens, identifyAnchorIndices, packWithSlidingWindow } from "./sliding-window";

/** Callback that produces the summary text given a range of messages.
 *  Must be pure/deterministic OR at least stable within a session ·
 *  callers typically wrap an LLM invocation. */
export type Summarizer = (input: { messages: readonly NexMessage[]; target_tokens: number }) => Promise<string>;

/** Deterministic fallback summarizer · concatenates + truncates.
 *  Used when no LLM summarizer is provided (tests · offline mode). */
export function deterministicSummarizer(): Summarizer {
  return async ({ messages, target_tokens }) => {
    const target_chars = target_tokens * 4;
    const lines: string[] = [`[NEX CONTEXT SUMMARY · ${messages.length} messages compressed]`];
    for (const m of messages) {
      const role = m.role;
      const text = typeof m.content === "string" ? m.content : m.content.map((b) => {
        if (b.type === "text" || b.type === "thinking") return b.text;
        if (b.type === "tool_result") return `[tool_result: ${b.result.slice(0, 80)}]`;
        if (b.type === "tool_call") return `[tool_call: ${b.toolName}]`;
        return "[image]";
      }).join(" ");
      lines.push(`${role}: ${text.slice(0, 200)}`);
    }
    const joined = lines.join("\n");
    return joined.length > target_chars ? joined.slice(0, target_chars - 20) + "…[truncated]" : joined;
  };
}

/** Hybrid pack · anchors + summarized middle + tail. When even that
 *  doesn't fit · falls back to plain sliding_window. */
export async function packWithHybridSummary(input: {
  messages: readonly NexMessage[];
  system_prompt_tokens: number;
  budget?: ContextBudget;
  anchor_rules?: readonly AnchorRule[];
  summarizer?: Summarizer;
  /** Reserve for the summary block itself · caller controls how big
   *  the summary is allowed to be. */
  summary_max_tokens?: number;
}): Promise<TruncationResult> {
  const budget = input.budget ?? DEFAULT_CONTEXT_BUDGET;
  const summarizer = input.summarizer ?? deterministicSummarizer();
  const summary_max = input.summary_max_tokens ?? 800;
  const rules = input.anchor_rules ?? [];

  // First try plain sliding window · if it fits everything · no need to summarize
  const plain = packWithSlidingWindow({ messages: input.messages, system_prompt_tokens: input.system_prompt_tokens, budget, anchor_rules: rules });
  if (!plain.information_lost) return plain;

  const anchor_indices = identifyAnchorIndices(input.messages, rules);
  const effective_budget = Math.floor(
    (budget.max_input_tokens - budget.reserve_for_output_tokens) * (1 - budget.headroom_fraction),
  ) - input.system_prompt_tokens - summary_max;

  if (effective_budget <= 0) {
    // No room for anything · degrade to plain sliding window
    return plain;
  }

  // Identify anchors + tail messages that fit
  const anchor_msgs: { idx: number; tokens: number; msg: NexMessage }[] = [];
  let tokens_used = 0;
  for (const idx of Array.from(anchor_indices).sort((a, b) => a - b)) {
    const m = input.messages[idx];
    const t = estimateMessageTokens(m);
    if (tokens_used + t > effective_budget) break;
    anchor_msgs.push({ idx, tokens: t, msg: m });
    tokens_used += t;
  }
  const anchor_idx_set = new Set(anchor_msgs.map((a) => a.idx));

  const tail_msgs: { idx: number; tokens: number; msg: NexMessage }[] = [];
  for (let i = input.messages.length - 1; i >= 0; i--) {
    if (anchor_idx_set.has(i)) continue;
    const m = input.messages[i];
    const t = estimateMessageTokens(m);
    if (tokens_used + t > effective_budget) break;
    tail_msgs.unshift({ idx: i, tokens: t, msg: m });
    tokens_used += t;
  }

  const kept_idx_set = new Set([...anchor_idx_set, ...tail_msgs.map((t) => t.idx)]);
  const to_summarize: NexMessage[] = [];
  for (let i = 0; i < input.messages.length; i++) {
    if (!kept_idx_set.has(i)) to_summarize.push(input.messages[i]);
  }

  if (to_summarize.length === 0) {
    // Everything fits without summary · return equivalent of plain
    return plain;
  }

  const summary_text = await summarizer({ messages: to_summarize, target_tokens: summary_max });
  const summary_msg: NexMessage = { role: "assistant", content: [{ type: "text", text: summary_text }] };

  // Insert summary_msg between anchors and tail (in original order)
  const packed: NexMessage[] = [];
  const anchor_sorted = anchor_msgs.sort((a, b) => a.idx - b.idx);
  for (const a of anchor_sorted) packed.push(a.msg);
  packed.push(summary_msg);
  for (const t of tail_msgs) packed.push(t.msg);

  const summary_tokens = estimateMessageTokens(summary_msg);
  const final_tokens = tokens_used + summary_tokens + input.system_prompt_tokens;

  return {
    packed_messages: packed,
    dropped_message_count: 0,
    summarized_message_count: to_summarize.length,
    anchor_message_count: anchor_msgs.length,
    input_tokens_estimated: final_tokens,
    input_tokens_budget: budget.max_input_tokens,
    strategy_used: "hybrid_anchor_summarize",
    cache_breakpoints: [],
    information_lost: false, // summarized · not silently dropped
    notes: `Summarized ${to_summarize.length} message(s) into ${summary_tokens}-token block · ${anchor_msgs.length} anchor(s) + ${tail_msgs.length} tail preserved verbatim`,
  };
}
