// Golden Path client component — the end-to-end story UI.
//
// Renders the 8-step flywheel for Phil's Carpentry and lets the
// visitor toggle between "before Phil acts" and "after Phil acts on
// the coach" to see the score improve + backlog shrink.

"use client";

import {
  ArrowRight,
  BadgeCheck,
  BookOpen,
  Building2,
  CalendarDays,
  Camera,
  ClipboardList,
  Compass,
  FileText,
  Hammer,
  Layers,
  MapPin,
  MessageSquareQuote,
  Sparkles,
  Star,
  Target,
  Wand2,
  Zap
} from "lucide-react";
import { useMemo, useState } from "react";
import {
  businessProfileRegistry,
  growthStrategyRegistry,
  patternRegistry,
  playbookRegistry,
  strategyResolver,
  StrategyExplainerPanel,
  websiteRecipeRegistry
} from "@/platform/business";
import { BusinessCoachPanel } from "@/platform/coach";
import type { CoachContext } from "@/platform/coach";
import type {
  ContentBlock,
  ContentManifest,
  FaqBlockData,
  HeroBlockData,
  ProjectStoryBlockData,
  SeoPageBlockData,
  ServiceListBlockData,
  TrustCopyBlockData,
  ValuePropsBlockData
} from "@/platform/content";

type ScenarioPrimitives = {
  projectCount: number;
  reviewCount: number;
  certificationsHeld: readonly string[];
  lastStrategyReviewAt: string | null;
};

type Props = {
  profileSlug: string;
  strategySlug: string;
  recipeSlug: string;
  strategyDescribe: string;
  manifestBefore: ContentManifest;
  manifestAfter: ContentManifest;
  coachBefore: ScenarioPrimitives;
  coachAfter: ScenarioPrimitives;
};

export function GoldenPathDemo(props: Props) {
  const [mode, setMode] = useState<"before" | "after">("before");

  // Client-side rehydrate strategy from registries (already loaded on
  // the server via side-effect imports on the page component).
  const strategy = useMemo(() => {
    const profile = businessProfileRegistry.getOrThrow(props.profileSlug);
    const growth = growthStrategyRegistry.getOrThrow(props.strategySlug);
    const recipe = websiteRecipeRegistry.getOrThrow(props.recipeSlug);
    return strategyResolver.resolve({ profile, strategy: growth, recipe });
  }, [props.profileSlug, props.strategySlug, props.recipeSlug]);

  const activeManifest = mode === "before" ? props.manifestBefore : props.manifestAfter;
  const activeCoachPrimitives = mode === "before" ? props.coachBefore : props.coachAfter;
  const active = useMemo(
    () => ({
      manifest: activeManifest,
      coach: {
        strategy,
        projectCount: activeCoachPrimitives.projectCount,
        reviewCount: activeCoachPrimitives.reviewCount,
        certificationsHeld: activeCoachPrimitives.certificationsHeld,
        lastStrategyReviewAt: activeCoachPrimitives.lastStrategyReviewAt ?? undefined,
        outputMedium: "website"
      } as CoachContext
    }),
    [strategy, activeManifest, activeCoachPrimitives]
  );

  const profile = strategy.inputs.profile;
  const growth = strategy.inputs.strategy;
  const recipe = strategy.inputs.recipe;

  return (
    <main className="min-h-screen bg-neutral-50">
      <div className="mx-auto max-w-5xl px-4 py-10">
        {/* ── Hero framing ────────────────────────────────────── */}
        <header className="mb-8">
          <div className="mb-2 inline-flex items-center gap-2 rounded-full bg-neutral-900 px-3 py-1 text-[11px] font-medium text-white">
            <Sparkles className="h-3 w-3" /> Golden Path Demo
          </div>
          <h1 className="text-3xl font-bold text-neutral-900">
            Phil&apos;s Carpentry, Dublin
          </h1>
          <p className="mt-2 max-w-2xl text-[13px] leading-relaxed text-neutral-700">
            One business. One growth goal. Every panel below is generated by
            the Xrated Trades platform from real registry data — no
            hand-authored demo content. Toggle the scenario at the bottom
            to see what happens when Phil acts on the coach&apos;s advice.
          </p>
        </header>

        {/* ── STEP 1 · Merchant signs up ──────────────────────── */}
        <StepCard step={1} icon={Building2} label="AI understands the business">
          <div className="grid gap-2 text-[13px] md:grid-cols-2">
            <Detail label="Business">{profile.name}</Detail>
            <Detail label="Trade">{profile.trade}</Detail>
            <Detail label="Country · region">
              {profile.country} · {profile.regions?.join(", ")}
            </Detail>
            <Detail label="Years trading">{profile.yearsTrading}+</Detail>
            <Detail label="Positioning">{profile.positioning}</Detail>
            <Detail label="Customer">{profile.customerType}</Detail>
            <Detail label="Primary services">
              {profile.primaryServices.join(", ")}
            </Detail>
            <Detail label="Avg job value">
              €{profile.averageJobValue?.min.toLocaleString()} – €
              {profile.averageJobValue?.max.toLocaleString()}
            </Detail>
          </div>
        </StepCard>

        {/* ── STEP 2 · Growth Strategy ────────────────────────── */}
        <StepCard step={2} icon={Target} label="Growth strategy locked in">
          <div className="grid gap-2 text-[13px] md:grid-cols-2">
            <Detail label="Current goal">
              {growth.currentGoal.replace(/-/g, " ")}
            </Detail>
            <Detail label="Quarter goal">{growth.quarterGoal}</Detail>
            <Detail label="Push services">
              {growth.pushServices?.join(", ")}
            </Detail>
            <Detail label="Reduce services">
              {growth.reduceServices?.join(", ")}
            </Detail>
          </div>
        </StepCard>

        {/* ── STEP 3 · Playbooks selected ─────────────────────── */}
        <StepCard step={3} icon={Layers} label="Playbooks selected">
          <p className="mb-2 text-[13px] text-neutral-700">
            Recipe: <strong>{recipe.name}</strong> — {recipe.description}
          </p>
          <ul className="flex flex-col gap-1 text-[13px]">
            {recipe.playbooks.map((slug) => {
              const p = playbookRegistry.get(slug);
              if (!p) return null;
              return (
                <li
                  key={slug}
                  className="flex items-start gap-2 rounded-lg bg-neutral-50 px-3 py-2"
                >
                  <BadgeCheck className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />
                  <div>
                    <div className="font-medium text-neutral-900">{p.name}</div>
                    {p.rationale ? (
                      <div className="text-neutral-600">
                        {p.rationale.statement}
                      </div>
                    ) : null}
                  </div>
                </li>
              );
            })}
          </ul>
        </StepCard>

        {/* ── STEP 4 · What the platform decided ──────────────── */}
        <StepCard step={4} icon={Wand2} label="What the platform decided">
          <StrategyExplainerPanel
            strategy={strategy}
            title="Why is Phil's website built this way?"
          />
        </StepCard>

        {/* ── STEP 5 · What the platform BUILT ────────────────── */}
        <StepCard step={5} icon={FileText} label="What the platform built">
          <ManifestPreview manifest={active.manifest} />
        </StepCard>

        {/* ── STEP 6 · Booking + Dashboard ────────────────────── */}
        <StepCard step={6} icon={ClipboardList} label="Booking flow + dashboard">
          <div className="grid gap-3 md:grid-cols-2">
            <SmallCard title="Booking flow" icon={CalendarDays}>
              Phil&apos;s recipe uses the{" "}
              <strong>simple-service-booking</strong> flow. Customer picks
              service → date → info → confirms. Featured service on top:{" "}
              <strong>{growth.pushServices?.[0]?.replace(/-/g, " ")}</strong>.
              Primary CTA:{" "}
              <strong>
                {
                  (
                    strategy.get("cta", "primary") as
                      | { ctaLabelHint?: string }
                      | undefined
                  )?.ctaLabelHint
                }
              </strong>
              .
            </SmallCard>
            <SmallCard title="Merchant dashboard" icon={Zap}>
              Metrics: quote requests · form conversion rate · average job
              value · revenue · jobs completed. Suggested actions surface
              at the top of every session. All wired from the{" "}
              <em>quote-driven</em> playbook&apos;s dashboard facets.
            </SmallCard>
          </div>
        </StepCard>

        {/* ── STEP 7 · Coach + backlog ────────────────────────── */}
        <StepCard step={7} icon={Compass} label="Business Operating Coach">
          <div className="mb-3 flex items-center gap-2 text-[13px]">
            <span className="text-neutral-600">Simulation:</span>
            <div className="inline-flex rounded-full border border-neutral-300 bg-white p-0.5">
              <button
                type="button"
                onClick={() => setMode("before")}
                className={`rounded-full px-3 py-1 text-[12px] transition ${
                  mode === "before"
                    ? "bg-neutral-900 text-white"
                    : "text-neutral-700 hover:bg-neutral-50"
                }`}
              >
                Before Phil acts
              </button>
              <button
                type="button"
                onClick={() => setMode("after")}
                className={`rounded-full px-3 py-1 text-[12px] transition ${
                  mode === "after"
                    ? "bg-neutral-900 text-white"
                    : "text-neutral-700 hover:bg-neutral-50"
                }`}
              >
                After Phil acts
              </button>
            </div>
            <span className="text-[11px] text-neutral-500">
              {mode === "before"
                ? `${active.coach.projectCount} projects · ${active.coach.reviewCount} reviews · strategy stale`
                : `${active.coach.projectCount} projects · ${active.coach.reviewCount} reviews · certifications added · strategy refreshed`}
            </span>
          </div>
          <BusinessCoachPanel
            context={active.coach}
            title={
              mode === "before"
                ? "This month — start here"
                : "This month — score improved"
            }
          />
        </StepCard>

        {/* ── STEP 8 · Evidence closes the loop ───────────────── */}
        <StepCard step={8} icon={MessageSquareQuote} label="The loop closes">
          <p className="mb-2 text-[13px] text-neutral-700">
            Every recommendation on this page is backed by real registered
            evidence and patterns. When these findings pass A/B tests +
            reach the &quot;proven&quot; validation state, confidence auto-recomputes
            and priority rises. Nothing is hand-set.
          </p>
          <div className="flex flex-col gap-2 text-[13px]">
            {(
              [
                "doors-carpenter-free-survey-gallery-first",
                "trust-above-the-fold-general"
              ] as const
            ).map((slug) => {
              const p = patternRegistry.get(slug);
              if (!p) return null;
              const derived = patternRegistry.confidenceOf(slug);
              return (
                <div
                  key={slug}
                  className="rounded-lg border border-neutral-200 bg-white p-3"
                >
                  <div className="flex items-center justify-between">
                    <div className="font-medium text-neutral-900">{p.title}</div>
                    <span className="rounded-full bg-neutral-100 px-2 py-0.5 text-[11px] text-neutral-700">
                      {derived}% derived confidence
                    </span>
                  </div>
                  <div className="mt-1 text-[12px] text-neutral-600">
                    {p.statement}
                  </div>
                  <div className="mt-1 text-[11px] text-neutral-500">
                    Backed by {p.supportingEvidence.length} evidence finding
                    {p.supportingEvidence.length === 1 ? "" : "s"} ·{" "}
                    {p.candidacy.status}
                  </div>
                </div>
              );
            })}
          </div>
        </StepCard>

        <footer className="mt-8 rounded-2xl border border-neutral-200 bg-white p-6 text-[13px] text-neutral-700">
          <div className="mb-1 flex items-center gap-2 font-semibold text-neutral-900">
            <Hammer className="h-4 w-4" /> What just happened
          </div>
          <p>
            You watched the Xrated Trades platform take a merchant profile
            plus a growth strategy and produce a fully composed website
            (hero, service list, trust, FAQ, project stories, SEO pages, a
            booking flow, a dashboard) — all typed, all provenance-carrying
            — then continuously coach the merchant on the highest-impact
            next action. Every decision is traceable to a playbook, a
            pattern, and a piece of evidence.
          </p>
          <p className="mt-2 text-neutral-600">
            No hand-authored demo copy. No fabricated numbers. When the
            evidence gets stronger, everything on this page gets smarter.
          </p>
        </footer>
      </div>
    </main>
  );
}

// ─── UI helpers ────────────────────────────────────────────────
function StepCard({
  step,
  icon: Icon,
  label,
  children
}: {
  step: number;
  icon: typeof Compass;
  label: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mb-6 rounded-2xl border border-neutral-200 bg-white p-6 shadow-sm">
      <header className="mb-4 flex items-center gap-3">
        <div className="flex h-8 w-8 items-center justify-center rounded-full bg-neutral-900 text-[13px] font-semibold text-white">
          {step}
        </div>
        <div className="flex items-center gap-2 text-neutral-900">
          <Icon className="h-4 w-4 text-neutral-500" />
          <h2 className="text-[15px] font-semibold">{label}</h2>
        </div>
      </header>
      {children}
    </section>
  );
}

function Detail({
  label,
  children
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col gap-0.5 rounded-lg bg-neutral-50 px-3 py-2">
      <span className="text-[11px] uppercase tracking-wide text-neutral-500">
        {label}
      </span>
      <span className="text-neutral-900">{children}</span>
    </div>
  );
}

function SmallCard({
  title,
  icon: Icon,
  children
}: {
  title: string;
  icon: typeof Compass;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded-xl border border-neutral-200 bg-white p-4 text-[13px]">
      <div className="mb-1 flex items-center gap-2 font-semibold text-neutral-900">
        <Icon className="h-4 w-4 text-neutral-500" /> {title}
      </div>
      <div className="text-neutral-700">{children}</div>
    </div>
  );
}

function ManifestPreview({ manifest }: { manifest: ContentManifest }) {
  const homeBlocks =
    manifest.pages
      .find((p) => p.slug === "home")
      ?.sections.flatMap((s) => s.blocks) ?? [];
  const heroBlock = homeBlocks.find((b) => b.kind === "hero") as
    | ContentBlock<HeroBlockData>
    | undefined;
  const serviceBlock = homeBlocks.find((b) => b.kind === "service-list") as
    | ContentBlock<ServiceListBlockData>
    | undefined;
  const valuePropsBlock = homeBlocks.find((b) => b.kind === "value-props") as
    | ContentBlock<ValuePropsBlockData>
    | undefined;
  const trustBlock = homeBlocks.find((b) => b.kind === "trust-copy") as
    | ContentBlock<TrustCopyBlockData>
    | undefined;
  const faqBlock = homeBlocks.find((b) => b.kind === "faq") as
    | ContentBlock<FaqBlockData>
    | undefined;
  const projectBlocks = manifest.pages
    .flatMap((p) => p.sections)
    .flatMap((s) => s.blocks)
    .filter((b) => b.kind === "project-story") as ContentBlock<ProjectStoryBlockData>[];
  const seoBlocks = manifest.pages
    .flatMap((p) => p.sections)
    .flatMap((s) => s.blocks)
    .filter((b) => b.kind === "seo-page") as ContentBlock<SeoPageBlockData>[];

  return (
    <div className="flex flex-col gap-4 text-[13px]">
      {/* Hero preview */}
      {heroBlock ? (
        <div className="rounded-xl bg-gradient-to-br from-neutral-900 to-neutral-800 p-6 text-white">
          <div className="mb-1 text-[11px] uppercase tracking-wide text-neutral-400">
            Hero
          </div>
          <h3 className="text-xl font-bold">{heroBlock.data.headline}</h3>
          {heroBlock.data.subheadline ? (
            <p className="mt-1 text-neutral-200">
              {heroBlock.data.subheadline}
            </p>
          ) : null}
          {heroBlock.data.supportingLine ? (
            <p className="mt-1 text-[12px] text-neutral-300">
              {heroBlock.data.supportingLine}
            </p>
          ) : null}
          <div className="mt-3 inline-flex rounded-full bg-amber-400 px-4 py-2 font-semibold text-neutral-900">
            {heroBlock.data.primaryCtaLabel}
          </div>
          <div className="mt-2 text-[10px] text-neutral-400">
            Composer: {heroBlock.provenance.generatedBy} · Purpose:{" "}
            {heroBlock.provenance.purpose} · Confidence:{" "}
            {heroBlock.provenance.confidenceBand}
          </div>
        </div>
      ) : null}

      {/* Service list */}
      {serviceBlock ? (
        <div className="rounded-xl border border-neutral-200 bg-white p-4">
          <div className="mb-1 flex items-center gap-2 text-[11px] uppercase tracking-wide text-neutral-500">
            <Hammer className="h-3 w-3" /> Services
          </div>
          <p className="mb-2 text-neutral-700">{serviceBlock.data.intro}</p>
          <ul className="grid gap-2 md:grid-cols-2">
            {serviceBlock.data.items.slice(0, 6).map((s) => (
              <li
                key={s.slug}
                className="rounded-lg border border-neutral-200 bg-neutral-50 px-3 py-2"
              >
                <div className="flex items-center gap-2 font-medium text-neutral-900">
                  {s.title}
                  {s.featured ? (
                    <span className="rounded-full bg-amber-100 px-1.5 py-0.5 text-[10px] font-semibold text-amber-800">
                      Featured
                    </span>
                  ) : null}
                  {s.marginBand === "high" ? (
                    <span className="rounded-full bg-emerald-100 px-1.5 py-0.5 text-[10px] text-emerald-800">
                      High margin
                    </span>
                  ) : null}
                </div>
                <div className="text-[12px] text-neutral-600">
                  {s.description}
                </div>
              </li>
            ))}
          </ul>
        </div>
      ) : null}

      {/* Value props */}
      {valuePropsBlock ? (
        <div className="rounded-xl border border-neutral-200 bg-white p-4">
          <div className="mb-1 flex items-center gap-2 text-[11px] uppercase tracking-wide text-neutral-500">
            <Star className="h-3 w-3" /> Why us
          </div>
          <h4 className="mb-2 font-semibold text-neutral-900">
            {valuePropsBlock.data.heading}
          </h4>
          <ul className="grid gap-2 md:grid-cols-2">
            {valuePropsBlock.data.items.map((item, i) => (
              <li
                key={i}
                className="rounded-lg border border-neutral-200 bg-neutral-50 px-3 py-2"
              >
                <div className="font-medium text-neutral-900">{item.title}</div>
                <div className="text-[12px] text-neutral-600">
                  {item.description}
                </div>
              </li>
            ))}
          </ul>
        </div>
      ) : null}

      {/* Trust */}
      {trustBlock ? (
        <div className="rounded-xl border border-neutral-200 bg-white p-4">
          <div className="mb-1 flex items-center gap-2 text-[11px] uppercase tracking-wide text-neutral-500">
            <BadgeCheck className="h-3 w-3" /> Trust
          </div>
          <h4 className="mb-2 font-semibold text-neutral-900">
            {trustBlock.data.heading}
          </h4>
          <ul className="flex flex-col gap-1 text-neutral-700">
            {trustBlock.data.bullets.map((b, i) => (
              <li key={i}>· {b}</li>
            ))}
          </ul>
          {trustBlock.data.guaranteeLine ? (
            <p className="mt-2 text-[12px] italic text-neutral-600">
              {trustBlock.data.guaranteeLine}
            </p>
          ) : null}
        </div>
      ) : null}

      {/* Project stories */}
      {projectBlocks.length ? (
        <div className="rounded-xl border border-neutral-200 bg-white p-4">
          <div className="mb-1 flex items-center gap-2 text-[11px] uppercase tracking-wide text-neutral-500">
            <Camera className="h-3 w-3" /> Project stories ({projectBlocks.length})
          </div>
          <ul className="flex flex-col gap-2">
            {projectBlocks.slice(0, 4).map((p) => (
              <li
                key={p.slug}
                className="rounded-lg border border-neutral-200 bg-neutral-50 p-3"
              >
                <div className="flex items-center justify-between">
                  <div className="font-medium text-neutral-900">
                    {p.data.title}
                  </div>
                  <div className="text-[11px] text-neutral-500">
                    {p.data.photoCount} photos
                  </div>
                </div>
                <div className="text-[12px] text-neutral-600">
                  {p.data.solution}
                </div>
                {p.data.customerQuote ? (
                  <div className="mt-2 rounded bg-white p-2 text-[12px] italic text-neutral-700">
                    &ldquo;{p.data.customerQuote.text}&rdquo;
                    <div className="mt-0.5 text-[11px] not-italic text-neutral-500">
                      — {p.data.customerQuote.attribution}
                    </div>
                  </div>
                ) : (
                  <div className="mt-2 rounded bg-amber-50 p-2 text-[11px] text-amber-800">
                    No customer quote yet — the platform never fabricates
                    one. The coach will ask Phil to request one.
                  </div>
                )}
              </li>
            ))}
          </ul>
        </div>
      ) : null}

      {/* FAQ */}
      {faqBlock ? (
        <div className="rounded-xl border border-neutral-200 bg-white p-4">
          <div className="mb-1 flex items-center gap-2 text-[11px] uppercase tracking-wide text-neutral-500">
            <BookOpen className="h-3 w-3" /> FAQ
          </div>
          <ul className="flex flex-col gap-1 text-neutral-700">
            {faqBlock.data.items.slice(0, 4).map((f, i) => (
              <li key={i} className="rounded-lg bg-neutral-50 px-3 py-2">
                <div className="font-medium text-neutral-900">
                  {f.question}
                </div>
                <div
                  className={`text-[12px] ${
                    f.answer.startsWith("[Add")
                      ? "italic text-amber-700"
                      : "text-neutral-600"
                  }`}
                >
                  {f.answer}
                </div>
              </li>
            ))}
          </ul>
        </div>
      ) : null}

      {/* SEO page inventory */}
      {seoBlocks.length ? (
        <div className="rounded-xl border border-neutral-200 bg-white p-4">
          <div className="mb-1 flex items-center gap-2 text-[11px] uppercase tracking-wide text-neutral-500">
            <MapPin className="h-3 w-3" /> SEO pages generated
          </div>
          <ul className="flex flex-col gap-1">
            {seoBlocks.map((b) => (
              <li key={b.slug} className="flex items-center gap-2">
                <ArrowRight className="h-3 w-3 text-neutral-400" />
                <span className="text-neutral-900">{b.data.title}</span>
                <span className="text-[11px] text-neutral-500">
                  {b.data.pageKind} · {b.data.keywords.slice(0, 2).join(", ")}
                </span>
              </li>
            ))}
          </ul>
        </div>
      ) : null}
    </div>
  );
}
