"use client";

// Stone-effect render wizard — client-side interactive.
//
// Steps: 1) Guide (Philip's drawing) → 2) Postcode →
// 3) Elevations (A/B/C + openings dropdown) → 4) Result
//
// Estimate is generated by POSTing to /api/plan/stone-effect-render/estimate
// which does the cited-rate math server-side (rates never leak to the
// browser as bare numbers; every render includes citations).

import { useMemo, useState } from "react";
import Link from "next/link";
import {
  ArrowRight, ArrowLeft, Loader2, Info, ExternalLink,
  Plus, Minus, Trash2, AlertTriangle, Sparkles, MapPin,
  Home as HomeIcon, ScrollText, BookOpen
} from "lucide-react";

// ─── Types matching the API response ──────────────────────────────

type Opening = {
  type_slug:  string;
  label:      string;
  width_m:    number;
  height_m:   number;
  count:      number;
};
type Elevation = {
  name:        string;
  width_m:     number;
  height_m:    number;
  gable_rise_m: number;    // 0 if no gable
  openings:    Opening[];
};

type EstimateLine = {
  line_item_slug: string;
  display_name:   string;
  quantity:       number;
  unit:           string;
  low_pence:      number;
  high_pence:     number;
  citation_text:  string;
  source_url:     string;
  excludes_notes: string | null;
};

type EstimateResult = {
  ok:                  boolean;
  total_low_pence:     number;
  total_high_pence:    number;
  render_area_m2:      number;
  region_display:      string | null;
  region_multiplier:   number;
  region_source_url:   string | null;
  lines:               EstimateLine[];
  extras_excluded:     string[];
  confidence:          "high" | "moderate" | "low";
  finish_display:      string;
};

// ─── Opening type ontology (dropdown groups) ──────────────────────

const OPENING_TYPES: Array<{ group: string; options: Array<{ slug: string; label: string; defW: number; defH: number }> }> = [
  {
    group: "🪟 Windows",
    options: [
      { slug: "window-standard",     label: "Window (standard)",     defW: 1.2, defH: 1.2 },
      { slug: "window-large",        label: "Large window (>2m)",    defW: 2.4, defH: 1.4 },
      { slug: "window-bay",          label: "Bay window (protrudes)",defW: 2.4, defH: 1.5 },
      { slug: "window-bow",          label: "Bow window (curved)",   defW: 2.4, defH: 1.5 },
      { slug: "window-dormer",       label: "Dormer window",         defW: 1.5, defH: 1.2 },
      { slug: "window-full-height",  label: "Full-height / picture", defW: 2.4, defH: 2.4 },
      { slug: "window-round",        label: "Round / porthole",      defW: 0.6, defH: 0.6 }
    ]
  },
  {
    group: "🚪 Doors",
    options: [
      { slug: "door-single",         label: "Front door (single)",   defW: 0.83, defH: 2.03 },
      { slug: "door-double",         label: "Double front door",     defW: 1.66, defH: 2.03 },
      { slug: "door-french",         label: "French doors",          defW: 1.8,  defH: 2.03 },
      { slug: "door-patio-sliding",  label: "Sliding patio doors",   defW: 2.4,  defH: 2.03 },
      { slug: "door-bifold",         label: "Bi-fold doors",         defW: 3.0,  defH: 2.03 },
      { slug: "door-side",           label: "Side / utility door",   defW: 0.76, defH: 2.03 },
      { slug: "door-garage-single",  label: "Garage door (single)",  defW: 2.13, defH: 2.13 },
      { slug: "door-garage-double",  label: "Garage door (double)",  defW: 4.27, defH: 2.13 },
      { slug: "door-stable",         label: "Stable door (split)",   defW: 0.83, defH: 2.03 }
    ]
  },
  {
    group: "💨 Vents + fittings",
    options: [
      { slug: "vent-air-brick",      label: "Air brick / wall vent", defW: 0.22, defH: 0.15 },
      { slug: "vent-boiler-flue",    label: "Boiler flue",           defW: 0.15, defH: 0.15 },
      { slug: "vent-extractor",      label: "Extractor fan grille",  defW: 0.15, defH: 0.15 },
      { slug: "fitting-meter-gas",   label: "Gas meter box",         defW: 0.45, defH: 0.60 },
      { slug: "fitting-meter-elec",  label: "Electric meter box",    defW: 0.45, defH: 0.60 },
      { slug: "fitting-cable",       label: "Cable entry / EV",      defW: 0.20, defH: 0.20 },
      { slug: "fitting-cabinet",     label: "Utility cabinet",       defW: 0.60, defH: 0.80 }
    ]
  }
];
const CUSTOM_OPTION = { slug: "custom", label: "Something else — custom", defW: 0.5, defH: 0.5 };

// ─── Elevation defaults per house-type preset ─────────────────────

const HOUSE_PRESETS: Record<string, { label: string; elevations: Elevation[] }> = {
  "semi-detached-3bed": {
    label: "Semi-detached (3-bed)",
    elevations: [
      { name: "Front",     width_m: 6, height_m: 5.4, gable_rise_m: 0,   openings: [
        { type_slug: "window-standard", label: "Ground-floor window", width_m: 1.2, height_m: 1.2, count: 2 },
        { type_slug: "window-standard", label: "First-floor window",  width_m: 1.2, height_m: 1.2, count: 2 },
        { type_slug: "door-single",     label: "Front door",          width_m: 0.83, height_m: 2.03, count: 1 }
      ]},
      { name: "Rear",      width_m: 6, height_m: 5.4, gable_rise_m: 0,   openings: [
        { type_slug: "window-standard",         label: "Kitchen + bathroom windows", width_m: 1.2, height_m: 1.2, count: 3 },
        { type_slug: "door-patio-sliding",      label: "Patio door",                 width_m: 2.4, height_m: 2.03, count: 1 }
      ]},
      { name: "Side gable",width_m: 6, height_m: 5.4, gable_rise_m: 2.5, openings: [] }
    ]
  },
  "detached-3bed": {
    label: "Detached (3-bed)",
    elevations: [
      { name: "Front",         width_m: 8,  height_m: 5.4, gable_rise_m: 0,   openings: [
        { type_slug: "window-standard", label: "Ground-floor window", width_m: 1.5, height_m: 1.2, count: 2 },
        { type_slug: "window-standard", label: "First-floor window",  width_m: 1.2, height_m: 1.2, count: 3 },
        { type_slug: "door-single",     label: "Front door",          width_m: 0.83, height_m: 2.03, count: 1 }
      ]},
      { name: "Rear",          width_m: 8,  height_m: 5.4, gable_rise_m: 0,   openings: [
        { type_slug: "window-standard",    label: "Kitchen + bathroom", width_m: 1.2, height_m: 1.2, count: 3 },
        { type_slug: "door-patio-sliding", label: "Patio door",         width_m: 2.4, height_m: 2.03, count: 1 }
      ]},
      { name: "Left gable",    width_m: 8,  height_m: 5.4, gable_rise_m: 2.8, openings: [
        { type_slug: "window-standard", label: "Side window", width_m: 1.0, height_m: 1.2, count: 2 }
      ]},
      { name: "Right gable",   width_m: 8,  height_m: 5.4, gable_rise_m: 2.8, openings: [
        { type_slug: "window-standard", label: "Side window", width_m: 1.0, height_m: 1.2, count: 2 }
      ]}
    ]
  },
  "terraced-2bed": {
    label: "Mid-terrace (2-bed)",
    elevations: [
      { name: "Front", width_m: 5, height_m: 5.4, gable_rise_m: 0, openings: [
        { type_slug: "window-standard", label: "Ground + first-floor", width_m: 1.2, height_m: 1.2, count: 2 },
        { type_slug: "door-single",     label: "Front door",           width_m: 0.83, height_m: 2.03, count: 1 }
      ]},
      { name: "Rear",  width_m: 5, height_m: 5.4, gable_rise_m: 0, openings: [
        { type_slug: "window-standard", label: "Kitchen + bathroom",   width_m: 1.2, height_m: 1.2, count: 2 },
        { type_slug: "door-single",     label: "Back door",            width_m: 0.83, height_m: 2.03, count: 1 }
      ]}
    ]
  },
  "bungalow": {
    label: "Bungalow",
    elevations: [
      { name: "Front", width_m: 10, height_m: 2.7, gable_rise_m: 0, openings: [
        { type_slug: "window-standard", label: "Front windows", width_m: 1.5, height_m: 1.2, count: 3 },
        { type_slug: "door-single",     label: "Front door",    width_m: 0.83, height_m: 2.03, count: 1 }
      ]},
      { name: "Rear",  width_m: 10, height_m: 2.7, gable_rise_m: 0, openings: [
        { type_slug: "window-standard", label: "Back windows",  width_m: 1.5, height_m: 1.2, count: 3 },
        { type_slug: "door-patio-sliding", label: "Patio door", width_m: 2.4, height_m: 2.03, count: 1 }
      ]},
      { name: "Left side",  width_m: 8, height_m: 2.7, gable_rise_m: 2.0, openings: [] },
      { name: "Right side", width_m: 8, height_m: 2.7, gable_rise_m: 2.0, openings: [] }
    ]
  },
  "single-wall": {
    label: "Just one wall / feature",
    elevations: [
      { name: "Wall", width_m: 6, height_m: 3.0, gable_rise_m: 0, openings: [] }
    ]
  }
};

// ─── Finishes with visual chooser ─────────────────────────────────

const FINISH_OPTIONS: Array<{ slug: string; label: string; note: string; premium?: boolean }> = [
  { slug: "stone-effect",  label: "Stone-effect (ashlar)",           note: "Carved to imitate natural stone blocks",   premium: true },
  { slug: "brick-effect",  label: "Brick-effect",                    note: "Carved to imitate brick courses",           premium: true },
  { slug: "rock-face",     label: "Rock-face",                       note: "Deep-textured natural stone-face look" },
  { slug: "monocouche",    label: "Monocouche",                      note: "Modern through-coloured cement render — clean, uniform" },
  { slug: "silicone",      label: "Silicone",                        note: "Self-cleaning, breathable, premium modern" },
  { slug: "acrylic",       label: "Acrylic",                         note: "Flexible modern render, wide colour range" },
  { slug: "lime",          label: "Lime (heritage)",                 note: "For older / listed / pre-1919 buildings" },
  { slug: "pebble-dash",   label: "Pebble dash",                     note: "Classic thrown pebble finish" },
  { slug: "roughcast",     label: "Roughcast (Scottish harling)",    note: "Traditional wet-thrown aggregate" },
  { slug: "tyrolean",      label: "Tyrolean",                        note: "Machine-sprayed stippled finish" }
];

// ─── Wizard state ─────────────────────────────────────────────────

type Step = "guide" | "postcode" | "walls" | "generating" | "result";

export function WizardClient() {
  const [step, setStep]                 = useState<Step>("guide");
  const [postcode, setPostcode]         = useState("");
  const [housePreset, setHousePreset]   = useState<keyof typeof HOUSE_PRESETS>("semi-detached-3bed");
  const [finish, setFinish]             = useState("stone-effect");
  const [elevations, setElevations]     = useState<Elevation[]>(HOUSE_PRESETS["semi-detached-3bed"].elevations);
  const [busy, setBusy]                 = useState(false);
  const [error, setError]               = useState<string | null>(null);
  const [result, setResult]             = useState<EstimateResult | null>(null);

  function pickPreset(key: keyof typeof HOUSE_PRESETS) {
    setHousePreset(key);
    // Deep clone the preset so edits don't mutate it
    setElevations(JSON.parse(JSON.stringify(HOUSE_PRESETS[key].elevations)));
  }

  async function generate() {
    setBusy(true); setError(null); setStep("generating");
    try {
      const res  = await fetch("/api/plan/stone-effect-render/estimate", {
        method:  "POST",
        headers: { "Content-Type": "application/json" },
        body:    JSON.stringify({ postcode, finish, elevations })
      });
      const json = await res.json();
      if (!json.ok) { setError(json.error ?? "Something went wrong"); setStep("walls"); setBusy(false); return; }
      setResult(json);
      setStep("result");
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
      setStep("walls");
    } finally {
      setBusy(false);
    }
  }

  return (
    <>
      {/* Progress crumbs */}
      <ol className="mb-4 flex items-center gap-1 text-[10.5px] font-black uppercase tracking-wider text-neutral-500">
        {["guide","postcode","walls","result"].map((s, i) => (
          <li key={s} className="flex items-center gap-1">
            <span className={step === s ? "text-neutral-900" : ""}>
              {i + 1}. {s === "guide" ? "How to measure" : s === "postcode" ? "Postcode" : s === "walls" ? "Wall details" : "Estimate"}
            </span>
            {i < 3 && <span aria-hidden>→</span>}
          </li>
        ))}
      </ol>

      {step === "guide"     && <GuideStep     onNext={() => setStep("postcode")}/>}
      {step === "postcode"  && <PostcodeStep  postcode={postcode} setPostcode={setPostcode} housePreset={housePreset} pickPreset={pickPreset} onBack={() => setStep("guide")} onNext={() => setStep("walls")}/>}
      {step === "walls"     && <WallsStep     elevations={elevations} setElevations={setElevations} finish={finish} setFinish={setFinish} error={error} onBack={() => setStep("postcode")} onGenerate={generate} busy={busy}/>}
      {step === "generating"&& <GeneratingStep/>}
      {step === "result"    && result && <ResultStep result={result} onBack={() => setStep("walls")} onRestart={() => { setStep("guide"); setResult(null); }}/>}
    </>
  );
}

// ─── Step 1 · Guide ───────────────────────────────────────────────

function GuideStep({ onNext }: { onNext: () => void }) {
  const drawingUrl = "https://msdonkkechxzgagyguoe.supabase.co/storage/v1/object/public/networkers-tv-thumbnails/measure-your-house-guide.png";

  return (
    <section className="rounded-2xl border-2 bg-white p-4 shadow-sm md:p-6" style={{ borderColor: "rgba(139,69,19,0.10)" }}>
      <p className="text-[10px] font-black uppercase tracking-[0.22em]" style={{ color: "#FFB300" }}>
        Step 1 · How to measure your house
      </p>
      <h2 className="mt-1 text-[18px] font-black text-neutral-900 md:text-[22px]">
        Grab a tape measure + pen. Takes 10 minutes.
      </h2>
      <p className="mt-2 text-[13px] leading-relaxed text-neutral-700">
        Measure the full wall first, then measure the openings (windows + doors + garage doors + vents).
        Number each opening (1, 2, 3, D1, D2) so you don't confuse yourself.
      </p>

      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={drawingUrl} alt="How to measure your house — annotated diagram showing A width, B ground to eaves, C eaves to ridge for front/rear/side elevations, with window + door dimensions"
        className="mt-4 h-auto w-full rounded-lg border object-contain" style={{ borderColor: "rgba(139,69,19,0.10)" }} loading="lazy"/>

      <p className="mt-3 text-[11.5px] text-neutral-600">
        <span className="font-black">Tip:</span> Can't reach the top? Use your front door (2.03m tall) as a scale — take a photo from the street and estimate proportions.
      </p>

      <button type="button" onClick={onNext}
        className="mt-5 inline-flex h-11 items-center gap-1.5 rounded-lg px-5 text-[12.5px] font-black uppercase tracking-wider text-neutral-900 shadow-sm active:scale-[0.97]"
        style={{ backgroundColor: "#FFB300" }}>
        I've got my numbers — continue <ArrowRight size={13}/>
      </button>
    </section>
  );
}

// ─── Step 2 · Postcode + house type ───────────────────────────────

function PostcodeStep({ postcode, setPostcode, housePreset, pickPreset, onBack, onNext }: {
  postcode: string;  setPostcode: (s: string) => void;
  housePreset: keyof typeof HOUSE_PRESETS;
  pickPreset: (k: keyof typeof HOUSE_PRESETS) => void;
  onBack: () => void;  onNext: () => void;
}) {
  return (
    <section className="rounded-2xl border-2 bg-white p-4 shadow-sm md:p-6" style={{ borderColor: "rgba(139,69,19,0.10)" }}>
      <p className="text-[10px] font-black uppercase tracking-[0.22em]" style={{ color: "#FFB300" }}>Step 2 · Location + house type</p>
      <h2 className="mt-1 text-[18px] font-black text-neutral-900 md:text-[22px]">Where + what kind of house?</h2>

      <label className="mt-4 block">
        <span className="inline-flex items-center gap-1 text-[10.5px] font-black uppercase tracking-wider text-neutral-500">
          <MapPin size={11}/> UK postcode (for regional pricing)
        </span>
        <input type="text" value={postcode} onChange={(e) => setPostcode(e.target.value.toUpperCase())}
          placeholder="e.g. M1 1AA or SW1A"
          className="mt-1 h-11 w-full max-w-xs rounded-lg border-2 bg-white px-3 text-[14px] font-black tabular-nums text-neutral-900"
          style={{ borderColor: "rgba(139,69,19,0.20)" }} maxLength={10}/>
        <span className="mt-1 block text-[10.5px] text-neutral-500">Rates adjust for your region using ONS Building Cost Index data.</span>
      </label>

      <div className="mt-5">
        <p className="inline-flex items-center gap-1 text-[10.5px] font-black uppercase tracking-wider text-neutral-500">
          <HomeIcon size={11}/> House type (auto-fills typical measurements)
        </p>
        <ul className="mt-2 grid grid-cols-1 gap-2 md:grid-cols-2 lg:grid-cols-3">
          {(Object.keys(HOUSE_PRESETS) as Array<keyof typeof HOUSE_PRESETS>).map((k) => (
            <li key={k}>
              <button type="button" onClick={() => pickPreset(k)}
                className="flex w-full items-center justify-between rounded-xl border-2 px-3 py-3 text-left transition"
                style={housePreset === k
                  ? { backgroundColor: "#FFB300", borderColor: "#FFB300", color: "#0A0A0A" }
                  : { backgroundColor: "#FFFFFF", borderColor: "rgba(139,69,19,0.20)", color: "#171717" }}>
                <span className="text-[12.5px] font-black">{HOUSE_PRESETS[k].label}</span>
                <span className="text-[10.5px] font-black uppercase tracking-wider opacity-70">{HOUSE_PRESETS[k].elevations.length} walls</span>
              </button>
            </li>
          ))}
        </ul>
      </div>

      <div className="mt-5 flex flex-wrap gap-2">
        <button type="button" onClick={onBack} className="inline-flex h-11 items-center gap-1 rounded-lg border-2 bg-white px-4 text-[11.5px] font-black uppercase tracking-wider text-neutral-800" style={{ borderColor: "rgba(139,69,19,0.20)" }}>
          <ArrowLeft size={12}/> Back
        </button>
        <button type="button" onClick={onNext} disabled={postcode.trim().length < 2}
          className="inline-flex h-11 items-center gap-1.5 rounded-lg px-5 text-[12.5px] font-black uppercase tracking-wider text-neutral-900 shadow-sm active:scale-[0.97] disabled:opacity-50"
          style={{ backgroundColor: "#FFB300" }}>
          Continue <ArrowRight size={13}/>
        </button>
      </div>
    </section>
  );
}

// ─── Step 3 · Walls + openings ────────────────────────────────────

function WallsStep({ elevations, setElevations, finish, setFinish, error, onBack, onGenerate, busy }: {
  elevations: Elevation[];
  setElevations: (e: Elevation[]) => void;
  finish: string; setFinish: (s: string) => void;
  error: string | null;
  onBack: () => void; onGenerate: () => void; busy: boolean;
}) {
  const totalGross = useMemo(() => {
    return elevations.reduce((acc, e) => acc + (e.width_m * e.height_m) + (e.gable_rise_m > 0 ? 0.5 * e.width_m * e.gable_rise_m : 0), 0);
  }, [elevations]);
  const totalOpenings = useMemo(() => {
    return elevations.reduce((acc, e) => acc + e.openings.reduce((s, o) => s + (o.width_m * o.height_m * o.count), 0), 0);
  }, [elevations]);
  const netArea = Math.max(0, totalGross - totalOpenings);

  function updateElevation(idx: number, fn: (e: Elevation) => Elevation) {
    setElevations(elevations.map((e, i) => i === idx ? fn(e) : e));
  }
  function addOpening(idx: number) {
    updateElevation(idx, (e) => ({ ...e, openings: [...e.openings, { type_slug: "window-standard", label: "Window", width_m: 1.2, height_m: 1.2, count: 1 }] }));
  }
  function removeOpening(elevIdx: number, opIdx: number) {
    updateElevation(elevIdx, (e) => ({ ...e, openings: e.openings.filter((_, i) => i !== opIdx) }));
  }
  function changeOpeningType(elevIdx: number, opIdx: number, typeSlug: string) {
    const flat = OPENING_TYPES.flatMap(g => g.options);
    const def = flat.find(o => o.slug === typeSlug) ?? CUSTOM_OPTION;
    updateElevation(elevIdx, (e) => ({
      ...e,
      openings: e.openings.map((o, i) => i === opIdx ? { ...o, type_slug: def.slug, label: def.label, width_m: def.defW, height_m: def.defH } : o)
    }));
  }

  return (
    <section className="space-y-4">
      {/* Finish selector */}
      <div className="rounded-2xl border-2 bg-white p-4 shadow-sm md:p-5" style={{ borderColor: "rgba(139,69,19,0.10)" }}>
        <p className="text-[10px] font-black uppercase tracking-[0.22em]" style={{ color: "#FFB300" }}>Step 3a · Which finish?</p>
        <h2 className="mt-1 text-[16px] font-black text-neutral-900">Choose your look</h2>
        <ul className="mt-3 grid grid-cols-1 gap-2 md:grid-cols-2 lg:grid-cols-3">
          {FINISH_OPTIONS.map((f) => (
            <li key={f.slug}>
              <button type="button" onClick={() => setFinish(f.slug)}
                className="flex w-full items-start justify-between gap-2 rounded-xl border-2 p-3 text-left transition"
                style={finish === f.slug
                  ? { backgroundColor: "#0A0A0A", borderColor: "#FFB300", color: "#FFFFFF" }
                  : { backgroundColor: "#FFFFFF", borderColor: "rgba(139,69,19,0.20)", color: "#171717" }}>
                <div>
                  <p className="text-[12.5px] font-black">{f.label}</p>
                  <p className="mt-0.5 text-[11px] opacity-80">{f.note}</p>
                </div>
                {f.premium && (
                  <span className="shrink-0 rounded-full px-1.5 py-0.5 text-[9px] font-black uppercase tracking-wider" style={{ backgroundColor: "#FFB300", color: "#0A0A0A" }}>Premium</span>
                )}
              </button>
            </li>
          ))}
        </ul>
      </div>

      {/* Elevation editors */}
      {elevations.map((el, idx) => (
        <div key={idx} className="rounded-2xl border-2 bg-white p-4 shadow-sm md:p-5" style={{ borderColor: "rgba(139,69,19,0.10)" }}>
          <div className="flex flex-wrap items-baseline justify-between gap-2">
            <p className="text-[10px] font-black uppercase tracking-[0.22em]" style={{ color: "#FFB300" }}>
              Step 3b · {el.name}
            </p>
            <p className="text-[11px] font-black uppercase tracking-wider text-neutral-500 tabular-nums">
              Gross: {(el.width_m * el.height_m + (el.gable_rise_m > 0 ? 0.5 * el.width_m * el.gable_rise_m : 0)).toFixed(2)} m²
            </p>
          </div>

          <div className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-3">
            <NumberField label="A · Width (m)"       value={el.width_m}      onChange={(v) => updateElevation(idx, (e) => ({ ...e, width_m: v }))} min={0.5} max={30} step={0.1}/>
            <NumberField label="B · Ground to eaves (m)" value={el.height_m} onChange={(v) => updateElevation(idx, (e) => ({ ...e, height_m: v }))} min={0.5} max={20} step={0.1}/>
            <NumberField label="C · Eaves to ridge (m)"  value={el.gable_rise_m} onChange={(v) => updateElevation(idx, (e) => ({ ...e, gable_rise_m: v }))} min={0}  max={10} step={0.1}/>
          </div>

          <div className="mt-4">
            <p className="text-[10.5px] font-black uppercase tracking-wider text-neutral-500">Openings (to subtract)</p>
            {el.openings.length === 0 && (
              <p className="mt-1 text-[11px] text-neutral-500">No openings — the whole wall gets rendered.</p>
            )}
            <ul className="mt-2 space-y-2">
              {el.openings.map((op, opIdx) => (
                <li key={opIdx} className="rounded-lg border-2 p-2" style={{ borderColor: "rgba(139,69,19,0.10)" }}>
                  <div className="flex flex-wrap items-end gap-2">
                    <label className="min-w-0 flex-1">
                      <span className="text-[9.5px] font-black uppercase tracking-wider text-neutral-500">Type</span>
                      <select value={op.type_slug} onChange={(e) => changeOpeningType(idx, opIdx, e.target.value)}
                        className="mt-0.5 h-9 w-full rounded-lg border-2 bg-white px-2 text-[12px] font-black text-neutral-900"
                        style={{ borderColor: "rgba(139,69,19,0.20)" }}>
                        {OPENING_TYPES.map((grp) => (
                          <optgroup key={grp.group} label={grp.group}>
                            {grp.options.map((o) => (<option key={o.slug} value={o.slug}>{o.label}</option>))}
                          </optgroup>
                        ))}
                        <option value={CUSTOM_OPTION.slug}>{CUSTOM_OPTION.label}</option>
                      </select>
                    </label>
                    <NumberField compact label="Width (m)"  value={op.width_m}  onChange={(v) => updateElevation(idx, (e) => ({ ...e, openings: e.openings.map((x, i) => i === opIdx ? { ...x, width_m: v } : x) }))} min={0.1} max={10} step={0.05}/>
                    <NumberField compact label="Height (m)" value={op.height_m} onChange={(v) => updateElevation(idx, (e) => ({ ...e, openings: e.openings.map((x, i) => i === opIdx ? { ...x, height_m: v } : x) }))} min={0.1} max={10} step={0.05}/>
                    <NumberField compact label="Count"      value={op.count}    onChange={(v) => updateElevation(idx, (e) => ({ ...e, openings: e.openings.map((x, i) => i === opIdx ? { ...x, count: Math.max(1, Math.floor(v)) } : x) }))} min={1} max={20} step={1}/>
                    <button type="button" onClick={() => removeOpening(idx, opIdx)} aria-label="Remove opening" className="inline-flex h-9 w-9 items-center justify-center rounded-lg border-2 text-red-700 hover:bg-red-50" style={{ borderColor: "rgba(220,38,38,0.30)" }}>
                      <Trash2 size={13}/>
                    </button>
                  </div>
                </li>
              ))}
            </ul>
            <button type="button" onClick={() => addOpening(idx)}
              className="mt-2 inline-flex h-9 items-center gap-1 rounded-lg border-2 bg-white px-3 text-[11px] font-black uppercase tracking-wider text-neutral-800 hover:-translate-y-0.5 transition"
              style={{ borderColor: "rgba(139,69,19,0.20)" }}>
              <Plus size={11}/> Add window / door / vent
            </button>
          </div>
        </div>
      ))}

      {/* Running totals + generate button */}
      <div className="rounded-2xl border-2 p-4 shadow-sm md:p-5" style={{ borderColor: "#0A0A0A", backgroundColor: "#0A0A0A", color: "#FFFFFF" }}>
        <div className="grid grid-cols-3 gap-3">
          <div>
            <p className="text-[10px] font-black uppercase tracking-wider" style={{ color: "#FFB300" }}>Gross wall area</p>
            <p className="mt-0.5 text-[16px] font-black tabular-nums">{totalGross.toFixed(1)} m²</p>
          </div>
          <div>
            <p className="text-[10px] font-black uppercase tracking-wider" style={{ color: "#FFB300" }}>Openings</p>
            <p className="mt-0.5 text-[16px] font-black tabular-nums">−{totalOpenings.toFixed(1)} m²</p>
          </div>
          <div>
            <p className="text-[10px] font-black uppercase tracking-wider" style={{ color: "#FFB300" }}>Net render area</p>
            <p className="mt-0.5 text-[16px] font-black tabular-nums">{netArea.toFixed(1)} m²</p>
          </div>
        </div>

        {error && (
          <p className="mt-3 flex items-center gap-1 rounded-lg bg-red-900/40 px-2 py-1.5 text-[11px] font-black text-red-100">
            <AlertTriangle size={11}/> {error}
          </p>
        )}

        <div className="mt-4 flex flex-wrap gap-2">
          <button type="button" onClick={onBack} className="inline-flex h-11 items-center gap-1 rounded-lg border-2 px-4 text-[11.5px] font-black uppercase tracking-wider text-white" style={{ borderColor: "rgba(255,255,255,0.30)" }}>
            <ArrowLeft size={12}/> Back
          </button>
          <button type="button" onClick={onGenerate} disabled={busy || netArea <= 0}
            className="inline-flex h-11 items-center gap-1.5 rounded-lg px-5 text-[12.5px] font-black uppercase tracking-wider text-neutral-900 shadow-sm active:scale-[0.97] disabled:opacity-50"
            style={{ backgroundColor: "#FFB300" }}>
            {busy ? <Loader2 size={14} className="animate-spin"/> : <Sparkles size={14} strokeWidth={2.6}/>}
            Get my estimate <ArrowRight size={13}/>
          </button>
        </div>
      </div>
    </section>
  );
}

// ─── Step 4 · Generating ──────────────────────────────────────────

function GeneratingStep() {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-center">
      <Loader2 size={32} className="animate-spin text-neutral-500"/>
      <p className="mt-3 text-[13px] font-black text-neutral-900">Building your estimate...</p>
      <p className="mt-1 text-[11px] text-neutral-600">Applying UK trade rates + your regional multiplier</p>
    </div>
  );
}

// ─── Step 5 · Result ──────────────────────────────────────────────

function ResultStep({ result, onBack, onRestart }: {
  result: EstimateResult;
  onBack: () => void;
  onRestart: () => void;
}) {
  const fmt = (p: number) => "£" + Math.round(p / 100).toLocaleString("en-GB");

  return (
    <section className="space-y-4">
      {/* Headline */}
      <div className="rounded-2xl border-2 p-5 shadow-sm md:p-6" style={{ borderColor: "#0A0A0A", backgroundColor: "#0A0A0A", color: "#FFFFFF" }}>
        <p className="text-[10px] font-black uppercase tracking-[0.28em]" style={{ color: "#FFB300" }}>
          Estimated range for {result.finish_display} · {result.render_area_m2.toFixed(1)} m²
        </p>
        <p className="mt-2 text-[32px] font-black leading-none tabular-nums md:text-[44px]">
          {fmt(result.total_low_pence)} – {fmt(result.total_high_pence)}
        </p>
        <p className="mt-2 text-[11.5px] leading-relaxed" style={{ color: "rgba(255,255,255,0.75)" }}>
          Budget for the higher figure to be safe. Actual quotes vary by site + trade + product choice.
          <br/>
          {result.region_display && (
            <>Regional multiplier applied: <span className="font-black text-white">{result.region_multiplier.toFixed(2)}× {result.region_display}</span> · </>
          )}
          Confidence: <span className="font-black text-white">{result.confidence}</span>
        </p>
      </div>

      {/* Line items with citations */}
      <div className="rounded-2xl border-2 bg-white p-4 shadow-sm md:p-5" style={{ borderColor: "rgba(139,69,19,0.10)" }}>
        <p className="inline-flex items-center gap-1 text-[10px] font-black uppercase tracking-[0.22em] text-neutral-500">
          <ScrollText size={11}/> Line breakdown · every rate cited
        </p>
        <ul className="mt-3 space-y-2">
          {result.lines.map((l) => (
            <li key={l.line_item_slug} className="border-b py-2 last:border-b-0" style={{ borderColor: "rgba(0,0,0,0.06)" }}>
              <div className="flex flex-wrap items-baseline justify-between gap-2">
                <p className="text-[13px] font-black text-neutral-900">{l.display_name}</p>
                <p className="tabular-nums text-[13px] font-black text-neutral-900">
                  {fmt(l.low_pence)} – {fmt(l.high_pence)}
                </p>
              </div>
              <p className="text-[10.5px] font-black uppercase tracking-wider text-neutral-500 tabular-nums">
                {l.quantity} {l.unit}
              </p>
              <p className="mt-0.5 text-[10.5px] italic text-neutral-500">
                {l.citation_text} · <a href={l.source_url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-0.5 text-neutral-700 underline underline-offset-2">source <ExternalLink size={8}/></a>
              </p>
              {l.excludes_notes && (
                <p className="mt-0.5 text-[10.5px] text-neutral-500">Excludes: {l.excludes_notes}</p>
              )}
            </li>
          ))}
        </ul>
      </div>

      {/* Extras excluded — bold callout */}
      <div className="rounded-2xl border-2 p-4 shadow-sm md:p-5" style={{ borderColor: "#F59E0B", backgroundColor: "#FFFBEB" }}>
        <p className="inline-flex items-center gap-1 text-[11px] font-black uppercase tracking-wider text-amber-800">
          <AlertTriangle size={12}/> This estimate is the render work only
        </p>
        <p className="mt-1 text-[12px] leading-relaxed text-amber-900">
          The following are <span className="font-black">always charged separately</span> by the trade and vary per site + region. Your trade will confirm exact prices after inspecting the site.
        </p>
        <ul className="mt-2 grid grid-cols-1 gap-1 md:grid-cols-2">
          {result.extras_excluded.map((e, i) => (
            <li key={i} className="text-[11.5px] text-amber-900">· {e}</li>
          ))}
        </ul>
      </div>

      {/* CTA */}
      <div className="rounded-2xl border-2 p-5 shadow-sm md:p-6" style={{ borderColor: "#FFB300", backgroundColor: "#FFFDF6" }}>
        <p className="text-[10px] font-black uppercase tracking-[0.22em] text-neutral-500">Next step</p>
        <h3 className="mt-1 text-[16px] font-black text-neutral-900 md:text-[18px]">Get 3 quotes from verified decorative renderers</h3>
        <p className="mt-1 text-[12px] text-neutral-700">Trades will visit, inspect, and give you a firm price — usually within your estimated range.</p>
        <div className="mt-3 flex flex-wrap gap-2">
          <Link href="/trades/renderer" className="inline-flex h-10 items-center gap-1 rounded-lg px-4 text-[11.5px] font-black uppercase tracking-wider text-neutral-900 shadow-sm active:scale-[0.97]" style={{ backgroundColor: "#FFB300" }}>
            Find local renderers <ArrowRight size={12}/>
          </Link>
          <Link href="/videos" className="inline-flex h-10 items-center gap-1 rounded-lg border-2 bg-white px-4 text-[11.5px] font-black uppercase tracking-wider text-neutral-800" style={{ borderColor: "rgba(139,69,19,0.20)" }}>
            <BookOpen size={12}/> Learn about the finishes
          </Link>
        </div>
      </div>

      {/* Wizard controls */}
      <div className="flex flex-wrap gap-2">
        <button type="button" onClick={onBack} className="inline-flex h-10 items-center gap-1 rounded-lg border-2 bg-white px-4 text-[11px] font-black uppercase tracking-wider text-neutral-800" style={{ borderColor: "rgba(139,69,19,0.20)" }}>
          <ArrowLeft size={11}/> Adjust wall details
        </button>
        <button type="button" onClick={onRestart} className="inline-flex h-10 items-center gap-1 rounded-lg border-2 bg-white px-4 text-[11px] font-black uppercase tracking-wider text-neutral-800" style={{ borderColor: "rgba(139,69,19,0.20)" }}>
          Start over
        </button>
      </div>

      {/* Trust footer */}
      <p className="text-[10.5px] text-neutral-500">
        <Info size={10} className="inline mb-0.5"/> Rates sourced from published UK trade guidance (Spon's Price Book, FMB, Checkatrade, FPDC, Historic England, ONS BCI). Regional multipliers from ONS Q3 2026. Every trade quotes differently — always get 3 quotes.
      </p>
    </section>
  );
}

// ─── Reusable field primitive ─────────────────────────────────────

function NumberField({ label, value, onChange, min, max, step, compact = false }: {
  label: string; value: number; onChange: (v: number) => void;
  min: number; max: number; step: number; compact?: boolean;
}) {
  return (
    <label className={compact ? "w-24" : "block"}>
      <span className="text-[9.5px] font-black uppercase tracking-wider text-neutral-500">{label}</span>
      <input type="number" value={value} min={min} max={max} step={step}
        onChange={(e) => onChange(Number(e.target.value) || 0)}
        className={`mt-0.5 h-9 w-full rounded-lg border-2 bg-white px-2 text-[13px] font-black tabular-nums text-neutral-900`}
        style={{ borderColor: "rgba(139,69,19,0.20)" }}/>
    </label>
  );
}
