BEGIN;
ALTER TABLE nex.accommodation_business ADD CONSTRAINT accommodation_business_cycle_run_id_fkey FOREIGN KEY (cycle_run_id) REFERENCES nex.worker_cycle_run(id) ON DELETE SET NULL;
ALTER TABLE nex.accommodation_business_field_provenance ADD CONSTRAINT accommodation_business_field_provenance_business_ref_fkey FOREIGN KEY (business_ref) REFERENCES nex.accommodation_business(public_listing_ref) ON DELETE CASCADE;
ALTER TABLE nex.accommodation_business_field_provenance ADD CONSTRAINT accommodation_business_field_provenance_cycle_run_id_fkey FOREIGN KEY (cycle_run_id) REFERENCES nex.worker_cycle_run(id) ON DELETE SET NULL;
ALTER TABLE nex.accommodation_business_source_snapshot ADD CONSTRAINT accommodation_business_source_snapshot_business_ref_fkey FOREIGN KEY (business_ref) REFERENCES nex.accommodation_business(public_listing_ref) ON DELETE CASCADE;
ALTER TABLE nex.accommodation_business_source_snapshot ADD CONSTRAINT accommodation_business_source_snapshot_cycle_run_id_fkey FOREIGN KEY (cycle_run_id) REFERENCES nex.worker_cycle_run(id) ON DELETE SET NULL;
ALTER TABLE nex.accommodation_enrichment_evidence ADD CONSTRAINT accommodation_enrichment_evidence_business_ref_fkey FOREIGN KEY (business_ref) REFERENCES nex.accommodation_business(public_listing_ref) ON DELETE CASCADE;
ALTER TABLE nex.accommodation_enrichment_evidence ADD CONSTRAINT accommodation_enrichment_evidence_cycle_run_id_fkey FOREIGN KEY (cycle_run_id) REFERENCES nex.worker_cycle_run(id) ON DELETE SET NULL;
ALTER TABLE nex.alert_dispatches ADD CONSTRAINT alert_dispatches_alert_id_fkey FOREIGN KEY (alert_id) REFERENCES nex.alerts(alert_id) ON DELETE CASCADE;
ALTER TABLE nex.alerts ADD CONSTRAINT alerts_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES nex.alert_rules(rule_id) ON DELETE RESTRICT;
ALTER TABLE nex.analytics_events ADD CONSTRAINT analytics_events_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES nex.campaigns(campaign_id) ON DELETE SET NULL;
ALTER TABLE nex.attributions ADD CONSTRAINT attributions_conversion_id_fkey FOREIGN KEY (conversion_id) REFERENCES nex.conversion_events(conversion_id) ON DELETE CASCADE;
ALTER TABLE nex.bike_rental_listing ADD CONSTRAINT bike_rental_listing_preferred_bike_slug_fkey FOREIGN KEY (preferred_bike_slug) REFERENCES nex.bike_model(slug);
ALTER TABLE nex.brain_english_practice ADD CONSTRAINT brain_english_practice_lesson_slug_fkey FOREIGN KEY (lesson_slug) REFERENCES nex.brain_english_lesson(lesson_slug);
ALTER TABLE nex.brain_english_progress ADD CONSTRAINT brain_english_progress_grammar_id_fkey FOREIGN KEY (grammar_id) REFERENCES nex.brain_english_grammar(grammar_id) ON DELETE CASCADE;
ALTER TABLE nex.brain_english_progress ADD CONSTRAINT brain_english_progress_lesson_slug_fkey FOREIGN KEY (lesson_slug) REFERENCES nex.brain_english_lesson(lesson_slug) ON DELETE CASCADE;
ALTER TABLE nex.brain_english_progress ADD CONSTRAINT brain_english_progress_practice_id_fkey FOREIGN KEY (practice_id) REFERENCES nex.brain_english_practice(practice_id) ON DELETE CASCADE;
ALTER TABLE nex.brain_english_progress ADD CONSTRAINT brain_english_progress_vocab_id_fkey FOREIGN KEY (vocab_id) REFERENCES nex.brain_english_vocabulary(vocab_id) ON DELETE CASCADE;
ALTER TABLE nex.brain_user_saved_facts ADD CONSTRAINT brain_user_saved_facts_fact_id_fkey FOREIGN KEY (fact_id) REFERENCES nex.brain_did_you_know_indonesia(fact_id) ON DELETE CASCADE;
ALTER TABLE nex.business_image ADD CONSTRAINT business_image_cycle_run_id_fkey FOREIGN KEY (cycle_run_id) REFERENCES nex.worker_cycle_run(id);
ALTER TABLE nex.campaign_recipients ADD CONSTRAINT campaign_recipients_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES nex.campaigns(campaign_id) ON DELETE CASCADE;
ALTER TABLE nex.campaign_segments ADD CONSTRAINT campaign_segments_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES nex.campaigns(campaign_id) ON DELETE CASCADE;
ALTER TABLE nex.campaign_segments ADD CONSTRAINT campaign_segments_segment_id_fkey FOREIGN KEY (segment_id) REFERENCES nex.contact_segments(segment_id) ON DELETE RESTRICT;
ALTER TABLE nex.campaigns ADD CONSTRAINT campaigns_template_id_fkey FOREIGN KEY (template_id) REFERENCES nex.email_templates(template_id) ON DELETE SET NULL;
ALTER TABLE nex.category_candidate ADD CONSTRAINT category_candidate_duplicate_of_registry_id_fkey FOREIGN KEY (duplicate_of_registry_id) REFERENCES nex.category_registry(id) ON DELETE SET NULL;
ALTER TABLE nex.category_candidate ADD CONSTRAINT category_candidate_proposed_cycle_run_id_fkey FOREIGN KEY (proposed_cycle_run_id) REFERENCES nex.worker_cycle_run(id) ON DELETE SET NULL;
ALTER TABLE nex.category_candidate ADD CONSTRAINT category_candidate_superseded_by_candidate_id_fkey FOREIGN KEY (superseded_by_candidate_id) REFERENCES nex.category_candidate(id) ON DELETE SET NULL;
ALTER TABLE nex.category_candidate_calibration_annotation ADD CONSTRAINT category_candidate_calibration_annotation_against_score_id_fkey FOREIGN KEY (against_score_id) REFERENCES nex.category_candidate_score(id) ON DELETE SET NULL;
ALTER TABLE nex.category_candidate_calibration_annotation ADD CONSTRAINT category_candidate_calibration_annotation_candidate_id_fkey FOREIGN KEY (candidate_id) REFERENCES nex.category_candidate(id) ON DELETE SET NULL;
ALTER TABLE nex.category_candidate_score ADD CONSTRAINT category_candidate_score_candidate_id_fkey FOREIGN KEY (candidate_id) REFERENCES nex.category_candidate(id) ON DELETE CASCADE;
ALTER TABLE nex.category_registry ADD CONSTRAINT category_registry_origin_candidate_fkey FOREIGN KEY (origin_candidate_id) REFERENCES nex.category_candidate(id) ON DELETE SET NULL;
ALTER TABLE nex.chat_message_archive ADD CONSTRAINT chat_message_archive_event_id_fkey FOREIGN KEY (event_id) REFERENCES nex.safety_audit_event(event_id) ON DELETE CASCADE;
ALTER TABLE nex.chat_message_deletion ADD CONSTRAINT chat_message_deletion_message_id_fkey FOREIGN KEY (message_id) REFERENCES nex.chat_message(message_id);
ALTER TABLE nex.confidence_scores ADD CONSTRAINT confidence_scores_record_id_fkey FOREIGN KEY (record_id) REFERENCES nex.knowledge_records(record_id) ON DELETE CASCADE;
ALTER TABLE nex.contact_duplicate_suggestions ADD CONSTRAINT contact_duplicate_suggestions_merge_id_fkey FOREIGN KEY (merge_id) REFERENCES nex.contact_merges(merge_id);
ALTER TABLE nex.contradictions ADD CONSTRAINT contradictions_record_a_id_fkey FOREIGN KEY (record_a_id) REFERENCES nex.knowledge_records(record_id) ON DELETE CASCADE;
ALTER TABLE nex.contradictions ADD CONSTRAINT contradictions_record_b_id_fkey FOREIGN KEY (record_b_id) REFERENCES nex.knowledge_records(record_id) ON DELETE CASCADE;
ALTER TABLE nex.conv_edges ADD CONSTRAINT conv_edges_from_item_fkey FOREIGN KEY (from_item) REFERENCES nex.conv_knowledge_items(id) ON DELETE CASCADE;
ALTER TABLE nex.conv_edges ADD CONSTRAINT conv_edges_to_item_fkey FOREIGN KEY (to_item) REFERENCES nex.conv_knowledge_items(id) ON DELETE CASCADE;
ALTER TABLE nex.conv_feedback ADD CONSTRAINT conv_feedback_turn_id_fkey FOREIGN KEY (turn_id) REFERENCES nex.conv_turns(id) ON DELETE CASCADE;
ALTER TABLE nex.conv_knowledge_items ADD CONSTRAINT conv_knowledge_items_canonical_intent_fkey FOREIGN KEY (canonical_intent) REFERENCES nex.conv_intents(slug) ON UPDATE CASCADE;
ALTER TABLE nex.conv_learning_candidate ADD CONSTRAINT conv_learning_candidate_cycle_run_id_fkey FOREIGN KEY (cycle_run_id) REFERENCES nex.worker_cycle_run(id) ON DELETE CASCADE;
ALTER TABLE nex.conv_learning_candidate ADD CONSTRAINT conv_learning_candidate_promotion_target_record_id_fkey FOREIGN KEY (promotion_target_record_id) REFERENCES nex.knowledge_records(id) ON DELETE SET NULL;
ALTER TABLE nex.conv_turns ADD CONSTRAINT conv_turns_cle_cycle_run_id_fkey FOREIGN KEY (cle_cycle_run_id) REFERENCES nex.worker_cycle_run(id) ON DELETE SET NULL;
ALTER TABLE nex.conv_turns ADD CONSTRAINT conv_turns_detected_intent_fkey FOREIGN KEY (detected_intent) REFERENCES nex.conv_intents(slug) ON UPDATE CASCADE;
ALTER TABLE nex.delivery_job_attempts ADD CONSTRAINT delivery_job_attempts_job_id_fkey FOREIGN KEY (job_id) REFERENCES nex.delivery_jobs(job_id) ON DELETE CASCADE;
ALTER TABLE nex.delivery_jobs ADD CONSTRAINT delivery_jobs_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES nex.campaigns(campaign_id) ON DELETE CASCADE;
ALTER TABLE nex.deprecations ADD CONSTRAINT deprecations_record_id_fkey FOREIGN KEY (record_id) REFERENCES nex.knowledge_records(record_id) ON DELETE CASCADE;
ALTER TABLE nex.deprecations ADD CONSTRAINT deprecations_superseded_by_fkey FOREIGN KEY (superseded_by) REFERENCES nex.knowledge_records(record_id);
ALTER TABLE nex.experiment_assignments ADD CONSTRAINT experiment_assignments_experiment_id_fkey FOREIGN KEY (experiment_id) REFERENCES nex.experiments(experiment_id) ON DELETE CASCADE;
ALTER TABLE nex.experiment_assignments ADD CONSTRAINT experiment_assignments_experiment_id_variant_id_fkey FOREIGN KEY (experiment_id, variant_id) REFERENCES nex.experiment_variants(experiment_id, variant_id);
ALTER TABLE nex.experiment_variants ADD CONSTRAINT experiment_variants_experiment_id_fkey FOREIGN KEY (experiment_id) REFERENCES nex.experiments(experiment_id) ON DELETE CASCADE;
ALTER TABLE nex.experiment_variants ADD CONSTRAINT experiment_variants_target_campaign_id_fkey FOREIGN KEY (target_campaign_id) REFERENCES nex.campaigns(campaign_id) ON DELETE SET NULL;
ALTER TABLE nex.food_business ADD CONSTRAINT food_business_cycle_run_id_fkey FOREIGN KEY (cycle_run_id) REFERENCES nex.worker_cycle_run(id) ON DELETE SET NULL;
ALTER TABLE nex.food_business_field_provenance ADD CONSTRAINT food_business_field_provenance_cycle_run_id_fkey FOREIGN KEY (cycle_run_id) REFERENCES nex.worker_cycle_run(id) ON DELETE SET NULL;
ALTER TABLE nex.food_business_promotion ADD CONSTRAINT food_business_promotion_business_ref_fkey FOREIGN KEY (business_ref) REFERENCES nex.food_business(public_listing_ref) ON DELETE CASCADE;
ALTER TABLE nex.food_business_promotion ADD CONSTRAINT food_business_promotion_cycle_run_id_fkey FOREIGN KEY (cycle_run_id) REFERENCES nex.worker_cycle_run(id) ON DELETE SET NULL;
ALTER TABLE nex.food_business_promotion_audit ADD CONSTRAINT food_business_promotion_audit_business_ref_fkey FOREIGN KEY (business_ref) REFERENCES nex.food_business(public_listing_ref) ON DELETE CASCADE;
ALTER TABLE nex.food_business_promotion_audit ADD CONSTRAINT food_business_promotion_audit_cycle_run_id_fkey FOREIGN KEY (cycle_run_id) REFERENCES nex.worker_cycle_run(id) ON DELETE CASCADE;
ALTER TABLE nex.food_business_promotion_decision ADD CONSTRAINT food_business_promotion_decision_business_ref_fkey FOREIGN KEY (business_ref) REFERENCES nex.food_business(public_listing_ref) ON DELETE CASCADE;
ALTER TABLE nex.food_business_promotion_decision ADD CONSTRAINT food_business_promotion_decision_cycle_run_id_fkey FOREIGN KEY (cycle_run_id) REFERENCES nex.worker_cycle_run(id);
ALTER TABLE nex.food_business_promotion_decision ADD CONSTRAINT food_business_promotion_decision_evidence_id_fkey FOREIGN KEY (evidence_id) REFERENCES nex.food_enrichment_evidence(evidence_id) ON DELETE CASCADE;
ALTER TABLE nex.graph_edges ADD CONSTRAINT graph_edges_from_record_id_fkey FOREIGN KEY (from_record_id) REFERENCES nex.knowledge_records(record_id) ON DELETE CASCADE;
ALTER TABLE nex.journey_campaign_executions ADD CONSTRAINT journey_campaign_executions_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES nex.campaigns(campaign_id) ON DELETE RESTRICT;
ALTER TABLE nex.journey_campaign_executions ADD CONSTRAINT journey_campaign_executions_journey_state_id_fkey FOREIGN KEY (journey_state_id) REFERENCES nex.journey_states(state_id) ON DELETE CASCADE;
ALTER TABLE nex.journey_states ADD CONSTRAINT journey_states_journey_id_fkey FOREIGN KEY (journey_id) REFERENCES nex.journeys(journey_id) ON DELETE RESTRICT;
ALTER TABLE nex.journey_triggers ADD CONSTRAINT journey_triggers_journey_id_fkey FOREIGN KEY (journey_id) REFERENCES nex.journeys(journey_id) ON DELETE CASCADE;
ALTER TABLE nex.knowledge_feedback ADD CONSTRAINT knowledge_feedback_record_id_fkey FOREIGN KEY (record_id) REFERENCES nex.knowledge_records(record_id) ON DELETE SET NULL;
ALTER TABLE nex.knowledge_feedback ADD CONSTRAINT knowledge_feedback_resulted_in_record_fkey FOREIGN KEY (resulted_in_record) REFERENCES nex.knowledge_records(record_id) ON DELETE SET NULL;
ALTER TABLE nex.knowledge_records ADD CONSTRAINT knowledge_records_supersedes_fkey FOREIGN KEY (supersedes) REFERENCES nex.knowledge_records(record_id);
ALTER TABLE nex.llm_retry_queue ADD CONSTRAINT llm_retry_queue_parent_job_id_fkey FOREIGN KEY (parent_job_id) REFERENCES nex.worker_jobs(id) ON DELETE CASCADE;
ALTER TABLE nex.media_object ADD CONSTRAINT media_object_poster_media_id_fkey FOREIGN KEY (poster_media_id) REFERENCES nex.media_object(media_id) ON DELETE SET NULL;
ALTER TABLE nex.mp_category ADD CONSTRAINT mp_category_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES nex.mp_category(category_id);
ALTER TABLE nex.mp_commerce_policy ADD CONSTRAINT mp_commerce_policy_category_id_fkey FOREIGN KEY (category_id) REFERENCES nex.mp_category(category_id);
ALTER TABLE nex.mp_product ADD CONSTRAINT mp_product_category_id_fkey FOREIGN KEY (category_id) REFERENCES nex.mp_category(category_id);
ALTER TABLE nex.mp_product ADD CONSTRAINT mp_product_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES nex.mp_seller(seller_id) ON DELETE CASCADE;
ALTER TABLE nex.mp_product_image ADD CONSTRAINT mp_product_image_product_id_fkey FOREIGN KEY (product_id) REFERENCES nex.mp_product(product_id) ON DELETE CASCADE;
ALTER TABLE nex.mp_product_option ADD CONSTRAINT mp_product_option_product_id_fkey FOREIGN KEY (product_id) REFERENCES nex.mp_product(product_id) ON DELETE CASCADE;
ALTER TABLE nex.mp_product_option_value ADD CONSTRAINT mp_product_option_value_option_id_fkey FOREIGN KEY (option_id) REFERENCES nex.mp_product_option(option_id) ON DELETE CASCADE;
ALTER TABLE nex.mp_product_variant ADD CONSTRAINT mp_product_variant_product_id_fkey FOREIGN KEY (product_id) REFERENCES nex.mp_product(product_id) ON DELETE CASCADE;
ALTER TABLE nex.mp_seller ADD CONSTRAINT mp_seller_cycle_run_id_fkey FOREIGN KEY (cycle_run_id) REFERENCES nex.worker_cycle_run(id) ON DELETE SET NULL;
ALTER TABLE nex.predictions ADD CONSTRAINT predictions_model_id_fkey FOREIGN KEY (model_id) REFERENCES nex.prediction_models(model_id);
ALTER TABLE nex.provider_profile ADD CONSTRAINT driver_profile_bike_slug_fkey FOREIGN KEY (bike_slug) REFERENCES nex.bike_model(slug);
ALTER TABLE nex.provider_rate_lease ADD CONSTRAINT provider_rate_lease_provider_fkey FOREIGN KEY (provider) REFERENCES nex.provider_rate_config(provider);
ALTER TABLE nex.provider_topup_intent ADD CONSTRAINT provider_topup_intent_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES nex.provider_profile(provider_id) ON DELETE CASCADE;
ALTER TABLE nex.provider_wallet ADD CONSTRAINT provider_wallet_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES nex.provider_profile(provider_id) ON DELETE CASCADE;
ALTER TABLE nex.provider_wallet_transaction ADD CONSTRAINT provider_wallet_transaction_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES nex.provider_profile(provider_id) ON DELETE CASCADE;
ALTER TABLE nex.provider_wallet_transaction ADD CONSTRAINT provider_wallet_transaction_related_request_id_fkey FOREIGN KEY (related_request_id) REFERENCES nex.service_request(request_id) ON DELETE SET NULL;
ALTER TABLE nex.provider_wallet_transaction ADD CONSTRAINT provider_wallet_transaction_related_topup_intent_id_fkey FOREIGN KEY (related_topup_intent_id) REFERENCES nex.provider_topup_intent(intent_id) ON DELETE SET NULL;
ALTER TABLE nex.record_versions ADD CONSTRAINT record_versions_record_id_fkey FOREIGN KEY (record_id) REFERENCES nex.knowledge_records(record_id) ON DELETE CASCADE;
ALTER TABLE nex.rollup_campaigns ADD CONSTRAINT rollup_campaigns_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES nex.campaigns(campaign_id) ON DELETE CASCADE;
ALTER TABLE nex.rollup_segment ADD CONSTRAINT rollup_segment_segment_id_fkey FOREIGN KEY (segment_id) REFERENCES nex.contact_segments(segment_id) ON DELETE CASCADE;
ALTER TABLE nex.service_request ADD CONSTRAINT service_request_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES nex.provider_profile(provider_id);
ALTER TABLE nex.service_request_offer ADD CONSTRAINT service_request_offer_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES nex.provider_profile(provider_id);
ALTER TABLE nex.service_request_offer ADD CONSTRAINT service_request_offer_request_id_fkey FOREIGN KEY (request_id) REFERENCES nex.service_request(request_id) ON DELETE CASCADE;
ALTER TABLE nex.social_accounts ADD CONSTRAINT social_accounts_access_dek_id_fkey FOREIGN KEY (access_dek_id) REFERENCES nex.social_dek_wraps(dek_id);
ALTER TABLE nex.social_accounts ADD CONSTRAINT social_accounts_refresh_dek_id_fkey FOREIGN KEY (refresh_dek_id) REFERENCES nex.social_dek_wraps(dek_id);
ALTER TABLE nex.social_accounts ADD CONSTRAINT social_accounts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES nex.social_tenants(tenant_id) ON DELETE RESTRICT;
ALTER TABLE nex.social_brand_profiles ADD CONSTRAINT social_brand_profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES nex.social_tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE nex.social_category_automation ADD CONSTRAINT social_category_automation_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES nex.social_tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE nex.social_content_drafts ADD CONSTRAINT social_content_drafts_template_id_fkey FOREIGN KEY (template_id) REFERENCES nex.social_content_templates(template_id) ON DELETE SET NULL;
ALTER TABLE nex.social_content_drafts ADD CONSTRAINT social_content_drafts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES nex.social_tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE nex.social_content_drafts ADD CONSTRAINT social_content_drafts_validator_run_id_fkey FOREIGN KEY (validator_run_id) REFERENCES nex.social_validator_runs(run_id);
ALTER TABLE nex.social_content_sources ADD CONSTRAINT social_content_sources_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES nex.social_tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE nex.social_content_templates ADD CONSTRAINT social_content_templates_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES nex.social_tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE nex.social_dek_wraps ADD CONSTRAINT social_dek_wraps_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES nex.social_tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE nex.social_oauth_states ADD CONSTRAINT social_oauth_states_code_verifier_dek_id_fkey FOREIGN KEY (code_verifier_dek_id) REFERENCES nex.social_dek_wraps(dek_id);
ALTER TABLE nex.social_oauth_states ADD CONSTRAINT social_oauth_states_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES nex.social_tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE nex.social_publish_intents ADD CONSTRAINT social_publish_intents_account_id_fkey FOREIGN KEY (account_id) REFERENCES nex.social_accounts(account_id) ON DELETE RESTRICT;
ALTER TABLE nex.social_publish_intents ADD CONSTRAINT social_publish_intents_scheduled_id_fkey FOREIGN KEY (scheduled_id) REFERENCES nex.social_scheduled_posts(scheduled_id);
ALTER TABLE nex.social_publish_intents ADD CONSTRAINT social_publish_intents_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES nex.social_tenants(tenant_id) ON DELETE RESTRICT;
ALTER TABLE nex.social_role_grants ADD CONSTRAINT social_role_grants_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES nex.social_tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE nex.social_scheduled_posts ADD CONSTRAINT social_scheduled_posts_account_id_fkey FOREIGN KEY (account_id) REFERENCES nex.social_accounts(account_id) ON DELETE RESTRICT;
ALTER TABLE nex.social_scheduled_posts ADD CONSTRAINT social_scheduled_posts_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES nex.social_content_drafts(draft_id) ON DELETE CASCADE;
ALTER TABLE nex.social_scheduled_posts ADD CONSTRAINT social_scheduled_posts_intent_id_fkey FOREIGN KEY (intent_id) REFERENCES nex.social_publish_intents(intent_id) ON DELETE SET NULL;
ALTER TABLE nex.social_scheduled_posts ADD CONSTRAINT social_scheduled_posts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES nex.social_tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE nex.social_validator_runs ADD CONSTRAINT social_validator_runs_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES nex.social_content_drafts(draft_id) ON DELETE SET NULL;
ALTER TABLE nex.social_validator_runs ADD CONSTRAINT social_validator_runs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES nex.social_tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE nex.sources ADD CONSTRAINT sources_record_id_fkey FOREIGN KEY (record_id) REFERENCES nex.knowledge_records(record_id) ON DELETE CASCADE;
ALTER TABLE nex.sparks_product_price ADD CONSTRAINT sparks_product_price_product_id_fkey FOREIGN KEY (product_id) REFERENCES nex.sparks_product(product_id);
ALTER TABLE nex.transport_acquisition_outreach ADD CONSTRAINT transport_acquisition_outreach_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES nex.transport_acquisition_record(provider_id) ON DELETE CASCADE;
ALTER TABLE nex.transport_acquisition_outreach ADD CONSTRAINT transport_acquisition_outreach_source_evidence_snapshot_id_fkey FOREIGN KEY (source_evidence_snapshot_id) REFERENCES nex.transport_acquisition_source_snapshot(snapshot_id);
ALTER TABLE nex.transport_acquisition_source_snapshot ADD CONSTRAINT transport_acquisition_source_snapshot_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES nex.transport_acquisition_record(provider_id) ON DELETE CASCADE;
ALTER TABLE nex.wallet_transaction ADD CONSTRAINT wallet_transaction_related_transaction_id_fkey FOREIGN KEY (related_transaction_id) REFERENCES nex.wallet_transaction(transaction_id);
ALTER TABLE nex.wallet_transaction ADD CONSTRAINT wallet_transaction_user_id_fkey FOREIGN KEY (user_id) REFERENCES nex.user_wallet(user_id);
ALTER TABLE nex.worker_results ADD CONSTRAINT worker_results_job_id_fkey FOREIGN KEY (job_id) REFERENCES nex.worker_jobs(id) ON DELETE CASCADE;
COMMIT;