// src/lib/nex-project-profile/scanner.ts
//
// NEX1 · PROJECT PROFILE · deterministic file walker.
// authored_by = master_ai_engineer · founder-authorised 2026-09-12
//
// READ-ONLY. Never writes into the measured project. Uses only readdirSync
// + readFileSync + statSync. Excludes vendor/generated markers reused from
// Code Intelligence (never a second contradictory definition).

import { readdirSync, readFileSync, statSync, existsSync } from "node:fs";
import { resolve, join, sep, relative } from "node:path";
import { createHash } from "node:crypto";

const VENDOR_PATH_MARKERS: readonly string[] = Object.freeze([
  "node_modules", "vendor", ".venv", "venv", "target", "build",
  "dist", ".next", ".nuxt", "__pycache__", ".cargo", "third_party",
  "third-party", ".git", ".turbo", ".cache", "coverage",
]);

export interface WalkedFile {
  readonly abs_path: string;
  readonly rel_path: string;
  readonly size: number;
  readonly is_vendor: boolean;
  readonly is_generated: boolean;
  readonly extension: string;
}

export interface WalkOptions {
  readonly root: string;
  readonly max_files: number;          // hard cap · never exceeded
  readonly max_bytes: number;          // hard cap on cumulative bytes read
  readonly sample_cap_per_language: number;
  readonly skip_vendor: boolean;
  readonly skip_generated: boolean;
}

export interface WalkResult {
  readonly files: readonly WalkedFile[];
  readonly excluded: readonly string[];
  readonly excluded_reasons: Readonly<Record<string, number>>;
  readonly bytes_read: number;
  readonly hit_max_files_cap: boolean;
  readonly hit_max_bytes_cap: boolean;
  readonly elapsed_ms: number;
}

export function walkProject(opts: WalkOptions): WalkResult {
  const t0 = Date.now();
  const files: WalkedFile[] = [];
  const excluded: string[] = [];
  const excludedReasons: Record<string, number> = {};
  let bytes_read = 0;
  let hit_max_files_cap = false;
  let hit_max_bytes_cap = false;

  const root = resolve(opts.root);
  const stack: string[] = [root];
  while (stack.length > 0) {
    if (files.length >= opts.max_files) { hit_max_files_cap = true; break; }
    if (bytes_read >= opts.max_bytes) { hit_max_bytes_cap = true; break; }
    const dir = stack.pop()!;
    let entries: string[];
    try { entries = readdirSync(dir); } catch { continue; }
    for (const name of entries) {
      const abs = join(dir, name);
      let st;
      try { st = statSync(abs); } catch { continue; }
      const rel = relative(root, abs).split(sep).join("/");
      if (st.isDirectory()) {
        if (opts.skip_vendor && VENDOR_PATH_MARKERS.includes(name)) {
          excluded.push(rel);
          excludedReasons["vendor_or_generated"] = (excludedReasons["vendor_or_generated"] ?? 0) + 1;
          continue;
        }
        stack.push(abs);
      } else if (st.isFile()) {
        const ext = extensionOf(name);
        const is_vendor = VENDOR_PATH_MARKERS.some((m) => rel.includes("/" + m + "/") || rel.startsWith(m + "/"));
        // Only sniff first 4KB for generated marker to keep bytes_read bounded
        let is_generated = false;
        if (st.size < opts.max_bytes - bytes_read) {
          try {
            const head = readFileSync(abs, { encoding: "utf8" }).slice(0, 4000);
            bytes_read += Math.min(4000, st.size);
            is_generated = /^\/\/\s*GENERATED FILE|^\/\/\s*Code generated by|^#\s*Generated by|DO NOT EDIT|This file is autogenerated/m.test(head);
          } catch { /* unreadable · skip content sniff */ }
        }
        if ((opts.skip_vendor && is_vendor) || (opts.skip_generated && is_generated)) {
          excluded.push(rel);
          excludedReasons[is_vendor ? "vendor_path" : "generated_marker"] = (excludedReasons[is_vendor ? "vendor_path" : "generated_marker"] ?? 0) + 1;
          continue;
        }
        files.push({ abs_path: abs, rel_path: rel, size: st.size, is_vendor, is_generated, extension: ext });
      }
    }
  }
  return {
    files,
    excluded,
    excluded_reasons: excludedReasons,
    bytes_read,
    hit_max_files_cap,
    hit_max_bytes_cap,
    elapsed_ms: Date.now() - t0,
  };
}

export function extensionOf(f: string): string {
  const i = f.lastIndexOf(".");
  return i > 0 ? f.slice(i).toLowerCase() : "";
}

export function sha256Prefix(input: string): string {
  return createHash("sha256").update(input, "utf8").digest("hex").slice(0, 16);
}

/** Deterministic content-read with size cap · returns null if too big or unreadable. */
export function safeReadFile(abs: string, maxBytes = 512 * 1024): string | null {
  try {
    const st = statSync(abs);
    if (st.size > maxBytes) return null;
    return readFileSync(abs, "utf8");
  } catch { return null; }
}

/** Byte-identity witness for a fixed sample of important project files. */
export function witnessKeyFiles(root: string): { hashes: readonly EvidenceHashLite[]; combined_hash_prefix: string } {
  const candidates = [
    "package.json", "tsconfig.json", "package-lock.json",
    "data/nex1-language-brain/regression/regression-index.json",
    "data/nex1-language-brain/pattern-registry-v0.json",
    "src/lib/nex-language-brain/intent-bridge-v0.ts",
    "src/lib/nex-integration/pipeline.ts",
    "src/lib/nex-evidence-engine/engine.ts",
    "data/nex1-engineering-evolution/evidence-record-schema-v0.1.0.json",
  ];
  const hashes: EvidenceHashLite[] = [];
  for (const rel of candidates) {
    const abs = resolve(root, rel);
    if (!existsSync(abs)) continue;
    try {
      const c = readFileSync(abs, "utf8");
      hashes.push({ path: rel, sha256_prefix: sha256Prefix(c), size_bytes: c.length });
    } catch { /* skip unreadable */ }
  }
  const combined = sha256Prefix(hashes.map((h) => h.path + ":" + h.sha256_prefix + ":" + h.size_bytes).join("|"));
  return { hashes, combined_hash_prefix: combined };
}
export interface EvidenceHashLite { readonly path: string; readonly sha256_prefix: string; readonly size_bytes: number; }
