// src/lib/nex/github-round-trip/pr-body.ts
//
// Stage 8 · build a well-formed PR body from a section revision + artifact
// summary + founder change-request context. Never generated with LLM · pure
// deterministic template so the PR body is verifiable against the revision.

import type { BuildArtifact, SectionRevision } from "../section-build";

export interface PrBodyInputs {
  readonly revision: SectionRevision;
  readonly artifact: BuildArtifact;
  readonly capabilityTitle: string;
  readonly previewUrl: string | null;
  readonly founderMessage: string | null;    // populated for v1.N+1 revisions
  readonly parentVersion: string | null;
}

export function buildPrTitle(inputs: PrBodyInputs): string {
  const cap = inputs.revision.capability_id;
  const version = inputs.revision.version;
  const title = inputs.capabilityTitle.trim().slice(0, 80);
  return `[${cap}/${version}] ${title}`;
}

export function buildPrBody(inputs: PrBodyInputs): string {
  const r = inputs.revision;
  const a = inputs.artifact;
  const lines: string[] = [];

  lines.push(`## Capability`);
  lines.push(`- **ID:** ${r.capability_id}`);
  lines.push(`- **Title:** ${inputs.capabilityTitle}`);
  lines.push(`- **Version:** ${r.version}${inputs.parentVersion ? ` (parent ${inputs.parentVersion})` : ""}`);
  lines.push(`- **Lifecycle state:** ${r.lifecycle_state}`);
  lines.push(``);

  lines.push(`## Build artifact`);
  lines.push(`- **artifact_id:** \`${a.artifact_id}\``);
  lines.push(`- **content_hash:** \`${a.content_hash.slice(0, 16)}…\``);
  lines.push(`- **files:** ${a.files_count} · ${a.total_bytes} bytes`);
  lines.push(`- **tests:** ${a.tests_passed}/${a.tests_total} passed`);
  lines.push(`- **guardian_verdict:** ${a.guardian_verdict ?? "PENDING"}`);
  lines.push(`- **truth_engine_ok:** ${a.truth_engine_ok === null ? "PENDING" : a.truth_engine_ok ? "true" : "false"}`);
  lines.push(`- **ui_dna_verdict:** ${a.ui_dna_verdict ?? "PENDING"}`);
  lines.push(``);

  if (inputs.previewUrl) {
    lines.push(`## Preview`);
    lines.push(`- Preview URL: ${inputs.previewUrl}`);
    lines.push(``);
  }

  if (inputs.founderMessage) {
    lines.push(`## Founder change request`);
    lines.push(`> ${inputs.founderMessage.replace(/\n/g, "\n> ")}`);
    lines.push(``);
  }

  lines.push(`## Discipline`);
  lines.push(`- Security Agent CI workflow: must pass before merge (never \`--no-verify\`)`);
  lines.push(`- Lifecycle: BUILD → TEST → SELF-CHECK → SUPERVISORY REVIEW → CORRECT → RE-TEST → PASS → VERSION → PREVIEW → FOUNDER APPROVAL → LIVE`);
  lines.push(`- LIVE deployment remains a separate founder decision (not merged = not live)`);
  lines.push(``);

  lines.push(`_Generated by NEX1 controlled builder · ADR-0316a/b/c/d._`);
  return lines.join("\n");
}
