// src/lib/nex-native/geo/iso-countries.ts
//
// NEX · ISO 3166-1 alpha-2 country metadata table.
//
// Static reference data for the Directory country picker. Covers every
// ISO 3166-1 alpha-2 code (247 entries · includes exceptional reservations
// used in NEX scope such as `XK` for Kosovo). No currency, no language —
// those live elsewhere; this file is picker-only.
//
// Flag asset strategy
//   The picker renders a flag per entry. This module does NOT embed SVG;
//   it exposes a stable key (`isoAlpha2`) that the UI can map to a flag
//   asset via its own convention (public/flags/<code-lower>.svg, a
//   bundled sprite, or a text-badge fallback). The deliberate decision
//   is to avoid taking a dependency on `circle-flags` or similar — the
//   picker degrades to the ISO code displayed in a styled circle if the
//   flag asset is missing, which is honest and never shipped-broken.
//
// Why not emoji regional-indicator flags? Windows does not render them;
// the user sees the letter pair ("GB"/"ID") instead. Shipping emoji
// flags produces a picker that looks broken in NEX's own dev
// environment. SVG assets (or the text-badge fallback) are the only
// correct choice for a Windows-authored product.

export interface IsoCountry {
  readonly isoAlpha2: string;    // e.g. "ID"
  readonly isoAlpha3: string;    // e.g. "IDN"
  readonly name: string;         // common English name
  readonly nativeName: string | null; // native-language name where known
  readonly region: "Africa" | "Americas" | "Antarctica" | "Asia" | "Europe" | "Oceania";
}

// Alphabetical by name. Native names included where NEX anticipates
// customer-facing display; `null` elsewhere to avoid fabricating.
export const ISO_COUNTRIES: readonly IsoCountry[] = Object.freeze([
  { isoAlpha2: "AF", isoAlpha3: "AFG", name: "Afghanistan", nativeName: "افغانستان", region: "Asia" },
  { isoAlpha2: "AX", isoAlpha3: "ALA", name: "Åland Islands", nativeName: "Åland", region: "Europe" },
  { isoAlpha2: "AL", isoAlpha3: "ALB", name: "Albania", nativeName: "Shqipëria", region: "Europe" },
  { isoAlpha2: "DZ", isoAlpha3: "DZA", name: "Algeria", nativeName: "الجزائر", region: "Africa" },
  { isoAlpha2: "AS", isoAlpha3: "ASM", name: "American Samoa", nativeName: null, region: "Oceania" },
  { isoAlpha2: "AD", isoAlpha3: "AND", name: "Andorra", nativeName: null, region: "Europe" },
  { isoAlpha2: "AO", isoAlpha3: "AGO", name: "Angola", nativeName: null, region: "Africa" },
  { isoAlpha2: "AI", isoAlpha3: "AIA", name: "Anguilla", nativeName: null, region: "Americas" },
  { isoAlpha2: "AQ", isoAlpha3: "ATA", name: "Antarctica", nativeName: null, region: "Antarctica" },
  { isoAlpha2: "AG", isoAlpha3: "ATG", name: "Antigua and Barbuda", nativeName: null, region: "Americas" },
  { isoAlpha2: "AR", isoAlpha3: "ARG", name: "Argentina", nativeName: null, region: "Americas" },
  { isoAlpha2: "AM", isoAlpha3: "ARM", name: "Armenia", nativeName: "Հայաստան", region: "Asia" },
  { isoAlpha2: "AW", isoAlpha3: "ABW", name: "Aruba", nativeName: null, region: "Americas" },
  { isoAlpha2: "AU", isoAlpha3: "AUS", name: "Australia", nativeName: null, region: "Oceania" },
  { isoAlpha2: "AT", isoAlpha3: "AUT", name: "Austria", nativeName: "Österreich", region: "Europe" },
  { isoAlpha2: "AZ", isoAlpha3: "AZE", name: "Azerbaijan", nativeName: "Azərbaycan", region: "Asia" },
  { isoAlpha2: "BS", isoAlpha3: "BHS", name: "Bahamas", nativeName: null, region: "Americas" },
  { isoAlpha2: "BH", isoAlpha3: "BHR", name: "Bahrain", nativeName: "البحرين", region: "Asia" },
  { isoAlpha2: "BD", isoAlpha3: "BGD", name: "Bangladesh", nativeName: "বাংলাদেশ", region: "Asia" },
  { isoAlpha2: "BB", isoAlpha3: "BRB", name: "Barbados", nativeName: null, region: "Americas" },
  { isoAlpha2: "BY", isoAlpha3: "BLR", name: "Belarus", nativeName: "Беларусь", region: "Europe" },
  { isoAlpha2: "BE", isoAlpha3: "BEL", name: "Belgium", nativeName: "België", region: "Europe" },
  { isoAlpha2: "BZ", isoAlpha3: "BLZ", name: "Belize", nativeName: null, region: "Americas" },
  { isoAlpha2: "BJ", isoAlpha3: "BEN", name: "Benin", nativeName: "Bénin", region: "Africa" },
  { isoAlpha2: "BM", isoAlpha3: "BMU", name: "Bermuda", nativeName: null, region: "Americas" },
  { isoAlpha2: "BT", isoAlpha3: "BTN", name: "Bhutan", nativeName: "འབྲུག", region: "Asia" },
  { isoAlpha2: "BO", isoAlpha3: "BOL", name: "Bolivia", nativeName: null, region: "Americas" },
  { isoAlpha2: "BQ", isoAlpha3: "BES", name: "Bonaire, Sint Eustatius and Saba", nativeName: null, region: "Americas" },
  { isoAlpha2: "BA", isoAlpha3: "BIH", name: "Bosnia and Herzegovina", nativeName: "Bosna i Hercegovina", region: "Europe" },
  { isoAlpha2: "BW", isoAlpha3: "BWA", name: "Botswana", nativeName: null, region: "Africa" },
  { isoAlpha2: "BV", isoAlpha3: "BVT", name: "Bouvet Island", nativeName: null, region: "Antarctica" },
  { isoAlpha2: "BR", isoAlpha3: "BRA", name: "Brazil", nativeName: "Brasil", region: "Americas" },
  { isoAlpha2: "IO", isoAlpha3: "IOT", name: "British Indian Ocean Territory", nativeName: null, region: "Asia" },
  { isoAlpha2: "BN", isoAlpha3: "BRN", name: "Brunei Darussalam", nativeName: null, region: "Asia" },
  { isoAlpha2: "BG", isoAlpha3: "BGR", name: "Bulgaria", nativeName: "България", region: "Europe" },
  { isoAlpha2: "BF", isoAlpha3: "BFA", name: "Burkina Faso", nativeName: null, region: "Africa" },
  { isoAlpha2: "BI", isoAlpha3: "BDI", name: "Burundi", nativeName: null, region: "Africa" },
  { isoAlpha2: "CV", isoAlpha3: "CPV", name: "Cabo Verde", nativeName: null, region: "Africa" },
  { isoAlpha2: "KH", isoAlpha3: "KHM", name: "Cambodia", nativeName: "កម្ពុជា", region: "Asia" },
  { isoAlpha2: "CM", isoAlpha3: "CMR", name: "Cameroon", nativeName: null, region: "Africa" },
  { isoAlpha2: "CA", isoAlpha3: "CAN", name: "Canada", nativeName: null, region: "Americas" },
  { isoAlpha2: "KY", isoAlpha3: "CYM", name: "Cayman Islands", nativeName: null, region: "Americas" },
  { isoAlpha2: "CF", isoAlpha3: "CAF", name: "Central African Republic", nativeName: null, region: "Africa" },
  { isoAlpha2: "TD", isoAlpha3: "TCD", name: "Chad", nativeName: null, region: "Africa" },
  { isoAlpha2: "CL", isoAlpha3: "CHL", name: "Chile", nativeName: null, region: "Americas" },
  { isoAlpha2: "CN", isoAlpha3: "CHN", name: "China", nativeName: "中国", region: "Asia" },
  { isoAlpha2: "CX", isoAlpha3: "CXR", name: "Christmas Island", nativeName: null, region: "Oceania" },
  { isoAlpha2: "CC", isoAlpha3: "CCK", name: "Cocos (Keeling) Islands", nativeName: null, region: "Oceania" },
  { isoAlpha2: "CO", isoAlpha3: "COL", name: "Colombia", nativeName: null, region: "Americas" },
  { isoAlpha2: "KM", isoAlpha3: "COM", name: "Comoros", nativeName: null, region: "Africa" },
  { isoAlpha2: "CG", isoAlpha3: "COG", name: "Congo", nativeName: null, region: "Africa" },
  { isoAlpha2: "CD", isoAlpha3: "COD", name: "Congo, Democratic Republic of the", nativeName: null, region: "Africa" },
  { isoAlpha2: "CK", isoAlpha3: "COK", name: "Cook Islands", nativeName: null, region: "Oceania" },
  { isoAlpha2: "CR", isoAlpha3: "CRI", name: "Costa Rica", nativeName: null, region: "Americas" },
  { isoAlpha2: "CI", isoAlpha3: "CIV", name: "Côte d'Ivoire", nativeName: null, region: "Africa" },
  { isoAlpha2: "HR", isoAlpha3: "HRV", name: "Croatia", nativeName: "Hrvatska", region: "Europe" },
  { isoAlpha2: "CU", isoAlpha3: "CUB", name: "Cuba", nativeName: null, region: "Americas" },
  { isoAlpha2: "CW", isoAlpha3: "CUW", name: "Curaçao", nativeName: null, region: "Americas" },
  { isoAlpha2: "CY", isoAlpha3: "CYP", name: "Cyprus", nativeName: "Κύπρος", region: "Asia" },
  { isoAlpha2: "CZ", isoAlpha3: "CZE", name: "Czechia", nativeName: "Česko", region: "Europe" },
  { isoAlpha2: "DK", isoAlpha3: "DNK", name: "Denmark", nativeName: "Danmark", region: "Europe" },
  { isoAlpha2: "DJ", isoAlpha3: "DJI", name: "Djibouti", nativeName: null, region: "Africa" },
  { isoAlpha2: "DM", isoAlpha3: "DMA", name: "Dominica", nativeName: null, region: "Americas" },
  { isoAlpha2: "DO", isoAlpha3: "DOM", name: "Dominican Republic", nativeName: null, region: "Americas" },
  { isoAlpha2: "EC", isoAlpha3: "ECU", name: "Ecuador", nativeName: null, region: "Americas" },
  { isoAlpha2: "EG", isoAlpha3: "EGY", name: "Egypt", nativeName: "مصر", region: "Africa" },
  { isoAlpha2: "SV", isoAlpha3: "SLV", name: "El Salvador", nativeName: null, region: "Americas" },
  { isoAlpha2: "GQ", isoAlpha3: "GNQ", name: "Equatorial Guinea", nativeName: null, region: "Africa" },
  { isoAlpha2: "ER", isoAlpha3: "ERI", name: "Eritrea", nativeName: null, region: "Africa" },
  { isoAlpha2: "EE", isoAlpha3: "EST", name: "Estonia", nativeName: "Eesti", region: "Europe" },
  { isoAlpha2: "SZ", isoAlpha3: "SWZ", name: "Eswatini", nativeName: null, region: "Africa" },
  { isoAlpha2: "ET", isoAlpha3: "ETH", name: "Ethiopia", nativeName: null, region: "Africa" },
  { isoAlpha2: "FK", isoAlpha3: "FLK", name: "Falkland Islands (Malvinas)", nativeName: null, region: "Americas" },
  { isoAlpha2: "FO", isoAlpha3: "FRO", name: "Faroe Islands", nativeName: null, region: "Europe" },
  { isoAlpha2: "FJ", isoAlpha3: "FJI", name: "Fiji", nativeName: null, region: "Oceania" },
  { isoAlpha2: "FI", isoAlpha3: "FIN", name: "Finland", nativeName: "Suomi", region: "Europe" },
  { isoAlpha2: "FR", isoAlpha3: "FRA", name: "France", nativeName: null, region: "Europe" },
  { isoAlpha2: "GF", isoAlpha3: "GUF", name: "French Guiana", nativeName: null, region: "Americas" },
  { isoAlpha2: "PF", isoAlpha3: "PYF", name: "French Polynesia", nativeName: null, region: "Oceania" },
  { isoAlpha2: "TF", isoAlpha3: "ATF", name: "French Southern Territories", nativeName: null, region: "Antarctica" },
  { isoAlpha2: "GA", isoAlpha3: "GAB", name: "Gabon", nativeName: null, region: "Africa" },
  { isoAlpha2: "GM", isoAlpha3: "GMB", name: "Gambia", nativeName: null, region: "Africa" },
  { isoAlpha2: "GE", isoAlpha3: "GEO", name: "Georgia", nativeName: "საქართველო", region: "Asia" },
  { isoAlpha2: "DE", isoAlpha3: "DEU", name: "Germany", nativeName: "Deutschland", region: "Europe" },
  { isoAlpha2: "GH", isoAlpha3: "GHA", name: "Ghana", nativeName: null, region: "Africa" },
  { isoAlpha2: "GI", isoAlpha3: "GIB", name: "Gibraltar", nativeName: null, region: "Europe" },
  { isoAlpha2: "GR", isoAlpha3: "GRC", name: "Greece", nativeName: "Ελλάδα", region: "Europe" },
  { isoAlpha2: "GL", isoAlpha3: "GRL", name: "Greenland", nativeName: null, region: "Americas" },
  { isoAlpha2: "GD", isoAlpha3: "GRD", name: "Grenada", nativeName: null, region: "Americas" },
  { isoAlpha2: "GP", isoAlpha3: "GLP", name: "Guadeloupe", nativeName: null, region: "Americas" },
  { isoAlpha2: "GU", isoAlpha3: "GUM", name: "Guam", nativeName: null, region: "Oceania" },
  { isoAlpha2: "GT", isoAlpha3: "GTM", name: "Guatemala", nativeName: null, region: "Americas" },
  { isoAlpha2: "GG", isoAlpha3: "GGY", name: "Guernsey", nativeName: null, region: "Europe" },
  { isoAlpha2: "GN", isoAlpha3: "GIN", name: "Guinea", nativeName: null, region: "Africa" },
  { isoAlpha2: "GW", isoAlpha3: "GNB", name: "Guinea-Bissau", nativeName: null, region: "Africa" },
  { isoAlpha2: "GY", isoAlpha3: "GUY", name: "Guyana", nativeName: null, region: "Americas" },
  { isoAlpha2: "HT", isoAlpha3: "HTI", name: "Haiti", nativeName: null, region: "Americas" },
  { isoAlpha2: "HM", isoAlpha3: "HMD", name: "Heard Island and McDonald Islands", nativeName: null, region: "Antarctica" },
  { isoAlpha2: "VA", isoAlpha3: "VAT", name: "Holy See", nativeName: null, region: "Europe" },
  { isoAlpha2: "HN", isoAlpha3: "HND", name: "Honduras", nativeName: null, region: "Americas" },
  { isoAlpha2: "HK", isoAlpha3: "HKG", name: "Hong Kong", nativeName: "香港", region: "Asia" },
  { isoAlpha2: "HU", isoAlpha3: "HUN", name: "Hungary", nativeName: "Magyarország", region: "Europe" },
  { isoAlpha2: "IS", isoAlpha3: "ISL", name: "Iceland", nativeName: "Ísland", region: "Europe" },
  { isoAlpha2: "IN", isoAlpha3: "IND", name: "India", nativeName: "भारत", region: "Asia" },
  { isoAlpha2: "ID", isoAlpha3: "IDN", name: "Indonesia", nativeName: "Indonesia", region: "Asia" },
  { isoAlpha2: "IR", isoAlpha3: "IRN", name: "Iran", nativeName: "ایران", region: "Asia" },
  { isoAlpha2: "IQ", isoAlpha3: "IRQ", name: "Iraq", nativeName: "العراق", region: "Asia" },
  { isoAlpha2: "IE", isoAlpha3: "IRL", name: "Ireland", nativeName: "Éire", region: "Europe" },
  { isoAlpha2: "IM", isoAlpha3: "IMN", name: "Isle of Man", nativeName: null, region: "Europe" },
  { isoAlpha2: "IL", isoAlpha3: "ISR", name: "Israel", nativeName: "ישראל", region: "Asia" },
  { isoAlpha2: "IT", isoAlpha3: "ITA", name: "Italy", nativeName: "Italia", region: "Europe" },
  { isoAlpha2: "JM", isoAlpha3: "JAM", name: "Jamaica", nativeName: null, region: "Americas" },
  { isoAlpha2: "JP", isoAlpha3: "JPN", name: "Japan", nativeName: "日本", region: "Asia" },
  { isoAlpha2: "JE", isoAlpha3: "JEY", name: "Jersey", nativeName: null, region: "Europe" },
  { isoAlpha2: "JO", isoAlpha3: "JOR", name: "Jordan", nativeName: "الأردن", region: "Asia" },
  { isoAlpha2: "KZ", isoAlpha3: "KAZ", name: "Kazakhstan", nativeName: "Қазақстан", region: "Asia" },
  { isoAlpha2: "KE", isoAlpha3: "KEN", name: "Kenya", nativeName: null, region: "Africa" },
  { isoAlpha2: "KI", isoAlpha3: "KIR", name: "Kiribati", nativeName: null, region: "Oceania" },
  { isoAlpha2: "KP", isoAlpha3: "PRK", name: "Korea, Democratic People's Republic of", nativeName: "조선", region: "Asia" },
  { isoAlpha2: "KR", isoAlpha3: "KOR", name: "Korea, Republic of", nativeName: "대한민국", region: "Asia" },
  { isoAlpha2: "XK", isoAlpha3: "XKX", name: "Kosovo", nativeName: "Kosovë", region: "Europe" },
  { isoAlpha2: "KW", isoAlpha3: "KWT", name: "Kuwait", nativeName: "الكويت", region: "Asia" },
  { isoAlpha2: "KG", isoAlpha3: "KGZ", name: "Kyrgyzstan", nativeName: null, region: "Asia" },
  { isoAlpha2: "LA", isoAlpha3: "LAO", name: "Laos", nativeName: null, region: "Asia" },
  { isoAlpha2: "LV", isoAlpha3: "LVA", name: "Latvia", nativeName: "Latvija", region: "Europe" },
  { isoAlpha2: "LB", isoAlpha3: "LBN", name: "Lebanon", nativeName: "لبنان", region: "Asia" },
  { isoAlpha2: "LS", isoAlpha3: "LSO", name: "Lesotho", nativeName: null, region: "Africa" },
  { isoAlpha2: "LR", isoAlpha3: "LBR", name: "Liberia", nativeName: null, region: "Africa" },
  { isoAlpha2: "LY", isoAlpha3: "LBY", name: "Libya", nativeName: null, region: "Africa" },
  { isoAlpha2: "LI", isoAlpha3: "LIE", name: "Liechtenstein", nativeName: null, region: "Europe" },
  { isoAlpha2: "LT", isoAlpha3: "LTU", name: "Lithuania", nativeName: "Lietuva", region: "Europe" },
  { isoAlpha2: "LU", isoAlpha3: "LUX", name: "Luxembourg", nativeName: null, region: "Europe" },
  { isoAlpha2: "MO", isoAlpha3: "MAC", name: "Macao", nativeName: "澳門", region: "Asia" },
  { isoAlpha2: "MG", isoAlpha3: "MDG", name: "Madagascar", nativeName: null, region: "Africa" },
  { isoAlpha2: "MW", isoAlpha3: "MWI", name: "Malawi", nativeName: null, region: "Africa" },
  { isoAlpha2: "MY", isoAlpha3: "MYS", name: "Malaysia", nativeName: null, region: "Asia" },
  { isoAlpha2: "MV", isoAlpha3: "MDV", name: "Maldives", nativeName: null, region: "Asia" },
  { isoAlpha2: "ML", isoAlpha3: "MLI", name: "Mali", nativeName: null, region: "Africa" },
  { isoAlpha2: "MT", isoAlpha3: "MLT", name: "Malta", nativeName: null, region: "Europe" },
  { isoAlpha2: "MH", isoAlpha3: "MHL", name: "Marshall Islands", nativeName: null, region: "Oceania" },
  { isoAlpha2: "MQ", isoAlpha3: "MTQ", name: "Martinique", nativeName: null, region: "Americas" },
  { isoAlpha2: "MR", isoAlpha3: "MRT", name: "Mauritania", nativeName: null, region: "Africa" },
  { isoAlpha2: "MU", isoAlpha3: "MUS", name: "Mauritius", nativeName: null, region: "Africa" },
  { isoAlpha2: "YT", isoAlpha3: "MYT", name: "Mayotte", nativeName: null, region: "Africa" },
  { isoAlpha2: "MX", isoAlpha3: "MEX", name: "Mexico", nativeName: "México", region: "Americas" },
  { isoAlpha2: "FM", isoAlpha3: "FSM", name: "Micronesia", nativeName: null, region: "Oceania" },
  { isoAlpha2: "MD", isoAlpha3: "MDA", name: "Moldova", nativeName: null, region: "Europe" },
  { isoAlpha2: "MC", isoAlpha3: "MCO", name: "Monaco", nativeName: null, region: "Europe" },
  { isoAlpha2: "MN", isoAlpha3: "MNG", name: "Mongolia", nativeName: "Монгол улс", region: "Asia" },
  { isoAlpha2: "ME", isoAlpha3: "MNE", name: "Montenegro", nativeName: "Crna Gora", region: "Europe" },
  { isoAlpha2: "MS", isoAlpha3: "MSR", name: "Montserrat", nativeName: null, region: "Americas" },
  { isoAlpha2: "MA", isoAlpha3: "MAR", name: "Morocco", nativeName: "المغرب", region: "Africa" },
  { isoAlpha2: "MZ", isoAlpha3: "MOZ", name: "Mozambique", nativeName: null, region: "Africa" },
  { isoAlpha2: "MM", isoAlpha3: "MMR", name: "Myanmar", nativeName: "မြန်မာ", region: "Asia" },
  { isoAlpha2: "NA", isoAlpha3: "NAM", name: "Namibia", nativeName: null, region: "Africa" },
  { isoAlpha2: "NR", isoAlpha3: "NRU", name: "Nauru", nativeName: null, region: "Oceania" },
  { isoAlpha2: "NP", isoAlpha3: "NPL", name: "Nepal", nativeName: "नेपाल", region: "Asia" },
  { isoAlpha2: "NL", isoAlpha3: "NLD", name: "Netherlands", nativeName: "Nederland", region: "Europe" },
  { isoAlpha2: "NC", isoAlpha3: "NCL", name: "New Caledonia", nativeName: null, region: "Oceania" },
  { isoAlpha2: "NZ", isoAlpha3: "NZL", name: "New Zealand", nativeName: null, region: "Oceania" },
  { isoAlpha2: "NI", isoAlpha3: "NIC", name: "Nicaragua", nativeName: null, region: "Americas" },
  { isoAlpha2: "NE", isoAlpha3: "NER", name: "Niger", nativeName: null, region: "Africa" },
  { isoAlpha2: "NG", isoAlpha3: "NGA", name: "Nigeria", nativeName: null, region: "Africa" },
  { isoAlpha2: "NU", isoAlpha3: "NIU", name: "Niue", nativeName: null, region: "Oceania" },
  { isoAlpha2: "NF", isoAlpha3: "NFK", name: "Norfolk Island", nativeName: null, region: "Oceania" },
  { isoAlpha2: "MK", isoAlpha3: "MKD", name: "North Macedonia", nativeName: "Северна Македонија", region: "Europe" },
  { isoAlpha2: "MP", isoAlpha3: "MNP", name: "Northern Mariana Islands", nativeName: null, region: "Oceania" },
  { isoAlpha2: "NO", isoAlpha3: "NOR", name: "Norway", nativeName: "Norge", region: "Europe" },
  { isoAlpha2: "OM", isoAlpha3: "OMN", name: "Oman", nativeName: "عُمان", region: "Asia" },
  { isoAlpha2: "PK", isoAlpha3: "PAK", name: "Pakistan", nativeName: "پاکستان", region: "Asia" },
  { isoAlpha2: "PW", isoAlpha3: "PLW", name: "Palau", nativeName: null, region: "Oceania" },
  { isoAlpha2: "PS", isoAlpha3: "PSE", name: "Palestine, State of", nativeName: "فلسطين", region: "Asia" },
  { isoAlpha2: "PA", isoAlpha3: "PAN", name: "Panama", nativeName: null, region: "Americas" },
  { isoAlpha2: "PG", isoAlpha3: "PNG", name: "Papua New Guinea", nativeName: null, region: "Oceania" },
  { isoAlpha2: "PY", isoAlpha3: "PRY", name: "Paraguay", nativeName: null, region: "Americas" },
  { isoAlpha2: "PE", isoAlpha3: "PER", name: "Peru", nativeName: null, region: "Americas" },
  { isoAlpha2: "PH", isoAlpha3: "PHL", name: "Philippines", nativeName: null, region: "Asia" },
  { isoAlpha2: "PN", isoAlpha3: "PCN", name: "Pitcairn", nativeName: null, region: "Oceania" },
  { isoAlpha2: "PL", isoAlpha3: "POL", name: "Poland", nativeName: "Polska", region: "Europe" },
  { isoAlpha2: "PT", isoAlpha3: "PRT", name: "Portugal", nativeName: null, region: "Europe" },
  { isoAlpha2: "PR", isoAlpha3: "PRI", name: "Puerto Rico", nativeName: null, region: "Americas" },
  { isoAlpha2: "QA", isoAlpha3: "QAT", name: "Qatar", nativeName: "قطر", region: "Asia" },
  { isoAlpha2: "RE", isoAlpha3: "REU", name: "Réunion", nativeName: null, region: "Africa" },
  { isoAlpha2: "RO", isoAlpha3: "ROU", name: "Romania", nativeName: "România", region: "Europe" },
  { isoAlpha2: "RU", isoAlpha3: "RUS", name: "Russian Federation", nativeName: "Россия", region: "Europe" },
  { isoAlpha2: "RW", isoAlpha3: "RWA", name: "Rwanda", nativeName: null, region: "Africa" },
  { isoAlpha2: "BL", isoAlpha3: "BLM", name: "Saint Barthélemy", nativeName: null, region: "Americas" },
  { isoAlpha2: "SH", isoAlpha3: "SHN", name: "Saint Helena", nativeName: null, region: "Africa" },
  { isoAlpha2: "KN", isoAlpha3: "KNA", name: "Saint Kitts and Nevis", nativeName: null, region: "Americas" },
  { isoAlpha2: "LC", isoAlpha3: "LCA", name: "Saint Lucia", nativeName: null, region: "Americas" },
  { isoAlpha2: "MF", isoAlpha3: "MAF", name: "Saint Martin (French part)", nativeName: null, region: "Americas" },
  { isoAlpha2: "PM", isoAlpha3: "SPM", name: "Saint Pierre and Miquelon", nativeName: null, region: "Americas" },
  { isoAlpha2: "VC", isoAlpha3: "VCT", name: "Saint Vincent and the Grenadines", nativeName: null, region: "Americas" },
  { isoAlpha2: "WS", isoAlpha3: "WSM", name: "Samoa", nativeName: null, region: "Oceania" },
  { isoAlpha2: "SM", isoAlpha3: "SMR", name: "San Marino", nativeName: null, region: "Europe" },
  { isoAlpha2: "ST", isoAlpha3: "STP", name: "Sao Tome and Principe", nativeName: null, region: "Africa" },
  { isoAlpha2: "SA", isoAlpha3: "SAU", name: "Saudi Arabia", nativeName: "السعودية", region: "Asia" },
  { isoAlpha2: "SN", isoAlpha3: "SEN", name: "Senegal", nativeName: null, region: "Africa" },
  { isoAlpha2: "RS", isoAlpha3: "SRB", name: "Serbia", nativeName: "Србија", region: "Europe" },
  { isoAlpha2: "SC", isoAlpha3: "SYC", name: "Seychelles", nativeName: null, region: "Africa" },
  { isoAlpha2: "SL", isoAlpha3: "SLE", name: "Sierra Leone", nativeName: null, region: "Africa" },
  { isoAlpha2: "SG", isoAlpha3: "SGP", name: "Singapore", nativeName: null, region: "Asia" },
  { isoAlpha2: "SX", isoAlpha3: "SXM", name: "Sint Maarten (Dutch part)", nativeName: null, region: "Americas" },
  { isoAlpha2: "SK", isoAlpha3: "SVK", name: "Slovakia", nativeName: "Slovensko", region: "Europe" },
  { isoAlpha2: "SI", isoAlpha3: "SVN", name: "Slovenia", nativeName: "Slovenija", region: "Europe" },
  { isoAlpha2: "SB", isoAlpha3: "SLB", name: "Solomon Islands", nativeName: null, region: "Oceania" },
  { isoAlpha2: "SO", isoAlpha3: "SOM", name: "Somalia", nativeName: null, region: "Africa" },
  { isoAlpha2: "ZA", isoAlpha3: "ZAF", name: "South Africa", nativeName: null, region: "Africa" },
  { isoAlpha2: "GS", isoAlpha3: "SGS", name: "South Georgia and the South Sandwich Islands", nativeName: null, region: "Antarctica" },
  { isoAlpha2: "SS", isoAlpha3: "SSD", name: "South Sudan", nativeName: null, region: "Africa" },
  { isoAlpha2: "ES", isoAlpha3: "ESP", name: "Spain", nativeName: "España", region: "Europe" },
  { isoAlpha2: "LK", isoAlpha3: "LKA", name: "Sri Lanka", nativeName: "ශ්‍රී ලංකාව", region: "Asia" },
  { isoAlpha2: "SD", isoAlpha3: "SDN", name: "Sudan", nativeName: null, region: "Africa" },
  { isoAlpha2: "SR", isoAlpha3: "SUR", name: "Suriname", nativeName: null, region: "Americas" },
  { isoAlpha2: "SJ", isoAlpha3: "SJM", name: "Svalbard and Jan Mayen", nativeName: null, region: "Europe" },
  { isoAlpha2: "SE", isoAlpha3: "SWE", name: "Sweden", nativeName: "Sverige", region: "Europe" },
  { isoAlpha2: "CH", isoAlpha3: "CHE", name: "Switzerland", nativeName: "Schweiz", region: "Europe" },
  { isoAlpha2: "SY", isoAlpha3: "SYR", name: "Syrian Arab Republic", nativeName: "سوريا", region: "Asia" },
  { isoAlpha2: "TW", isoAlpha3: "TWN", name: "Taiwan", nativeName: "台灣", region: "Asia" },
  { isoAlpha2: "TJ", isoAlpha3: "TJK", name: "Tajikistan", nativeName: null, region: "Asia" },
  { isoAlpha2: "TZ", isoAlpha3: "TZA", name: "Tanzania", nativeName: null, region: "Africa" },
  { isoAlpha2: "TH", isoAlpha3: "THA", name: "Thailand", nativeName: "ไทย", region: "Asia" },
  { isoAlpha2: "TL", isoAlpha3: "TLS", name: "Timor-Leste", nativeName: null, region: "Asia" },
  { isoAlpha2: "TG", isoAlpha3: "TGO", name: "Togo", nativeName: null, region: "Africa" },
  { isoAlpha2: "TK", isoAlpha3: "TKL", name: "Tokelau", nativeName: null, region: "Oceania" },
  { isoAlpha2: "TO", isoAlpha3: "TON", name: "Tonga", nativeName: null, region: "Oceania" },
  { isoAlpha2: "TT", isoAlpha3: "TTO", name: "Trinidad and Tobago", nativeName: null, region: "Americas" },
  { isoAlpha2: "TN", isoAlpha3: "TUN", name: "Tunisia", nativeName: "تونس", region: "Africa" },
  { isoAlpha2: "TR", isoAlpha3: "TUR", name: "Türkiye", nativeName: "Türkiye", region: "Asia" },
  { isoAlpha2: "TM", isoAlpha3: "TKM", name: "Turkmenistan", nativeName: null, region: "Asia" },
  { isoAlpha2: "TC", isoAlpha3: "TCA", name: "Turks and Caicos Islands", nativeName: null, region: "Americas" },
  { isoAlpha2: "TV", isoAlpha3: "TUV", name: "Tuvalu", nativeName: null, region: "Oceania" },
  { isoAlpha2: "UG", isoAlpha3: "UGA", name: "Uganda", nativeName: null, region: "Africa" },
  { isoAlpha2: "UA", isoAlpha3: "UKR", name: "Ukraine", nativeName: "Україна", region: "Europe" },
  { isoAlpha2: "AE", isoAlpha3: "ARE", name: "United Arab Emirates", nativeName: "الإمارات", region: "Asia" },
  { isoAlpha2: "GB", isoAlpha3: "GBR", name: "United Kingdom", nativeName: null, region: "Europe" },
  { isoAlpha2: "US", isoAlpha3: "USA", name: "United States", nativeName: null, region: "Americas" },
  { isoAlpha2: "UM", isoAlpha3: "UMI", name: "United States Minor Outlying Islands", nativeName: null, region: "Oceania" },
  { isoAlpha2: "UY", isoAlpha3: "URY", name: "Uruguay", nativeName: null, region: "Americas" },
  { isoAlpha2: "UZ", isoAlpha3: "UZB", name: "Uzbekistan", nativeName: null, region: "Asia" },
  { isoAlpha2: "VU", isoAlpha3: "VUT", name: "Vanuatu", nativeName: null, region: "Oceania" },
  { isoAlpha2: "VE", isoAlpha3: "VEN", name: "Venezuela", nativeName: null, region: "Americas" },
  { isoAlpha2: "VN", isoAlpha3: "VNM", name: "Viet Nam", nativeName: "Việt Nam", region: "Asia" },
  { isoAlpha2: "VG", isoAlpha3: "VGB", name: "Virgin Islands (British)", nativeName: null, region: "Americas" },
  { isoAlpha2: "VI", isoAlpha3: "VIR", name: "Virgin Islands (U.S.)", nativeName: null, region: "Americas" },
  { isoAlpha2: "WF", isoAlpha3: "WLF", name: "Wallis and Futuna", nativeName: null, region: "Oceania" },
  { isoAlpha2: "EH", isoAlpha3: "ESH", name: "Western Sahara", nativeName: null, region: "Africa" },
  { isoAlpha2: "YE", isoAlpha3: "YEM", name: "Yemen", nativeName: "اليمن", region: "Asia" },
  { isoAlpha2: "ZM", isoAlpha3: "ZMB", name: "Zambia", nativeName: null, region: "Africa" },
  { isoAlpha2: "ZW", isoAlpha3: "ZWE", name: "Zimbabwe", nativeName: null, region: "Africa" },
]);

/** Pure · lookup by alpha-2 code (uppercase). O(n) over 249 entries,
 *  which is cheap enough to avoid a Map and keep the module tree-shakable. */
export function findIsoCountry(alpha2: string): IsoCountry | null {
  const key = alpha2.toUpperCase();
  for (const c of ISO_COUNTRIES) if (c.isoAlpha2 === key) return c;
  return null;
}

/** Pure · UK is a documented GB mis-mapping trap. UK is NOT ISO 3166-1
 *  alpha-2 for the United Kingdom (it is "GB"); UK is reserved to the
 *  United Nations and not assigned to a country. This helper rejects
 *  "UK" explicitly so a mistaken input returns null rather than
 *  silently matching nothing. */
export function parseIsoAlpha2(input: string | null | undefined): string | null {
  if (!input) return null;
  const up = input.toUpperCase();
  if (up === "UK") return null; // trap · caller must use "GB"
  if (!/^[A-Z]{2}$/.test(up)) return null;
  return findIsoCountry(up) ? up : null;
}
