// src/lib/nex-agent/code-engine/capability-project-scaffolder.ts
//
// NEX1 · Real Project Scaffolder (Blocker Two · §6-8)
// Ledger B additive · Zero LLM · Deterministic
//
// PURPOSE
//   Take a natural-language request and produce a real runnable project on
//   disk. Not a code snippet returned in chat.
//
//   Input:  "Build me a simple booking website"
//   Output: filesystem directory containing runnable Next.js/HTML project
//
// FOUNDER INVARIANTS
//   · Physical project on disk · not a snippet
//   · Every scaffold declares its start_command · build_command · framework
//   · Template library extensible · additional project types can be added
//   · Deterministic scaffold id derived from spec + template + timestamp
//   · Zero LLM · zero external dep · uses fs primitives + template registry
//   · Fails safe when target directory exists · never overwrites silently

import { mkdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";

export const PROJECT_SCAFFOLDER_VERSION = "project-scaffolder.v1.2026-09-19";

// ── Template registry ───────────────────────────────────────────────────

export type ProjectFramework = "static-html" | "next-app-router";
export type ProjectKind = "website" | "landing" | "form" | "booking" | "portfolio" | "generic";
export type PackageManager = "npm" | "none";

export interface ProjectTemplate {
  readonly template_id: string;
  readonly display_name: string;
  readonly framework: ProjectFramework;
  readonly package_manager: PackageManager;
  readonly supported_kinds: readonly ProjectKind[];
  readonly build_command: string | null;
  readonly start_command: string;
  readonly dev_command: string;
  readonly default_port: number;
  readonly requires_install: boolean;
  readonly files: readonly {
    readonly rel_path: string;
    readonly content: string;
  }[];
}

// ── Built-in templates (deterministic · plain text) ─────────────────────

const NEXT_APP_TEMPLATE: ProjectTemplate = {
  template_id: "next-minimal.v1",
  display_name: "Next.js Minimal App",
  framework: "next-app-router",
  package_manager: "npm",
  supported_kinds: ["website", "landing", "form", "booking", "portfolio", "generic"],
  build_command: "next build",
  start_command: "next start",
  dev_command: "next dev",
  default_port: 3000,
  requires_install: true,
  files: [
    {
      rel_path: "package.json",
      content: JSON.stringify({
        name: "nex1-generated-app",
        version: "0.1.0",
        private: true,
        scripts: {
          dev: "next dev",
          build: "next build",
          start: "next start",
        },
        dependencies: {
          next: "^15.0.0",
          react: "^19.0.0",
          "react-dom": "^19.0.0",
        },
      }, null, 2) + "\n",
    },
    {
      rel_path: "next.config.mjs",
      content: `/** @type {import('next').NextConfig} */\nconst nextConfig = {};\nexport default nextConfig;\n`,
    },
    {
      rel_path: "app/layout.tsx",
      content: `export const metadata = { title: "NEX1 Generated App", description: "Generated by NEX1" };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (<html lang="en"><body>{children}</body></html>);
}
`,
    },
    {
      rel_path: "app/page.tsx",
      content: `export default function Home() {
  return (
    <main style={{ fontFamily: "system-ui", padding: "2rem", maxWidth: 720, margin: "0 auto" }}>
      <h1>Welcome</h1>
      <p>This project was generated by NEX1.</p>
    </main>
  );
}
`,
    },
    {
      rel_path: "tsconfig.json",
      content: JSON.stringify({
        compilerOptions: {
          target: "ES2022",
          lib: ["dom", "dom.iterable", "esnext"],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "preserve",
          incremental: true,
          plugins: [{ name: "next" }],
          paths: { "@/*": ["./*"] },
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
        exclude: ["node_modules"],
      }, null, 2) + "\n",
    },
    {
      rel_path: ".gitignore",
      content: "node_modules\n.next\nout\ndist\n.env\n.env.local\n",
    },
    {
      rel_path: "README.md",
      content: "# NEX1 Generated Project\n\nRun `npm install` then `npm run dev`.\n",
    },
  ],
};

const STATIC_HTML_TEMPLATE: ProjectTemplate = {
  template_id: "static-html.v1",
  display_name: "Static HTML Site",
  framework: "static-html",
  package_manager: "none",
  supported_kinds: ["website", "landing", "portfolio", "generic"],
  build_command: null,
  start_command: "npx serve .",
  dev_command: "npx serve . -l 3000",
  default_port: 3000,
  requires_install: false,
  files: [
    {
      rel_path: "index.html",
      content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>NEX1 Generated Site</title>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; max-width: 720px; margin: 3rem auto; padding: 0 1.5rem; line-height: 1.5; }
    h1 { font-size: 2rem; margin-bottom: 0.5rem; }
    p { color: #444; }
  </style>
</head>
<body>
  <h1>Welcome</h1>
  <p>This site was generated by NEX1.</p>
</body>
</html>
`,
    },
    {
      rel_path: "README.md",
      content: "# NEX1 Generated Site\n\nRun `npx serve .` to preview.\n",
    },
  ],
};

const TEMPLATES: readonly ProjectTemplate[] = Object.freeze([NEXT_APP_TEMPLATE, STATIC_HTML_TEMPLATE]);

export function listTemplates(): readonly ProjectTemplate[] {
  return TEMPLATES;
}

export function getTemplate(id: string): ProjectTemplate | null {
  return TEMPLATES.find((t) => t.template_id === id) ?? null;
}

// ── Deterministic natural-language → template selection ──────────────────
//
// Simple keyword heuristic. When the request is ambiguous, defaults to
// static-html (no install required · fast to preview).

export interface RequestClassification {
  readonly kind: ProjectKind;
  readonly framework_preference: ProjectFramework;
  readonly matched_keywords: readonly string[];
  readonly rationale: string;
}

const KEYWORD_MAP: readonly { readonly kw: string; readonly kind: ProjectKind }[] = [
  { kw: "booking", kind: "booking" },
  { kw: "book", kind: "booking" },
  { kw: "reservation", kind: "booking" },
  { kw: "form", kind: "form" },
  { kw: "contact", kind: "form" },
  { kw: "portfolio", kind: "portfolio" },
  { kw: "landing", kind: "landing" },
  { kw: "website", kind: "website" },
  { kw: "site", kind: "website" },
  { kw: "app", kind: "website" },
  { kw: "restaurant", kind: "booking" },
];

const FRAMEWORK_HINTS: readonly { readonly kw: string; readonly fw: ProjectFramework }[] = [
  { kw: "react", fw: "next-app-router" },
  { kw: "next", fw: "next-app-router" },
  { kw: "interactive", fw: "next-app-router" },
  { kw: "form", fw: "next-app-router" },
  { kw: "booking", fw: "next-app-router" },
];

export function classifyRequest(request: string): RequestClassification {
  const lower = request.toLowerCase();
  const matched: string[] = [];
  let kind: ProjectKind = "generic";
  for (const { kw, kind: k } of KEYWORD_MAP) {
    if (lower.includes(kw)) {
      matched.push(kw);
      if (kind === "generic") kind = k;
    }
  }
  let framework: ProjectFramework = "static-html";
  for (const { kw, fw } of FRAMEWORK_HINTS) {
    if (lower.includes(kw)) {
      matched.push(kw);
      framework = fw;
      break;
    }
  }
  return {
    kind,
    framework_preference: framework,
    matched_keywords: [...new Set(matched)],
    rationale: matched.length > 0
      ? `matched keywords: ${matched.join(", ")}`
      : "no keywords matched · defaulting to static-html",
  };
}

// ── Scaffolding entry ────────────────────────────────────────────────────

export interface ScaffoldInput {
  readonly natural_language_request: string;
  readonly workspace_root: string;
  readonly project_slug?: string;
  readonly template_override?: string;
  /** When true, do not touch filesystem · returns planned files only. */
  readonly dry_run?: boolean;
}

export interface ScaffoldOutcome {
  readonly ok: boolean;
  readonly project_id: string;
  readonly project_slug: string;
  readonly project_root: string;
  readonly template_id: string;
  readonly framework: ProjectFramework;
  readonly package_manager: PackageManager;
  readonly requires_install: boolean;
  readonly dev_command: string;
  readonly start_command: string;
  readonly build_command: string | null;
  readonly default_port: number;
  readonly classification: RequestClassification;
  readonly files_written: readonly string[];
  readonly files_planned: readonly string[];
  readonly refusal_reason: string | null;
  readonly created_at_iso: string;
  readonly input_digest: string;
  readonly zero_llm: true;
  readonly ledger: "B";
  readonly version: string;
}

export function scaffoldProject(input: ScaffoldInput): ScaffoldOutcome {
  const workspace_root = path.resolve(input.workspace_root);
  const classification = classifyRequest(input.natural_language_request);

  // Select template
  const template = input.template_override
    ? getTemplate(input.template_override)
    : classification.framework_preference === "next-app-router"
      ? NEXT_APP_TEMPLATE
      : STATIC_HTML_TEMPLATE;

  const nowIso = new Date().toISOString();
  const project_slug = input.project_slug ?? deriveSlug(input.natural_language_request, nowIso);
  const project_id = createHash("sha256")
    .update(`${project_slug}|${template?.template_id ?? "none"}|${nowIso}`)
    .digest("hex")
    .slice(0, 16);
  const project_root = path.join(workspace_root, project_slug);

  if (!template) {
    return refuse(project_id, project_slug, project_root, `unknown_template:${input.template_override}`, classification, nowIso, input);
  }

  if (input.dry_run !== true) {
    if (existsSync(project_root)) {
      return refuse(project_id, project_slug, project_root, "project_root_already_exists", classification, nowIso, input, template);
    }
    mkdirSync(project_root, { recursive: true });
  }

  const files_written: string[] = [];
  const files_planned: string[] = template.files.map((f) => f.rel_path);
  if (input.dry_run !== true) {
    for (const f of template.files) {
      const abs = path.join(project_root, f.rel_path);
      mkdirSync(path.dirname(abs), { recursive: true });
      writeFileSync(abs, f.content);
      files_written.push(f.rel_path);
    }
  }

  return {
    ok: true,
    project_id,
    project_slug,
    project_root,
    template_id: template.template_id,
    framework: template.framework,
    package_manager: template.package_manager,
    requires_install: template.requires_install,
    dev_command: template.dev_command,
    start_command: template.start_command,
    build_command: template.build_command,
    default_port: template.default_port,
    classification,
    files_written,
    files_planned,
    refusal_reason: null,
    created_at_iso: nowIso,
    input_digest: createHash("sha256").update(input.natural_language_request + template.template_id).digest("hex").slice(0, 16),
    zero_llm: true,
    ledger: "B",
    version: PROJECT_SCAFFOLDER_VERSION,
  };
}

function deriveSlug(request: string, ts: string): string {
  const base = request
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40) || "project";
  const hash = createHash("sha256").update(request + ts).digest("hex").slice(0, 6);
  return `${base}-${hash}`;
}

function refuse(
  project_id: string,
  project_slug: string,
  project_root: string,
  reason: string,
  classification: RequestClassification,
  nowIso: string,
  input: ScaffoldInput,
  template?: ProjectTemplate,
): ScaffoldOutcome {
  return {
    ok: false,
    project_id,
    project_slug,
    project_root,
    template_id: template?.template_id ?? "none",
    framework: template?.framework ?? "static-html",
    package_manager: template?.package_manager ?? "none",
    requires_install: false,
    dev_command: template?.dev_command ?? "",
    start_command: template?.start_command ?? "",
    build_command: template?.build_command ?? null,
    default_port: template?.default_port ?? 3000,
    classification,
    files_written: [],
    files_planned: template?.files.map((f) => f.rel_path) ?? [],
    refusal_reason: reason,
    created_at_iso: nowIso,
    input_digest: createHash("sha256").update(input.natural_language_request).digest("hex").slice(0, 16),
    zero_llm: true,
    ledger: "B",
    version: PROJECT_SCAFFOLDER_VERSION,
  };
}

// ── Post-scaffold sanity: does the project look runnable? ────────────────
//
// Deterministic filesystem-only check · never runs the project.

export interface RunnabilityCheck {
  readonly runnable: boolean;
  readonly reasons: readonly string[];
}

export function checkRunnable(scaffold: ScaffoldOutcome): RunnabilityCheck {
  const reasons: string[] = [];
  if (!scaffold.ok) reasons.push(`scaffold_not_ok:${scaffold.refusal_reason}`);
  if (!existsSync(scaffold.project_root)) reasons.push("project_root_missing");
  if (scaffold.framework === "next-app-router") {
    if (!existsSync(path.join(scaffold.project_root, "package.json"))) reasons.push("missing_package_json");
    if (!existsSync(path.join(scaffold.project_root, "app/page.tsx"))) reasons.push("missing_app_page");
  } else if (scaffold.framework === "static-html") {
    if (!existsSync(path.join(scaffold.project_root, "index.html"))) reasons.push("missing_index_html");
  }
  return { runnable: reasons.length === 0, reasons };
}
