// src/lib/nex-agent/code-engine/capability-test-generator.ts
//
// NEX1 · Test Generator · takes a specification, writes a real vitest test file
// Ledger B additive · Zero LLM · Deterministic template-based generation.
//
// FOUNDER PRINCIPLES
//   · Never fabricate expected values · refuses when spec is UNRESOLVED
//   · Every generated test cites the spec_id it came from
//   · Deterministic: same spec → same generated bytes
//   · Zero LLM · pure string composition

import { createHash } from "node:crypto";
import type { SpecificationRepresentation } from "./capability-spec-representation";

export const TEST_GENERATOR_VERSION = "test-generator.v1.2026-09-19";

// ── Result ────────────────────────────────────────────────────────────

export interface GeneratedTestFile {
  readonly ok: boolean;
  readonly rel_path: string;
  readonly content: string;
  readonly bytes: number;
  readonly content_hash: string;
  readonly test_case_count: number;
  readonly spec_id: string;
  readonly refusal_reason: string | null;
  readonly evidence_signals: readonly string[];
  readonly caller_must_decide: true;
  readonly zero_llm: true;
  readonly ledger: "B";
  readonly version: string;
}

// ── Input ─────────────────────────────────────────────────────────────

export interface GenerateTestFileInput {
  readonly specification: SpecificationRepresentation;
  readonly test_file_rel_path?: string;      // e.g. "src/foo.test.ts"
  readonly import_source_rel_path?: string;  // e.g. "./foo" for import statement
  readonly framework?: "vitest" | "jest";    // default vitest
}

// ── Public entry ─────────────────────────────────────────────────────

export function generateTestFile(input: GenerateTestFileInput): GeneratedTestFile {
  const spec = input.specification;
  const signals: string[] = [
    `spec_id=${spec.spec_id}`,
    `resolution_status=${spec.resolution_status}`,
    `expected_behaviours=${spec.expected_behaviours.length}`,
  ];

  // Refuse to fabricate: spec must be RESOLVED with at least one determinable behaviour
  if (spec.resolution_status !== "RESOLVED") {
    return refuse(spec.spec_id, `spec_not_resolved:${spec.resolution_status}`, signals);
  }
  const determinable = spec.expected_behaviours.filter((eb) => eb.determinable);
  if (determinable.length === 0) {
    return refuse(spec.spec_id, "no_determinable_expected_behaviour", signals);
  }

  const framework = input.framework ?? "vitest";
  const rel_path = input.test_file_rel_path ?? "src/generated.spec.test.ts";
  const import_source = input.import_source_rel_path ?? "./generated";

  // Compose · deterministic string layout
  const lines: string[] = [];
  lines.push(`// AUTO-GENERATED · spec_id=${spec.spec_id} · ${TEST_GENERATOR_VERSION}`);
  lines.push(`// Every assertion below cites an expected_behaviour with source="founder" in the spec.`);
  lines.push(`// Zero LLM · deterministic · refuses to invent expected values.`);
  lines.push(``);
  lines.push(`import { describe, it, expect } from "${framework}";`);

  // Import subject symbols (deduplicated)
  const subjects = [...new Set(determinable.map((eb) => eb.subject).filter((s): s is string => !!s))];
  if (subjects.length > 0) {
    lines.push(`import { ${subjects.join(", ")} } from "${import_source}";`);
  }
  lines.push(``);
  lines.push(`describe("generated · spec=${spec.spec_id}", () => {`);

  let case_count = 0;
  for (const eb of determinable) {
    if (!eb.subject) continue;
    // Only trust behaviours the spec representation marked determinable · never fabricate
    const inputRepr = renderInputCall(eb.input_arguments ?? []);
    const expectedRepr = renderExpected(eb.outcome_value, eb.outcome_type);
    const testDescription = `${eb.subject}(${inputRepr}) → ${expectedRepr}`;
    lines.push(`  it(${JSON.stringify(testDescription)}, () => {`);
    lines.push(`    // spec citation · expected_value from founder-stated spec ONLY`);
    lines.push(`    expect(${eb.subject}(${inputRepr})).${assertionOp(eb.outcome_type)}(${expectedRepr});`);
    lines.push(`  });`);
    case_count += 1;
  }
  lines.push(`});`);
  lines.push(``);

  const content = lines.join("\n");
  const content_hash = createHash("sha256").update(content).digest("hex").slice(0, 16);

  signals.push(`test_cases=${case_count}`);
  signals.push(`framework=${framework}`);

  return {
    ok: true,
    rel_path,
    content,
    bytes: content.length,
    content_hash,
    test_case_count: case_count,
    spec_id: spec.spec_id,
    refusal_reason: null,
    evidence_signals: signals,
    caller_must_decide: true,
    zero_llm: true,
    ledger: "B",
    version: TEST_GENERATOR_VERSION,
  };
}

function refuse(spec_id: string, reason: string, signals: readonly string[]): GeneratedTestFile {
  return {
    ok: false,
    rel_path: "",
    content: "",
    bytes: 0,
    content_hash: "",
    test_case_count: 0,
    spec_id,
    refusal_reason: reason,
    evidence_signals: signals,
    caller_must_decide: true,
    zero_llm: true,
    ledger: "B",
    version: TEST_GENERATOR_VERSION,
  };
}

function renderInputCall(inputs: readonly { readonly value: unknown; readonly type: string | null }[]): string {
  return inputs.map((i) => renderLiteral(i.value, i.type)).join(", ");
}

function renderExpected(value: unknown, type: string | null): string {
  return renderLiteral(value, type);
}

function renderLiteral(value: unknown, type: string | null): string {
  if (value === null) return "null";
  if (value === undefined) return "undefined";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return String(value);
  if (Array.isArray(value)) return JSON.stringify(value);
  if (typeof value === "object") return JSON.stringify(value);
  return JSON.stringify(String(value));
}

function assertionOp(type: string | null): "toBe" | "toEqual" {
  // Primitive types use toBe · objects/arrays use toEqual
  if (type === "string" || type === "number" || type === "boolean" || type === null) return "toBe";
  return "toEqual";
}
