// src/lib/nex-agent/code-engine/adapters/template-only.ts
//
// NEX1's IDENTITY-FLOOR adapter · deterministic pure TypeScript · zero inference.
//
// Constitution Amendment 1: this is not a fallback. It is the adapter that
// defines NEX1's own coding capability without any model. Every synthesis path
// here is a rule NEX1 knows on its own · not something generated by a language
// model. Removing every other adapter leaves NEX1 with this one · and NEX1
// still functions.
//
// Supported synthesis kinds (deterministic · no LLM):
//   · scaffold_ts_module   — create a new TS module from a structured spec
//   · add_jsdoc            — insert a JSDoc block above a named symbol
//   · add_import           — add an import declaration if not already present

import type {
  Nex1AdapterCapabilities,
  Nex1IntentKind,
  Nex1ReasoningAdapter,
  Nex1ReasoningRequest,
  Nex1ReasoningResponse,
  TemplateDirective,
} from "../types";
import { NEX1_ENGINE_ERRORS } from "../types";

const ID = "template-only";
const SUPPORTED_INTENTS: readonly Nex1IntentKind[] = [
  "add_feature",
  "refactor",
  "add_test",
  "add_scaffold",
  "add_jsdoc",
];

export const TEMPLATE_ONLY_ID = ID;

/**
 * The identity-floor adapter. Always available. Always deterministic.
 */
export const TemplateOnlyAdapter: Nex1ReasoningAdapter = {
  id: ID,
  deterministic: true,

  async isAvailable(): Promise<boolean> {
    return true;
  },

  capabilities(): Nex1AdapterCapabilities {
    return {
      deterministic: true,
      supported_intents: SUPPORTED_INTENTS,
      network_egress: "none",
      declared_max_context_bytes: 200_000,
    };
  },

  async reason(req: Nex1ReasoningRequest): Promise<Nex1ReasoningResponse> {
    const started = Date.now();
    const directive = req.template_directive;
    if (!directive) {
      return {
        ok: false,
        code: NEX1_ENGINE_ERRORS.diff_malformed,
        reason: "template-only adapter requires a template_directive · NEX1 must compose one",
      };
    }
    const inScope = (path: string) => req.context.declared_scope.includes(path);
    try {
      let diff: string;
      let rationale: string;
      switch (directive.kind) {
        case "scaffold_ts_module": {
          if (!inScope(directive.target_path)) {
            return {
              ok: false,
              code: NEX1_ENGINE_ERRORS.scope_violation,
              reason: `target_path ${directive.target_path} is not in declared_scope`,
            };
          }
          diff = synthesiseScaffoldDiff(directive);
          rationale = `Scaffolded TS module at ${directive.target_path} · purpose: ${directive.module_purpose}`;
          break;
        }
        case "add_jsdoc": {
          if (!inScope(directive.target_path)) {
            return {
              ok: false,
              code: NEX1_ENGINE_ERRORS.scope_violation,
              reason: `target_path ${directive.target_path} is not in declared_scope`,
            };
          }
          const slice = req.context.file_slices.find((s) => s.path === directive.target_path);
          if (!slice) {
            return {
              ok: false,
              code: NEX1_ENGINE_ERRORS.diff_malformed,
              reason: `add_jsdoc requires a file_slice for ${directive.target_path}`,
            };
          }
          const result = synthesiseAddJsdoc(slice.content, directive.target_symbol, directive.summary);
          if (!result.ok) {
            return { ok: false, code: NEX1_ENGINE_ERRORS.diff_malformed, reason: result.reason };
          }
          diff = renderUnifiedDiff(directive.target_path, slice.content, result.next);
          rationale = `Added JSDoc @summary to ${directive.target_symbol} in ${directive.target_path}`;
          break;
        }
        case "add_import": {
          if (!inScope(directive.target_path)) {
            return {
              ok: false,
              code: NEX1_ENGINE_ERRORS.scope_violation,
              reason: `target_path ${directive.target_path} is not in declared_scope`,
            };
          }
          // Sprint 1 hardening (2026-09-12): add_import must only accept an
          // actual import statement. Previously it prepended arbitrary text,
          // which Challenge 3.B exposed as a real defect. NEX1's engine
          // now rejects any import_spec that is not a syntactically valid
          // single-line import declaration.
          if (!isValidImportSpec(directive.import_spec)) {
            return {
              ok: false,
              code: NEX1_ENGINE_ERRORS.diff_malformed,
              reason: `add_import.import_spec must be a valid import statement · got: ${directive.import_spec.slice(0, 120)}`,
            };
          }
          const slice = req.context.file_slices.find((s) => s.path === directive.target_path);
          if (!slice) {
            return {
              ok: false,
              code: NEX1_ENGINE_ERRORS.diff_malformed,
              reason: `add_import requires a file_slice for ${directive.target_path}`,
            };
          }
          if (slice.content.includes(directive.import_spec)) {
            return {
              ok: true,
              result: {
                adapter_id: ID,
                model_id: null,
                model_version: null,
                proposed_diff: "",
                rationale: `Import ${directive.import_spec} already present · no-op`,
                confidence: 1,
                tokens_in: 0,
                tokens_out: 0,
                latency_ms: Date.now() - started,
                deterministic: true,
                adapter_scope: "code_proposal_only",
              },
            };
          }
          const next = `${directive.import_spec}\n${slice.content}`;
          diff = renderUnifiedDiff(directive.target_path, slice.content, next);
          rationale = `Prepended import ${directive.import_spec} to ${directive.target_path}`;
          break;
        }
        default: {
          // Sprint 2: semantic-modification directives are handled by the
          // AST semantic adapter. Template-only returns "not-handled" so the
          // registry can try the next adapter.
          return {
            ok: false,
            code: NEX1_ENGINE_ERRORS.reasoning_not_bound,
            reason: `template-only does not handle directive kind '${(directive as { kind: string }).kind}' · try a semantic adapter`,
          };
        }
      }
      return {
        ok: true,
        result: {
          adapter_id: ID,
          model_id: null,
          model_version: null,
          proposed_diff: diff,
          rationale,
          confidence: 1,
          tokens_in: 0,
          tokens_out: 0,
          latency_ms: Date.now() - started,
          deterministic: true,
          adapter_scope: "code_proposal_only",
        },
      };
    } catch (e) {
      return {
        ok: false,
        code: NEX1_ENGINE_ERRORS.diff_malformed,
        reason: e instanceof Error ? e.message.slice(0, 200) : "template synthesis failed",
      };
    }
  },
};

// ─── Synthesisers · pure functions · no side effects ───────────────

/**
 * @summary Return true iff `spec` is a single-line ES-module import statement.
 * Accepts: default · named · namespace · side-effect · type-only.
 * Rejects: comments · arbitrary text · multi-line · dynamic import calls.
 */
export function isValidImportSpec(spec: string): boolean {
  if (typeof spec !== "string") return false;
  const s = spec.trim();
  if (s.length === 0) return false;
  if (s.includes("\n") || s.includes("\r")) return false;
  // Named / default / namespace / type-only · with `from "path"`
  const withFrom = /^import(\s+type)?\s+(?:[*{]|[\w$]+|\{[^}]*\}|\*\s+as\s+[\w$]+|[\w$]+\s*,\s*\{[^}]*\}|[\w$]+\s*,\s*\*\s+as\s+[\w$]+)[^;\n]*\s+from\s+["'][^"'\n]+["']\s*;?$/;
  // Side-effect only: import "module";
  const sideEffect = /^import\s+["'][^"'\n]+["']\s*;?$/;
  return withFrom.test(s) || sideEffect.test(s);
}

function synthesiseScaffoldDiff(d: Extract<TemplateDirective, { kind: "scaffold_ts_module" }>): string {
  const lines: string[] = [];
  lines.push(`// ${d.target_path}`);
  lines.push(`//`);
  lines.push(`// ${d.module_purpose}`);
  lines.push(`//`);
  lines.push(`// Authored by NEX1 via the template-only identity-floor adapter.`);
  lines.push("");
  for (const c of d.exported_constants ?? []) {
    if (c.annotation) lines.push(`/** ${c.annotation} */`);
    lines.push(`export const ${c.name} = ${c.value_literal};`);
    lines.push("");
  }
  const body = lines.join("\n").replace(/\n{3,}/g, "\n\n");
  return renderUnifiedDiff(d.target_path, "", body);
}

function synthesiseAddJsdoc(
  content: string,
  symbol: string,
  summary: string,
): { ok: true; next: string } | { ok: false; reason: string } {
  const lines = content.split(/\r?\n/);
  const targetRe = new RegExp(`^\\s*export\\s+(?:async\\s+)?function\\s+${symbol}\\b`);
  const targetIdx = lines.findIndex((l) => targetRe.test(l));
  if (targetIdx === -1) {
    return { ok: false, reason: `symbol ${symbol} not found as exported function` };
  }
  // Do not double-add
  if (targetIdx > 0 && /^\s*\*\//.test(lines[targetIdx - 1] ?? "")) {
    return { ok: false, reason: `JSDoc already present above ${symbol}` };
  }
  const doc = ["/**", ` * @summary ${summary}`, " */"];
  const next = [...lines.slice(0, targetIdx), ...doc, ...lines.slice(targetIdx)].join("\n");
  return { ok: true, next };
}

/**
 * Minimal unified-diff renderer for whole-file replacement.
 * Sufficient for Sprint 1 · a more precise line-level differ can be added later
 * without changing the adapter interface.
 */
function renderUnifiedDiff(path: string, before: string, after: string): string {
  const beforeLines = before === "" ? [] : before.split(/\r?\n/);
  const afterLines = after.split(/\r?\n/);
  const header = [
    `--- a/${path}`,
    `+++ b/${path}`,
    `@@ -${beforeLines.length === 0 ? "0,0" : `1,${beforeLines.length}`} +1,${afterLines.length} @@`,
  ];
  const body: string[] = [];
  for (const l of beforeLines) body.push(`-${l}`);
  for (const l of afterLines) body.push(`+${l}`);
  return [...header, ...body].join("\n") + "\n";
}
