// src/lib/nex/master-ai/intelligence-loops.ts
//
// NEX Master AI Engineer · Failure→Research + Observation→Improvement loops
// §13 §14 · Philip 2026-09-07 · AUTHORIZE
//
// These are the WIRING primitives that turn separate ledgers into a
// living learning loop. They do NOT execute promotions. They do NOT
// modify observed agents. They only ADD records to Master AI's own
// ledgers (research queue · knowledge · Philip claims).
//
// Every proposal generated by an observation still enters M7's
// AWAITING_APPROVAL queue · founder authority remains the sole promote
// gate (§30).

import { listCurrentPatterns, linkPatternToImprovement } from "./failure-intelligence";
import { readAllHealthReports } from "./observatory";
import { enqueueResearchQuery, listQueries } from "./research-engine";
import { computePriority } from "./research-priority";
import { recordKnowledge } from "./knowledge-ledger";
import { emitClaim } from "./philip-intelligence";
import type { MasterAgentId } from "./types";

// ─── Failure → Research loop (§13) ──────────────────────────────────

/** For every unaddressed failure pattern above threshold, enqueue a
 *  research query targeted at understanding root cause. Returns the
 *  new queries created (empty if nothing above threshold). */
export function driveFailurePatternResearch(input: {
  min_occurrence_threshold?: number;
  created_by: string;
}): { queries_created: number; queries: Array<{ query_id: string; pattern_key: string; score: number }> } {
  const threshold = input.min_occurrence_threshold ?? 2;
  const patterns = listCurrentPatterns()
    .filter((p) => p.occurrence_count >= threshold)
    .filter((p) => !p.candidate_improvement_slug);

  const created: Array<{ query_id: string; pattern_key: string; score: number }> = [];
  const existingQuestions = new Set(listQueries().map((q) => q.question));

  for (const p of patterns) {
    const question = `What is the root cause of the failure pattern '${p.representative_reason.slice(0, 120)}' seen ${p.occurrence_count} times across ${p.affected_agents.length} agent(s)?`;
    if (existingQuestions.has(question)) continue;

    // Priority is deterministic: recurrence drives urgency + impact
    const priority = computePriority({
      question,
      driver: "AGENT_FAILURE",
      components: {
        impact: Math.min(10, 3 + p.affected_agents.length),
        urgency: Math.min(10, 3 + Math.floor(p.occurrence_count / 3)),
        confidence_in_signal: p.occurrence_count >= 5 ? 8 : 5,
        recurrence_count: p.occurrence_count,
        expected_benefit: 6,
        cost_estimate: 3,
        risk_estimate: 2,
        complexity_estimate: 5,
      },
    });

    const q = enqueueResearchQuery({
      question,
      target_source_slugs: [],                    // no sources yet · adapters register separately
      priority: Math.round(priority.score),
      created_by: input.created_by,
    });

    // Provisional link so we don't re-enqueue on next tick
    linkPatternToImprovement({
      pattern_key: p.pattern_key,
      candidate_improvement_slug: `research_target:${q.query_id.slice(0, 8)}`,
    });

    created.push({ query_id: q.query_id, pattern_key: p.pattern_key, score: priority.score });
  }
  return { queries_created: created.length, queries: created };
}

// ─── Observation → Improvement loop (§14) ────────────────────────────

/** Scan observatory reports · detect agents that have been IDLE for
 *  the entire window · surface them as opportunities via Philip
 *  Intelligence claims (INFERENCE with uncertainty note). Does NOT
 *  create capability proposals · that decision belongs to §15 which
 *  requires actual reusable-capability evidence. */
export function driveObservationOpportunities(input: {
  window_hours?: number;
  now?: number;
  created_by: string;
}): { opportunities_emitted: number } {
  const now = input.now ?? Date.now();
  const winStart = now - (input.window_hours ?? 24) * 60 * 60 * 1000;
  const winIso = new Date(winStart).toISOString();
  const reports = readAllHealthReports().filter((r) => r.timestamp_iso >= winIso);
  const byAgent = new Map<MasterAgentId, Set<string>>();
  for (const r of reports) {
    const s = byAgent.get(r.agent_id) ?? new Set<string>();
    s.add(r.derived_health);
    byAgent.set(r.agent_id, s);
  }

  let emitted = 0;
  for (const [agent, states] of byAgent) {
    if (states.size === 1 && states.has("IDLE")) {
      // Record structured knowledge · never overwrites, always appends
      recordKnowledge({
        category: "OPPORTUNITY_SIGNAL",
        agent_id: agent,
        authority_tier: "TIER_3",
        content: {
          slug: `stagnation:${agent}`,
          detail: `${agent} has been IDLE across all observation windows in the last ${input.window_hours ?? 24}h`,
          window_iso: winIso,
        },
        supersedes: null,
        provenance: { source: "master_ai_observatory", source_ref: null },
        created_by: input.created_by,
      });
      // Emit Philip Intelligence claim as INFERENCE with uncertainty note
      emitClaim({
        classification: "INFERENCE",
        statement: `${agent} may benefit from additional work · has been IDLE across observed windows`,
        supporting_refs: [`observatory:${agent}`],
        uncertainty_note: `${input.window_hours ?? 24}h window may be too short for definitive stagnation claim`,
        time_horizon: "NEAR_TERM",
        category: "OPPORTUNITY",
      });
      emitted++;
    }
  }
  return { opportunities_emitted: emitted };
}
