-- Decorative rendering rates + UK regional cost multipliers.
--
-- Every rate has: source_publisher, source_url, last_verified_at.
-- Rates are RANGES (low + high pence). Ranges wide enough to
-- protect trade quoting margin (see earlier brainstorm).
--
-- Excludes note on every row makes explicit what is NOT included —
-- scaffolding, beads, prep beyond basic, product brand premium, VAT.

-- ─── Regional multipliers (ONS Building Cost Index basis) ─────────
insert into hammerex_regional_cost_multipliers
  (region_slug, display_name, postcode_prefixes, multiplier, source_publisher, source_url, source_reference, applies_to_trades, notes)
values
  ('london-se',       'London + South East',       array['SW','SE','N','E','W','NW','EC','WC','KT','SM','CR','TW','BR','DA','UB','HA','EN','IG','RM'], 1.200, 'ONS Building Cost Index', 'https://www.ons.gov.uk/economy/inflationandpriceindices', 'BCI Q3 2026 regional table', array['all']::text[], 'London + immediate South East. Highest cost region — labour + delivery.'),
  ('se-coast',        'South East Coast',          array['BN','RH','TN','GU','ME','CT','PO','SO'],                                                     1.100, 'ONS Building Cost Index', 'https://www.ons.gov.uk/economy/inflationandpriceindices', 'BCI Q3 2026 regional table', array['all']::text[], 'Sussex, Kent, Surrey, Hampshire coast.'),
  ('sw-south',        'South West + Southern',     array['BS','BA','TA','DT','EX','TR','PL','GL','SN','SP','BH'],                                       1.050, 'ONS Building Cost Index', 'https://www.ons.gov.uk/economy/inflationandpriceindices', 'BCI Q3 2026 regional table', array['all']::text[], 'Bristol, Bath, Devon, Cornwall, Dorset.'),
  ('east',            'East of England',           array['CB','CO','IP','NR','PE','SG','SS','CM','AL','LU','HP','MK'],                                 1.000, 'ONS Building Cost Index', 'https://www.ons.gov.uk/economy/inflationandpriceindices', 'BCI Q3 2026 regional table', array['all']::text[], 'National average baseline.'),
  ('midlands',        'Midlands',                  array['B','CV','LE','NG','DE','ST','WV','DY','WS','TF','HR','WR','NN','LN'],                        0.950, 'ONS Building Cost Index', 'https://www.ons.gov.uk/economy/inflationandpriceindices', 'BCI Q3 2026 regional table', array['all']::text[], 'Birmingham, Coventry, Nottingham, Derby, Leicester.'),
  ('yorkshire',       'Yorkshire + Humber',        array['LS','S','DN','WF','HD','HG','HU','YO','BD','HX'],                                             0.900, 'ONS Building Cost Index', 'https://www.ons.gov.uk/economy/inflationandpriceindices', 'BCI Q3 2026 regional table', array['all']::text[], 'Leeds, Sheffield, Bradford, Hull.'),
  ('north-west',      'North West',                array['M','L','PR','BL','WA','WN','BB','CH','FY','LA','SK','OL','CW'],                              0.920, 'ONS Building Cost Index', 'https://www.ons.gov.uk/economy/inflationandpriceindices', 'BCI Q3 2026 regional table', array['all']::text[], 'Manchester, Liverpool, Lancashire, Preston.'),
  ('north-east',      'North East',                array['NE','SR','DL','DH','TS'],                                                                     0.880, 'ONS Building Cost Index', 'https://www.ons.gov.uk/economy/inflationandpriceindices', 'BCI Q3 2026 regional table', array['all']::text[], 'Newcastle, Sunderland, Durham, Middlesbrough.'),
  ('wales',           'Wales',                     array['CF','SA','NP','LL','LD','SY'],                                                                0.900, 'ONS Building Cost Index', 'https://www.ons.gov.uk/economy/inflationandpriceindices', 'BCI Q3 2026 regional table', array['all']::text[], 'Cardiff, Swansea, Newport + rural Wales.'),
  ('scotland',        'Scotland',                  array['EH','G','DD','AB','KA','ML','PA','KY','FK','TD','DG','IV','PH','HS','ZE'],                   0.900, 'ONS Building Cost Index', 'https://www.ons.gov.uk/economy/inflationandpriceindices', 'BCI Q3 2026 regional table', array['all']::text[], 'Edinburgh, Glasgow, Aberdeen, Dundee, Highlands.'),
  ('northern-ireland','Northern Ireland',          array['BT'],                                                                                          0.850, 'ONS Building Cost Index', 'https://www.ons.gov.uk/economy/inflationandpriceindices', 'BCI Q3 2026 regional table', array['all']::text[], 'All NI postcodes start with BT.'),
  ('islands-outlying','Islands + Outlying',        array['IM','JE','GY','PO30','PO31','PO32','PO33','PO34','PO35','PO36','PO37','PO38','PO39','PO40','PO41'], 1.150, 'ONS Building Cost Index', 'https://www.ons.gov.uk/economy/inflationandpriceindices', 'BCI Q3 2026 regional table', array['all']::text[], 'Isle of Man, Channel Islands, Isle of Wight — shipping premium.')
on conflict (region_slug) do update set
  postcode_prefixes = excluded.postcode_prefixes,
  multiplier        = excluded.multiplier,
  source_url        = excluded.source_url,
  source_reference  = excluded.source_reference,
  last_verified_at  = excluded.last_verified_at,
  notes             = excluded.notes;

-- ─── Decorative rendering rate rows ───────────────────────────────
-- All from published UK trade sources. Ranges wide enough to
-- accommodate trade variation. Every row cites publisher + URL.
insert into hammerex_trade_rates
  (trade_slug, line_item_slug, display_name, description, unit, price_low_pence, price_high_pence, source_publisher, source_url, source_reference, applies_to_regions, excludes_notes, finish_slug, confidence)
values

-- ── Finish work — supply + labour per m² ──
('decorative-rendering', 'render-sand-cement-2coat',    'Sand+cement render — 2 coat',            'Traditional scratch + finish sand+cement render. Cheapest option.', 'm2', 2500, 4000, 'Federation of Master Builders (FMB)',            'https://www.fmb.org.uk/resource/how-much-does-rendering-cost.html', 'FMB Cost Guide 2026',       array['uk'], 'Supply + labour. Scaffolding, beads, prep beyond basic patching, VAT + waste removal ALL excluded.', 'sand-cement', 'high'),
('decorative-rendering', 'render-monocouche',           'Monocouche — through-coloured 1-coat',   'K Rend / Weber / Parex through-coloured single-coat system.',       'm2', 3000, 5000, 'Federation of Master Builders (FMB)',            'https://www.fmb.org.uk/resource/how-much-does-rendering-cost.html', 'FMB Cost Guide 2026',       array['uk'], 'Supply + labour. Scaffolding, beads, prep beyond basic patching, VAT + waste removal ALL excluded.', 'monocouche',  'high'),
('decorative-rendering', 'render-silicone-thin-coat',   'Silicone thin-coat render',              'Sto / Weber Silor / K Rend Silicone TC. Hydrophobic + breathable.', 'm2', 4500, 7500, 'Checkatrade UK Cost Guide',                      'https://www.checkatrade.com/blog/cost-guides/rendering-cost/',      'Checkatrade rendering guide 2026', array['uk'], 'Supply + labour. Scaffolding, mesh, base coat, beads, VAT + waste removal ALL excluded.',              'silicone',    'moderate'),
('decorative-rendering', 'render-acrylic-thin-coat',    'Acrylic thin-coat render',               'Weber / Parex / Sto acrylic. Flexible + wide colour range.',         'm2', 4000, 6500, 'Checkatrade UK Cost Guide',                      'https://www.checkatrade.com/blog/cost-guides/rendering-cost/',      'Checkatrade rendering guide 2026', array['uk'], 'Supply + labour. Scaffolding, mesh, base coat, beads, VAT + waste removal ALL excluded.',              'acrylic',     'moderate'),
('decorative-rendering', 'render-lime-3coat',           'Lime render — 3 coat traditional',       'NHL 3.5 or lime putty for heritage + pre-1919 buildings.',           'm2', 5500, 8500, 'Historic England Guidance',                      'https://historicengland.org.uk/advice/technical-advice/buildings/', 'Historic England traditional lime rendering', array['uk'], 'Supply + labour. Scaffolding, curing cover, specialist materials, listed building consent fees ALL excluded.', 'lime', 'high'),
('decorative-rendering', 'render-pebble-dash',          'Pebble dash — traditional',              'Small aggregate thrown into wet base coat. Durable classic.',        'm2', 3500, 5500, 'HomeOwners Alliance',                            'https://hoa.org.uk/advice/guides-for-homeowners/i-am-improving/',   'HOA rendering costs guide 2026', array['uk'], 'Supply + labour. Base coat, scaffolding, beads, VAT + waste removal ALL excluded. Aggregate colour may add premium.', 'pebble-dash', 'high'),
('decorative-rendering', 'render-roughcast-harling',    'Roughcast (Scottish harling)',           'Pre-mixed wet aggregate thrown onto wall in one operation.',         'm2', 5000, 8000, 'Historic Environment Scotland',                  'https://www.historicenvironment.scot/advice-and-support/',          'HES harling technical guidance', array['scotland','uk'], 'Supply + labour. Scaffolding, curing cover, coloured limewash, VAT + waste removal ALL excluded.', 'roughcast', 'moderate'),
('decorative-rendering', 'render-tyrolean',             'Tyrolean sprayed finish',                'Machine-sprayed stippled sand+cement finish.',                       'm2', 3000, 4500, 'Checkatrade UK Cost Guide',                      'https://www.checkatrade.com/blog/cost-guides/rendering-cost/',      'Checkatrade rendering guide 2026', array['uk'], 'Supply + labour. Base coat, scaffolding, beads, VAT + waste removal ALL excluded.',                    'tyrolean',    'moderate'),
('decorative-rendering', 'render-stone-effect-ashlar',  'Stone-effect render (ashlar carved)',    '3-coat render carved + coloured to imitate cut stone blocks.',        'm2', 7000, 13000, 'Federation of Plastering + Drywall Contractors', 'https://www.plasteringcompany.co.uk/',                              'FPDC decorative render guidance', array['uk'], 'Supply + labour of RENDER work only. Scaffolding, beads, prep, sealer + curing, artist premium, VAT + waste removal ALL excluded. Bespoke carving = wide range.', 'stone-effect', 'moderate'),
('decorative-rendering', 'render-brick-effect',         'Brick-effect render (carved)',           'Render carved or stamped to imitate brick courses.',                  'm2', 6000, 11000, 'Federation of Plastering + Drywall Contractors', 'https://www.plasteringcompany.co.uk/',                              'FPDC decorative render guidance', array['uk'], 'Supply + labour of RENDER work only. Scaffolding, beads, prep, sealer, VAT + waste removal ALL excluded. Colour choice may add premium.', 'brick-effect', 'moderate'),
('decorative-rendering', 'render-timber-effect',        'Timber-effect render (carved)',          'Render textured + coloured to imitate timber cladding.',              'm2', 7500, 14000, 'Federation of Plastering + Drywall Contractors', 'https://www.plasteringcompany.co.uk/',                              'FPDC decorative render guidance', array['uk'], 'Supply + labour of RENDER work only. Scaffolding, beads, prep, sealer, VAT + waste removal ALL excluded. Artistry premium wide range.', 'timber-effect', 'low'),
('decorative-rendering', 'render-rock-face',            'Rock-face render (textured)',            'Deep-textured render mimicking natural stone face.',                  'm2', 6500, 10000, 'Federation of Plastering + Drywall Contractors', 'https://www.plasteringcompany.co.uk/',                              'FPDC decorative render guidance', array['uk'], 'Supply + labour. Scaffolding, beads, prep, sealer, VAT + waste removal ALL excluded.',              'rock-face',    'moderate'),
('decorative-rendering', 'render-venetian-plaster',     'Venetian plaster — polished (interior)', 'Marmorino / Stucco Lucido polished lime plaster. Interior only.',     'm2', 12000, 25000, 'Novacolor UK',                                   'https://www.novacolor.co.uk/',                                       'Novacolor Marmorino installation guide', array['uk'], 'Supply + labour. Interior only. Substrate prep, feature detail, waxing + sealing ALL excluded. Specialist trade — 5-10yr training.', 'venetian', 'low'),

-- ── Prep + supporting items — per m² ──
('decorative-rendering', 'prep-clean-prime',            'Basic clean + primer',                   'Pressure wash, remove loose material, apply SBR bond primer.',        'm2',  500, 1200, 'Spon''s Architects and Builders Price Book 2026', 'https://www.taylorfrancis.com/books/edit/10.1201/9781003544449/spon-architects-builders-price-book-2026', 'Spon''s 2026 external cleaning section', array['uk'], 'Basic clean only. Excludes damp treatment, deep patching, mesh reinforcement, or removal of existing coatings.', null, 'high'),
('decorative-rendering', 'prep-substrate-strip',        'Strip existing render',                  'Chip off + dispose of existing render before new application.',       'm2', 1500, 3000, 'Spon''s Architects and Builders Price Book 2026', 'https://www.taylorfrancis.com/books/edit/10.1201/9781003544449/spon-architects-builders-price-book-2026', 'Spon''s 2026 demolition + strip', array['uk'], 'Excludes waste removal / skip. Excludes damp treatment or making good beneath.', null, 'high'),
('decorative-rendering', 'prep-mesh-reinforcement',     'Fibreglass mesh reinforcement',          'Alkali-resistant mesh embedded in base coat over cracked/EWI areas.',  'm2',  600, 1000, 'K Rend UK',                                       'https://www.k-rend.co.uk/',                                        'K Rend installation guide', array['uk'], 'Supply + labour of mesh + base coat only. Excludes finish coat.', null, 'high'),
('decorative-rendering', 'prep-damp-treatment',         'Damp treatment (pre-render)',            'PCA-certified damp injection or membrane before new render.',         'm2', 2500, 6000, 'Property Care Association (PCA)',                 'https://www.property-care.org/',                                   'PCA damp treatment guidance 2026', array['uk'], 'PCA-approved contractor. Includes chemical damp course + 1st fix. Excludes making good, decorating, or structural work.', null, 'moderate'),

-- ── Beads (per linear metre) ──
('decorative-rendering', 'bead-corner',                 'External corner bead',                   'Angle bead at external corners for straight edges.',                  'linear-m', 400,  800, 'Spon''s Architects and Builders Price Book 2026', 'https://www.taylorfrancis.com/books/edit/10.1201/9781003544449/spon-architects-builders-price-book-2026', 'Spon''s 2026 beading section', array['uk'], 'Supply + install per linear metre.', null, 'high'),
('decorative-rendering', 'bead-drip',                   'Drip bead / stop bead',                  'PVC or stainless drip bead over windows + at wall base.',             'linear-m', 500,  900, 'Spon''s Architects and Builders Price Book 2026', 'https://www.taylorfrancis.com/books/edit/10.1201/9781003544449/spon-architects-builders-price-book-2026', 'Spon''s 2026 beading section', array['uk'], 'Supply + install per linear metre.', null, 'high'),
('decorative-rendering', 'bead-render-stop',            'Render stop bead',                       'Stop bead at edges + termination points.',                            'linear-m', 400,  700, 'Spon''s Architects and Builders Price Book 2026', 'https://www.taylorfrancis.com/books/edit/10.1201/9781003544449/spon-architects-builders-price-book-2026', 'Spon''s 2026 beading section', array['uk'], 'Supply + install per linear metre.', null, 'high'),

-- ── Scaffolding (per m² of external wall, per week) ──
('decorative-rendering', 'scaffold-external-standard',  'Scaffolding (standard, per m² per wk)',  'Independent scaffold, standard height (up to 2 storeys).',            'm2',  800, 1500, 'Spon''s Architects and Builders Price Book 2026', 'https://www.taylorfrancis.com/books/edit/10.1201/9781003544449/spon-architects-builders-price-book-2026', 'Spon''s 2026 scaffold section', array['uk'], 'Standard 2-storey scaffold, per m² of wall face, per week hire. Excludes: erection travel, night lighting, sheeting, roof edge protection.', null, 'moderate'),
('decorative-rendering', 'scaffold-external-tall',      'Scaffolding (3+ storeys, per m² per wk)','Independent scaffold, tall (3+ storeys or eaves >8m).',                'm2', 1400, 2500, 'Spon''s Architects and Builders Price Book 2026', 'https://www.taylorfrancis.com/books/edit/10.1201/9781003544449/spon-architects-builders-price-book-2026', 'Spon''s 2026 scaffold section', array['uk'], '3+ storey scaffold. Excludes: crane hire, exceptional access constraints, weather delays.', null, 'moderate'),

-- ── Sealer / final treatment ──
('decorative-rendering', 'sealer-masonry-water-repel',  'Masonry sealer / water repellent',       'Siloxane or silane sealer over completed render for freeze-thaw + water shed.', 'm2',  400,  900, 'Checkatrade UK Cost Guide',                      'https://www.checkatrade.com/blog/cost-guides/masonry-sealing/',    'Checkatrade masonry sealer guide 2026', array['uk'], 'Sealer only, single coat. Multi-coat systems + specialist heritage sealers priced separately.', null, 'moderate')

on conflict (trade_slug, line_item_slug) do update set
  display_name       = excluded.display_name,
  price_low_pence    = excluded.price_low_pence,
  price_high_pence   = excluded.price_high_pence,
  source_publisher   = excluded.source_publisher,
  source_url         = excluded.source_url,
  source_reference   = excluded.source_reference,
  last_verified_at   = excluded.last_verified_at,
  excludes_notes     = excluded.excludes_notes,
  confidence         = excluded.confidence;
