-- Concrete Knowledge Pack — first implementation of the Trade
-- Knowledge Engine. Every entry is trade-agnostic in shape; only
-- the CONTENT is concrete-specific. The exact same structure is
-- used by future packs (bricklaying, plumbing, electrical, etc).
--
-- Sources: gov.uk (Approved Docs), planningportal.co.uk,
-- Mineral Products Association (mineralproducts.org), Concrete
-- Society technical notes, NHBC standards, BS EN 206 + BS 8500
-- summaries, and manufacturer datasheets (Hanson, Tarmac).
--
-- Every entry ships with confidence_score 0.90-1.00 for the
-- seeded set. Lower confidence entries flow through the
-- community contribution pipeline for admin verification.

-- ─── Trade ────────────────────────────────────────────────────────
insert into hammerex_knowledge_trades
  (slug, display_name, description, merchant_categories, trade_categories, icon_slug, sort_order)
values
  ('concrete', 'Concrete',
   'Concrete work — mix design, foundations, slabs, driveways, patios, screeding, curing, testing, repair.',
   array['building-merchant','builders-supplies','concrete-supplier','plant-hire'],
   array['bricklayer','groundworker','concrete-contractor','builder','driveway-installer','structural-engineer'],
   'square', 10)
on conflict (slug) do update
  set display_name = excluded.display_name,
      description  = excluded.description,
      merchant_categories = excluded.merchant_categories,
      trade_categories    = excluded.trade_categories,
      icon_slug           = excluded.icon_slug;

-- ─── Topics (hierarchical) ────────────────────────────────────────
insert into hammerex_knowledge_topics (trade_slug, slug, display_name, description, sort_order) values
  ('concrete', 'fundamentals',       'Concrete fundamentals',       'What concrete is and how it works.',                                  10),
  ('concrete', 'materials',          'Materials',                    'Cement, aggregate, sand, water, admixtures.',                         20),
  ('concrete', 'mix-design',         'Mix ratios + strength classes','Mix ratios (1:2:4 etc), strength classes (C15-C50), workability.',    30),
  ('concrete', 'reinforcement',      'Reinforcement',                'Mesh, rebar, fibres, cover, spacing.',                                40),
  ('concrete', 'foundations',        'Foundations + footings',       'Strip, trench-fill, pad, raft foundations.',                          50),
  ('concrete', 'slabs',              'Slabs + oversites',            'Domestic, driveway, garage, workshop, industrial slabs.',             60),
  ('concrete', 'ready-mix-vs-site',  'Ready-mix vs site-mix',        'When to order ready-mix vs mix on site.',                             70),
  ('concrete', 'curing',             'Curing + placement',           'Curing time, hot/cold weather, walking + driving times.',             80),
  ('concrete', 'joints',             'Expansion + control joints',   'Where and how to cut joints.',                                        90),
  ('concrete', 'testing',            'Testing + quality',            'Cube test, slump test, compressive strength.',                       100),
  ('concrete', 'failure',            'Failure + repair',             'Cracking, dusting, flaking, structural failure diagnosis.',          110),
  ('concrete', 'safety',             'Safety',                       'PPE, silica dust, cement burns, working around wet concrete.',       120),
  ('concrete', 'regulations',        'UK regulations',               'Building Regs Approved Doc A, BS EN 206, planning + drainage rules.',130)
on conflict (trade_slug, slug) do nothing;

-- ─── Video tag ontology ───────────────────────────────────────────
insert into hammerex_knowledge_video_tags (slug, trade_slug, display_name, tag_kind, description) values
  ('concrete-mix',        'concrete', 'Mix design / batching', 'activity', 'Preparing the mix on site or via ready-mix'),
  ('concrete-pour',       'concrete', 'Pouring concrete',      'activity', 'Placing concrete into formwork'),
  ('concrete-finish',     'concrete', 'Finishing',             'activity', 'Trowelling, floating, power-float'),
  ('concrete-cure',       'concrete', 'Curing',                'stage',    'Post-pour curing period'),
  ('foundation-strip',    'concrete', 'Strip foundation',      'method',   'Strip footing for load-bearing walls'),
  ('foundation-trench',   'concrete', 'Trench-fill foundation','method',   'Trench-fill to reduce brickwork below DPC'),
  ('foundation-raft',     'concrete', 'Raft foundation',       'method',   'Full-slab reinforced foundation'),
  ('slab-domestic',       'concrete', 'Domestic floor slab',   'method',   'Ground-bearing slab for houses'),
  ('slab-driveway',       'concrete', 'Driveway slab',         'method',   'Domestic driveway pour'),
  ('slab-industrial',     'concrete', 'Industrial slab',       'method',   'Warehouse / workshop slab with heavy loading'),
  ('screed',              'concrete', 'Screeding',             'activity', 'Sand+cement or self-levelling screed'),
  ('reinforcement-mesh',  'concrete', 'Mesh reinforcement',    'material', 'A-series steel mesh (A142/A193/A252)'),
  ('reinforcement-rebar', 'concrete', 'Rebar reinforcement',   'material', 'Deformed steel bar (T10/T12/T16 etc)'),
  ('reinforcement-fibre', 'concrete', 'Fibre reinforcement',   'material', 'Polypropylene or steel fibres'),
  ('joint-expansion',     'concrete', 'Expansion joint',       'method',   'Movement joint through the slab'),
  ('joint-control',       'concrete', 'Control joint',         'method',   'Saw-cut crack control'),
  ('pump-line',           'concrete', 'Concrete pump',         'tool',     'Line or boom pump for placement'),
  ('mixer-drum',          'concrete', 'Drum mixer',            'tool',     'Ready-mix truck or site mixer'),
  ('power-float',         'concrete', 'Power float',           'tool',     'Power float / trowel machine'),
  ('cube-test',           'concrete', 'Cube test',             'method',   '150mm cube compressive strength test'),
  ('slump-test',          'concrete', 'Slump test',            'method',   'Workability test per BS EN 12350-2'),
  ('crack-plastic',       'concrete', 'Plastic shrinkage cracking', 'problem', 'Surface cracks during early curing'),
  ('crack-drying',        'concrete', 'Drying shrinkage cracking',  'problem', 'Longer-term cracks from moisture loss'),
  ('dust-silica',         'concrete', 'Silica dust',           'safety',   'RCS exposure from cutting or dry cement'),
  ('cement-burn',         'concrete', 'Cement burn',           'safety',   'Alkaline burns from wet concrete on skin')
on conflict (slug) do nothing;

-- ─── Entries ──────────────────────────────────────────────────────
-- Helper: topic_id lookup pattern used below
--   (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug=<topic>)

-- 1. Fundamentals
insert into hammerex_knowledge_entries (
  trade_slug, topic_id, content_type, title, ai_summary, detailed_explanation,
  video_tags, merchant_categories, trade_categories, source_url, source_type, source_publisher, confidence_score
) values
('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='fundamentals'),
 'fundamentals', 'What concrete is',
 'Concrete is a composite of cement (binder), water, sand (fine aggregate), and coarse aggregate (stone). It cures via hydration — the cement chemically reacts with water to form a hard matrix.',
 'Concrete is not simply a mix that dries out. It hardens through hydration: a chemical reaction between cement and water that produces calcium silicate hydrate. This is why concrete can set underwater and why the water-cement ratio (typically 0.4-0.6 by weight) is the single most important factor determining final strength. Too much water gives you weak, porous concrete; too little and you cannot properly compact it. Standard components per BS EN 206: CEM I / CEM II cement, graded coarse aggregate (typically 10-20mm), sharp sand (0-4mm), and clean drinkable water.',
 array['concrete-mix'],
 array['building-merchant','builders-supplies'],
 array['bricklayer','groundworker'],
 'https://www.mineralproducts.org/', 'trade-body', 'MPA', 0.98),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='materials'),
 'material', 'Cement types (CEM I to CEM V)',
 'BS EN 197-1 defines 5 cement types: CEM I (Portland), CEM II (Portland-composite), CEM III (blastfurnace), CEM IV (pozzolanic), CEM V (composite). CEM I and CEM II are the everyday choice for UK domestic work.',
 'CEM I (pure Portland) sets fastest and reaches strength quickest — used for structural work and cold weather. CEM II blends Portland with fly ash, limestone or slag (5-35%) — cheaper, lower carbon, slower strength gain, used for most domestic slabs. CEM III is high-slag content — used for aggressive ground conditions (sulfate-bearing soils). Sulfate-resisting Portland (SRPC / CEM I-SR3) is required where soil sulfate class DS-3+ per BS 8500-1. Rapid-hardening (CEM I 52.5R) reaches 24-hour strength for early formwork strike. Always check the bag class code: e.g., CEM II/A-LL 32.5R is limestone-blend, 32.5MPa 28-day strength, rapid.',
 array['concrete-mix'],
 array['building-merchant','builders-supplies','concrete-supplier'],
 array['bricklayer','groundworker','concrete-contractor'],
 'https://www.hanson.co.uk/en/cement', 'manufacturer', 'Hanson', 0.95),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='mix-design'),
 'specification', '1:2:4 mix ratio explained',
 '1:2:4 by volume means 1 part cement, 2 parts sand, 4 parts coarse aggregate. This produces roughly C20 concrete (20 MPa at 28 days) suitable for general foundations, garden slabs and non-structural work.',
 'The 1:2:4 mix is the most commonly cited UK ratio for everyday concrete. To batch 1 m³ you need approximately: 320 kg cement (~6.5 bags of 50 kg or ~13 bags of 25 kg), 640 kg sharp sand (~0.4 m³), 1280 kg 20mm ballast (~0.8 m³), and 160-190 litres of water. Water content controls both workability and final strength — aim for water-cement ratio 0.5-0.6. For higher strength (structural elements) drop to 1:1.5:3 which gives ~C25. For lean concrete (blinding, sub-base) use 1:3:6. Never adjust ratio mid-pour — batch consistently for uniform strength.',
 array['concrete-mix','concrete-pour'],
 array['building-merchant','builders-supplies','concrete-supplier'],
 array['bricklayer','groundworker'],
 'https://www.concretecentre.com/', 'trade-body', 'Concrete Centre', 0.97),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='mix-design'),
 'specification', 'Strength classes C15 to C50',
 'UK concrete strength is specified in MPa (N/mm²) at 28 days per BS EN 206. Common classes: C15 (lean), C20 (general), C25 (foundations), C30 (drives, exposed), C32/40 (structural), C40+ (heavy industrial).',
 'The number after C is the characteristic compressive strength in MPa. Choose by exposure + load: C15 for blinding under foundations; C20 (RC20) for internal domestic floor slabs and mass fill; C25 for domestic strip foundations; C28/35 for driveways and exposed exterior slabs (per Approved Doc A + BS 8500); C32/40 for structural elements (lintels, beams, ground beams); C40+ for industrial slabs with heavy loading. Note the dual notation like C28/35 refers to cylinder strength (28) / cube strength (35) — UK design typically references cube strength. Ready-mix orders should specify class + slump + max aggregate size (e.g. "C28/35 S3 20").',
 array['concrete-mix','slab-driveway','slab-industrial'],
 array['building-merchant','concrete-supplier'],
 array['groundworker','concrete-contractor','structural-engineer'],
 'https://www.gov.uk/government/publications/approved-document-a', 'gov', 'gov.uk Approved Doc A', 0.98),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='slabs'),
 'specification', 'Slab thickness recommendations',
 'Standard slab thicknesses (UK): 75mm garden path; 100mm domestic patio + shed base; 100-125mm domestic driveway (car only); 150mm van/light commercial drive; 150-200mm garage floor; 200mm+ workshop floor with vehicle loading; 250mm+ industrial slab.',
 'Thickness is driven by load, sub-base quality, and reinforcement. For DOMESTIC work on good sub-base (150mm compacted MOT Type 1): 75mm suits foot-only paths; 100mm handles patios, shed bases, and light cars if reinforced with A142 mesh; 150mm is safe for a domestic drive with a family car. For VEHICLES over 3.5t (vans, works trucks, small plant) drop to 150mm minimum with A252 mesh. For workshops with occasional heavy load (2-tonne cars on jack, small forklift) 200mm reinforced with A393 or an engineered mesh. For industrial + agricultural slabs a structural engineer must specify thickness, mix, sub-base and reinforcement to BS 8500 + Concrete Society TR34.',
 array['slab-domestic','slab-driveway','slab-industrial'],
 array['building-merchant','concrete-supplier'],
 array['groundworker','concrete-contractor','structural-engineer','driveway-installer'],
 'https://www.concretecentre.com/', 'trade-body', 'Concrete Centre', 0.94),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='slabs'),
 'faq', 'How much concrete do I need for a 3m x 3m garden slab?',
 'For a 3m × 3m area at 100mm depth: 0.9 m³ of concrete — approximately 36 × 25kg bags or a 1 m³ ready-mix load (minimum load size at most suppliers).',
 'Calculation: length × width × depth in metres. 3 × 3 × 0.1 = 0.9 m³. Bag conversion: at 2400 kg/m³ that''s ~2160 kg, or ~87 × 25kg bags of ready-mixed concrete (each yields ~0.01 m³). If you''re batching from separate cement/sand/ballast bags at 1:2:4 you need roughly 6-7 × 25kg cement, 0.4 m³ sand, 0.8 m³ ballast. For pours over 0.5 m³ ready-mix is almost always cheaper and more consistent than bags. Add 5-10% waste allowance. For 150mm (driveway depth) use 1.35 m³. Any building merchant on the Networkers app can quote ready-mix + delivery to your postcode.',
 array['concrete-mix','slab-domestic','slab-driveway'],
 array['building-merchant','concrete-supplier'],
 array['bricklayer','groundworker','driveway-installer'],
 'https://www.concretecentre.com/', 'trade-body', 'Concrete Centre', 0.95),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='reinforcement'),
 'material', 'Steel mesh reinforcement (A142 to A393)',
 'A-series mesh is standard for domestic slabs: A142 (6mm bars @ 200mm centres, 142 mm²/m) for light slabs; A193 for domestic drives; A252 for heavier drives + garage floors; A393 for industrial slabs. Overlap 300mm at joints per BS 4483.',
 'Mesh sits on 25-50mm spacers (never on the sub-base directly) so it ends up in the lower third of the slab where tensile stress is highest. Cover to underside: 40mm for exposed exterior slabs, 50mm+ for aggressive ground. Overlap sheets by at least 300mm and tie with 1.6mm annealed wire at 1m intervals. For a domestic garage floor spec A252 on 50mm spacers, 100mm+ cover top. Fibre reinforcement can supplement but does not replace mesh for load-bearing slabs — always check BS 8500 + your engineer''s spec.',
 array['reinforcement-mesh','slab-domestic','slab-driveway'],
 array['building-merchant','builders-supplies'],
 array['groundworker','concrete-contractor','structural-engineer'],
 'https://www.romtech.co.uk/', 'manufacturer', 'ROM Group', 0.94),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='ready-mix-vs-site'),
 'best-practice', 'Ready-mix vs site-mix — when to choose which',
 'Ready-mix is cheaper + more consistent above 0.5 m³. Site-mix (bags or on-site mixer) makes sense for small pours (<0.3 m³), remote sites, or when access blocks a mixer truck.',
 'A single ready-mix truck typically carries 6-8 m³ and needs 3m width + firm ground for access. Minimum delivered loads are usually 1 m³ (some suppliers 0.5 m³ with a "part load" charge). If you cannot get a truck within 25m of the pour, add a pump (line pump ~£350-500, boom pump ~£800-1,500 in the UK). For any pour over 0.5 m³ ready-mix is cheaper per m³ AND more consistent — cube-tested at the plant. Site mixing is worth it under 0.3 m³ (posts, small footings) or where access is impossible. For pours 0.3-0.5 m³ get quotes both ways. Any concrete supplier on the Networkers app can advise on minimum load + pump hire for your site.',
 array['concrete-mix','mixer-drum','pump-line'],
 array['concrete-supplier','plant-hire','building-merchant'],
 array['groundworker','concrete-contractor'],
 'https://www.mineralproducts.org/', 'trade-body', 'MPA', 0.93),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='curing'),
 'best-practice', 'Curing times — when to walk, when to drive',
 'Foot traffic: 24-48 hours. Furniture / light loads: 3-7 days. Vehicles: 7-14 days minimum, ideally 28 days for full design strength. Full cure (100% strength): 28 days.',
 'Concrete reaches ~70% strength at 7 days and ~99% at 28 days assuming curing conditions are met. Never drive on a fresh slab under 7 days regardless of how hard it feels — internal strength lags surface hardness. In HOT weather (>20°C) cover with polythene or damp hessian for the first 3 days to prevent plastic shrinkage cracking. In COLD weather (<5°C) hydration slows dramatically — do not pour if temperatures will drop below 3°C for 24+ hours after. Cover with insulating blankets if pouring below 5°C. NEVER pour on frozen ground — sub-base movement will crack the slab. If in doubt, delay 24 hours — a cracked slab costs 10× more to fix than the wait.',
 array['concrete-cure'],
 array['building-merchant','concrete-supplier'],
 array['groundworker','concrete-contractor'],
 'https://www.concretecentre.com/', 'trade-body', 'Concrete Centre', 0.96),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='joints'),
 'installation', 'Control + expansion joints',
 'Control joints (saw-cut or tooled) at 4-6m centres in domestic slabs, cut to ¼ of slab depth within 4-24 hours of pour, guide where the slab will crack. Expansion joints (full-depth compressible filler) needed where slab abuts a wall, column or existing slab.',
 'Concrete WILL crack — the job is to control WHERE. For domestic slabs use control joints at every 4-6m in each direction (rule of thumb: 25× slab thickness so a 100mm slab = 2.5m centres). Cut with a diamond disc saw within 4-24 hours of pour, depth = ¼ of slab thickness. Any panel with an aspect ratio worse than 1.5:1 needs an extra intermediate joint. Expansion joints (10mm+ compressible filler board) go around perimeter walls, columns, drain covers, and where new slab meets existing. For a driveway or patio pour a bond-breaker (polythene) against walls to prevent bonding + crack transfer. Skipping joints is the #1 cause of random cracking in domestic slabs.',
 array['joint-control','joint-expansion','slab-domestic','slab-driveway'],
 array['building-merchant','builders-supplies'],
 array['groundworker','concrete-contractor'],
 'https://www.concretecentre.com/', 'trade-body', 'Concrete Centre', 0.93),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='testing'),
 'method', 'Slump test + cube test',
 'Slump test (BS EN 12350-2) measures workability — a truncated cone lifted off gives S1 (10-40mm) low to S5 (>220mm) high. Cube test (BS EN 12390-3) measures compressive strength at 7 + 28 days using 150mm cubes.',
 'For any structural pour insist on ready-mix delivery tickets + slump on arrival. Common slump targets: S2 (50-90mm) foundation pours, S3 (100-150mm) reinforced slabs, S4 (160-210mm) pumped concrete. Test on site with a slump cone before signing the ticket — reject the load if slump is outside the ordered range. For notifiable structural work take 4 × 150mm cubes per pour (or per 20 m³), cure them in a water bath at 20°C, test 2 at 7 days + 2 at 28 days. Ready-mix suppliers can do this for you as a paid service. Cube strength must exceed the specified class (e.g. C28/35 requires minimum 35 MPa at 28 days). Failed cubes = investigate: it may be batch error, curing conditions, or sampling issue.',
 array['cube-test','slump-test'],
 array['concrete-supplier'],
 array['concrete-contractor','structural-engineer'],
 'https://www.bsigroup.com/en-GB/', 'standard', 'BSI', 0.96),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='failure'),
 'troubleshooting', 'Why is my concrete cracking?',
 'Common causes: plastic shrinkage (hot/windy conditions), drying shrinkage (excess water, no joints), thermal movement (temperature swings, missing expansion joints), structural overload, subgrade settlement, or freeze-thaw.',
 'Cracks under 0.3mm wide are usually cosmetic; over 0.3mm can allow water/reinforcement corrosion. PLASTIC cracks (fine, appear within hours of pour) — cause: rapid surface drying, wind, or heat. Fix: keep surface wet + covered for 3 days. DRYING SHRINKAGE cracks (wider, appear over weeks) — cause: too much water in mix or missing joints. Fix: chase + fill with flexible epoxy. STRUCTURAL cracks (wide, follow a load path, may step) — cause: overload or subsidence. Fix: needs a structural engineer''s assessment. FREEZE-THAW spalling (surface flaking, exterior slabs) — cause: air-entrainment missing or w/c ratio too high. Fix: apply penetrating sealant + air-entrained overlay. Never just fill wide cracks without diagnosing the cause — they will re-open.',
 array['crack-plastic','crack-drying'],
 array['building-merchant'],
 array['groundworker','concrete-contractor','structural-engineer'],
 'https://www.concretecentre.com/', 'trade-body', 'Concrete Centre', 0.93),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='safety'),
 'safety', 'Cement burns + PPE',
 'Wet concrete is highly alkaline (pH 12-13) and causes chemical burns on skin contact within 30 minutes. Full PPE: safety goggles, chemical-resistant gloves (nitrile min), long sleeves, waterproof trousers, safety boots.',
 'Cement burns are often not felt at the time — you only notice hours later when the skin blisters. Wash any splash off immediately with clean water for 15 minutes. Kneepads must be waterproof — kneeling in wet concrete causes some of the worst burns. NEVER handle wet concrete barefoot or in shorts. If concrete gets inside boots or gloves, STOP and rinse — the burn accelerates in warmth. For eye splash rinse for 15 minutes and see A&E immediately (risk of permanent damage). Dry cement dust causes silicosis over time — wear FFP3 mask when mixing or cutting cured concrete. HSE reports ~500 UK construction workers/year with severe cement burns.',
 array['cement-burn','dust-silica'],
 array['building-merchant'],
 array['bricklayer','groundworker','concrete-contractor'],
 'https://www.hse.gov.uk/skin/employ/cement.htm', 'gov', 'HSE', 0.99),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='regulations'),
 'regulation', 'Building Regs + concrete work — when do I need approval?',
 'Building Regs (Approved Doc A structure, C site prep) apply to any concrete work that supports the building or the ground beneath it: foundations, floors that carry load, retaining walls > 600mm. Detached outbuildings under 30m² floor area typically do not need approval.',
 'Full plans notification required for: new dwelling foundations; extensions with any load-bearing concrete element; retaining walls over 600mm high next to a highway or drop; garage floors that support a habitable room above; commercial slabs. NOT typically notifiable: garden slabs, patios, paths, shed bases (<30m²), fence-post concrete, decorative concrete. A DRIVEWAY does not need Building Regs but MAY need PLANNING if over 5m² of impermeable surface draining to a highway (per SUDS regs) — use permeable paving OR direct water to a soakaway to stay permitted-development. Always check with your local authority Building Control before starting — a phone call is free; a rejected structure costs thousands.',
 array['foundation-strip','foundation-trench','slab-domestic','slab-driveway'],
 array['building-merchant'],
 array['building-inspector','structural-engineer','groundworker','driveway-installer'],
 'https://www.gov.uk/government/publications/approved-document-a', 'gov', 'gov.uk Approved Doc A', 0.98),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='foundations'),
 'method', 'Strip foundation vs trench-fill vs raft',
 'Strip footing: 600mm-wide × 200mm-deep concrete band under walls, brickwork below DPC. Trench-fill: full-depth concrete to within 150mm of ground level (no below-DPC brick). Raft: full slab across footprint for weak ground.',
 'STRIP footings suit firm cohesive soils with load-bearing walls. Cheapest to pour (less concrete) but slower to build (must build up below-DPC brick). TRENCH-FILL uses more concrete but saves 4-6 courses of below-ground blockwork — faster overall, popular for domestic extensions. Widen if soil is soft (min 750mm for weak clay). RAFT foundations distribute load across the whole footprint — used for weak/variable soils, made-up ground, or in areas of subsidence risk. Requires engineered design with reinforcement. Minimum depth below finished ground: 900mm on cohesive clay (frost heave), 450mm on rock. Any tree within 20m of the foundation increases depth requirements per NHBC Chapter 4.2. A structural engineer must specify raft foundations — do not guess.',
 array['foundation-strip','foundation-trench','foundation-raft'],
 array['building-merchant','concrete-supplier'],
 array['groundworker','structural-engineer','building-inspector'],
 'https://www.nhbc.co.uk/', 'trade-body', 'NHBC', 0.94),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='slabs'),
 'method', 'Driveway build-up — sub-base to slab',
 'Standard UK domestic driveway build-up (top to bottom): 100mm C28/35 concrete slab with A252 mesh, on 50mm sharp sand blinding, on 150mm compacted MOT Type 1 sub-base, on compacted subgrade. Total depth 300mm.',
 'Excavate to 300mm below finished driveway level. Compact subgrade with a vibrating roller. Lay 150mm MOT Type 1 in two 75mm lifts, compacting each. Add 50mm sharp sand blinding to level. Lay A252 mesh on 50mm spacers (mesh in bottom third of slab). Pour C28/35 concrete to 100mm depth (specify air-entrainment for freeze-thaw resistance). Tamp + float finish (broom finish for grip). Cut control joints at 3m centres within 24 hours. Cure 7 days before foot use, 14 days before vehicle use, 28 days for full design load. Add fall of 1:80 (12mm per m) toward drainage — never toward the house. Any groundworker on the Networkers app can quote full supply + install.',
 array['slab-driveway'],
 array['building-merchant','concrete-supplier'],
 array['groundworker','driveway-installer','concrete-contractor'],
 'https://www.concretecentre.com/', 'trade-body', 'Concrete Centre', 0.94),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='mix-design'),
 'faq', 'How many bags of cement per m³?',
 'For a 1:2:4 mix (~C20): ~6.5 bags of 50kg cement OR ~13 bags of 25kg. For 1:1.5:3 (~C25): ~8 bags of 50kg. For lean 1:3:6 (~C10 blinding): ~4.5 bags of 50kg.',
 'Precise cement content per m³ of fresh concrete: 1:2:4 = 320 kg (workable general), 1:1.5:3 = 400 kg (structural), 1:3:6 = 220 kg (lean/blinding). All figures assume 20mm coarse aggregate and w/c ratio 0.55. Add ~5% waste allowance when ordering. If you''re using pre-mixed bagged concrete (already contains cement + aggregate) yields are printed on the bag — typically ~0.011 m³ per 25kg bag, so 90 bags per m³. Pre-mixed bags cost 2-3× the price of separate materials — only economical for very small pours or where you can''t site-mix. A merchant on the Networkers app can quote either option.',
 array['concrete-mix'],
 array['building-merchant','builders-supplies'],
 array['bricklayer','groundworker'],
 'https://www.mineralproducts.org/', 'trade-body', 'MPA', 0.95),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='curing'),
 'faq', 'When can I walk on my new concrete?',
 'Light foot traffic: 24-48 hours after pour if surface is firm. Regular walking + placing lightweight objects: 3-4 days. Furniture / heavy foot loads: 7 days.',
 'Concrete is walkable when finger-pressed and the surface does not indent — usually 24-48 hours in normal UK conditions, longer in cold weather. Even when walkable, avoid dragging heavy or sharp objects across the surface for 7+ days as it can gouge the still-curing top layer. In hot weather keep the surface covered with damp hessian or plastic sheeting for the first 3-5 days to prevent surface drying (which causes dusting). In cold weather (below 5°C) do not walk on it until the surface is fully set — hydration slows dramatically and the surface can crush. Never drive on a domestic slab before 7 days regardless of how hard it feels — internal strength lags surface hardness by several days.',
 array['concrete-cure'],
 array['building-merchant'],
 array['bricklayer','groundworker','concrete-contractor'],
 'https://www.concretecentre.com/', 'trade-body', 'Concrete Centre', 0.94),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='failure'),
 'troubleshooting', 'Why is my concrete dusting or flaking?',
 'Dusting = surface bleed of fines caused by over-trowelling wet concrete, excess water, or premature drying. Flaking (spalling) = freeze-thaw damage or insufficient curing. Both are preventable with proper mix + curing.',
 'DUSTING (chalky powder on surface): cause is trowelling water into the surface OR pouring in freezing conditions. Fix: apply a penetrating silicate hardener + surface sealant. Prevention: never trowel while bleed water is visible; wait for it to disappear or be pushed off. FLAKING (surface layer peeling off in patches, usually winter): cause is water absorbed into surface pores then freezing + expanding. Prevention: spec air-entrained concrete for exterior slabs (2-6% entrained air per BS 8500); cure properly for 7+ days; apply penetrating sealer after 28 days. Repair: mechanically remove loose surface, apply bonding agent, screed with 20mm modified overlay. If flaking covers >20% of slab, replacement is often cheaper than repair.',
 array['crack-drying','concrete-cure'],
 array['building-merchant'],
 array['groundworker','concrete-contractor'],
 'https://www.concretecentre.com/', 'trade-body', 'Concrete Centre', 0.92),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='ready-mix-vs-site'),
 'faq', 'How much does ready-mix concrete cost in the UK?',
 'UK ready-mix pricing (indicative 2026): £90-130 per m³ for standard C20-C25; £110-160 for C28/35 driveway grade; £140-200 for C40+ structural. Add £30-60 delivery + £60-100 part-load charge (under minimum).',
 'Prices vary significantly by region and current cement + fuel costs. London/SE typically 15-25% higher than northern regions. Minimum load is usually 1 m³; part-load charges apply below this. Pumping adds £350-500 (line pump, up to 25m reach) or £800-1500 (boom pump, up to 60m). Weekend deliveries usually +20%. Waiting time charges kick in after 30-45 minutes on site (typically £2-3/min) — have your formwork completely ready before ordering. Get 3 quotes for any pour over 3 m³. Any concrete supplier on the Networkers app can quote to your postcode + specify class, slump, aggregate size + delivery window.',
 array['concrete-mix','mixer-drum','pump-line'],
 array['concrete-supplier','plant-hire'],
 array['groundworker','concrete-contractor','driveway-installer'],
 'https://www.mineralproducts.org/', 'trade-body', 'MPA', 0.88),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='materials'),
 'material', 'Aggregate types + grading',
 'Standard UK aggregates: 20mm graded ballast (mix of sand + stone, for general concrete); 20mm single-sized stone (for concrete with separate sand); 10mm for tight formwork or thin slabs; sharp/washed sand for concrete; building sand only for mortar.',
 '"Ballast" is a pre-mixed sand + coarse aggregate blend (typically 40:60 sand:stone) — convenient for small pours. For accurate mix design, buy sharp sand + coarse aggregate separately so you control ratios. NEVER use building sand (soft sand) in concrete — its fines cause weak, dusty concrete. Aggregate must comply with BS EN 12620. Grading matters: use 10mm for slabs under 75mm thick or where mesh spacing is tight; 20mm for general work; 40mm only for mass foundations. Recycled concrete aggregate (RCA) is BS EN 12620-compliant for many applications and 20-30% cheaper — but check with your engineer for structural use. All aggregate should be washed, low-fines, and free of clay lumps.',
 array['concrete-mix'],
 array['building-merchant','builders-supplies'],
 array['bricklayer','groundworker'],
 'https://www.mineralproducts.org/', 'trade-body', 'MPA', 0.93),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='reinforcement'),
 'material', 'Fibre reinforcement — when it helps',
 'Polypropylene micro-fibres (18-20mm) reduce plastic shrinkage cracking in the surface. Steel or macro-synthetic fibres (40-60mm) can partially replace mesh for lightly-loaded slabs. Neither replaces engineered reinforcement for structural work.',
 'Poly micro-fibres (~600g per m³, e.g. Sika Fiber PPM-12) are cheap insurance against surface plastic-shrinkage cracks — worth adding to any large exterior pour. They do NOT add structural strength. Steel/macro-synthetic fibres (25-40 kg/m³) can carry moderate load and are used in ground-bearing industrial slabs (per Concrete Society TR34) — but require engineered mix design + dosage. For domestic driveways and garage floors, always specify A252 mesh even if adding fibres — insurance layers, not substitutes. Never rely on fibres alone for a slab that will carry vehicles.',
 array['reinforcement-fibre','reinforcement-mesh','slab-industrial'],
 array['building-merchant','builders-supplies'],
 array['concrete-contractor','structural-engineer'],
 'https://www.concretecentre.com/', 'trade-body', 'Concrete Centre', 0.90),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='regulations'),
 'regulation', 'Driveway planning — the 5m² permeable surface rule',
 'In England you do NOT need planning permission for a new driveway of any size IF it uses permeable surfacing (gravel, permeable paving, porous asphalt) OR if runoff drains to a permeable area (lawn, border, soakaway). Impermeable surfaces >5m² draining to highway need planning.',
 'The Town and Country Planning (General Permitted Development) Order 2008 introduced this rule after urban flooding concerns. Solid concrete draining to the road is the classic trigger. To stay permitted-development: (1) install permeable concrete blocks / porous asphalt / gravel; OR (2) install a soakaway that meets BRE Digest 365; OR (3) direct the water via a fall to a lawn/border > 3m² per m² of surface. Building Regulations do NOT apply to a driveway itself. Planning IS required in Wales for any hardstanding + in Scotland/NI different rules apply — always check local. If uncertain phone your local authority planning department (free) before pouring.',
 array['slab-driveway'],
 array['building-merchant'],
 array['driveway-installer','groundworker','building-inspector'],
 'https://www.planningportal.co.uk/permission/common-projects/patio-and-driveway/planning-permission/', 'gov', 'Planning Portal', 0.98),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='slabs'),
 'method', 'Screed vs concrete — what''s the difference',
 'Screed is a fine layer (typically 40-75mm) of cement + sharp sand placed over a concrete slab to give a smooth, level finish for flooring. Concrete is the structural slab beneath. Screed is not a substitute for concrete — it has no coarse aggregate + no structural strength.',
 'Standard sand-cement screed: 1:3 or 1:4 cement:sharp sand at 40-75mm depth for bonded, 65-100mm for unbonded (over DPM), 100mm+ for floating (over insulation). Modified screed adds SBR bonding polymer for improved crack resistance. Self-levelling screed (calcium sulfate or cementitious) requires only 5-30mm depth + gives a flat finish suitable for direct tiling/vinyl — used over underfloor heating. Traditional screed cures for 1 day per mm depth (60mm = 60 days!) before floor finishes; modified/rapid screeds cure faster (7-14 days). NEVER lay flooring over a screed until moisture content is below 75% RH — check with a hygrometer.',
 array['screed','slab-domestic'],
 array['building-merchant','concrete-supplier'],
 array['screeder','tiler','carpenter'],
 'https://www.concretecentre.com/', 'trade-body', 'Concrete Centre', 0.93),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='mix-design'),
 'best-practice', 'Water-cement ratio — the single most important number',
 'Water-cement (w/c) ratio by weight determines final strength. Lower ratio = stronger + more durable concrete. Structural design uses 0.4-0.5; general work 0.5-0.6. Never exceed 0.65 (mix becomes weak + porous).',
 'Every extra litre of water beyond hydration need (roughly 25% of cement weight) reduces strength. A w/c ratio of 0.5 gives ~40 MPa; increase to 0.7 and strength drops to ~15 MPa — a 60% loss for a tiny convenience gain. Common mistake: adding water to make a stiff mix easier to place. Correct fix: add a plasticiser instead (superplasticiser at 0.5-1.5% cement weight can drop w/c by 15-25% without losing workability). Ready-mix orders should specify max w/c ratio — most UK suppliers hold to 0.55 for standard mixes. If concrete arrives stiff, use plasticiser; never add water on site to a ready-mix load, as it voids the strength guarantee.',
 array['concrete-mix'],
 array['building-merchant','concrete-supplier'],
 array['concrete-contractor','structural-engineer'],
 'https://www.concretecentre.com/', 'trade-body', 'Concrete Centre', 0.96),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='materials'),
 'material', 'Plasticisers + admixtures',
 'Admixtures modify fresh or hardened concrete: plasticisers reduce water; superplasticisers reduce water significantly (up to 25%); retarders slow set (hot weather); accelerators speed set (cold); air-entrainers add microscopic bubbles for freeze-thaw resistance; waterproofers reduce permeability.',
 'For DIY domestic pours, admixtures are rarely worth the complexity — order the right mix from ready-mix. For larger pours: plasticiser (Sika ViscoCrete etc) at 0.5-1.5% cement weight lets you drop water content without losing workability — cheap way to add ~5 MPa strength. Air-entrainer (Sika AER-N) is MANDATORY for external slabs exposed to freeze-thaw (per BS 8500) — target 4-6% air content. Retarder (Sika Retarder) buys 1-2 hours extra placing time in hot weather. Accelerator (calcium chloride historically, now propylene glycol-based) speeds early set — useful for cold-weather pours but voids some reinforced concrete warranties. Waterproofing admixtures (Sika WT-200) suit basement + pool applications. Always check dosage — under 0.5% is usually ineffective; over 3% can weaken concrete.',
 array['concrete-mix'],
 array['building-merchant','builders-supplies','concrete-supplier'],
 array['concrete-contractor','groundworker'],
 'https://www.sika.co.uk/', 'manufacturer', 'Sika', 0.90),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='mix-design'),
 'best-practice', 'Choosing a mix ratio for common jobs',
 'Quick reference: 1:3:6 lean concrete for blinding + post fixing (~C10). 1:2:4 general foundations + garden slabs (~C20). 1:1.5:3 structural + reinforced slabs (~C25-30). Above C30 order ready-mix by strength class not ratio.',
 'Ratio-by-eye becomes unreliable above C25 — for anything structural or exposed, order ready-mix by BS EN 206 strength class (see the strength-class entry). BLINDING under foundations: 1:3:6 (~C10). Fence posts + small garden slabs: 1:2:4 (~C20). Domestic footings: 1:2:4 to 1:2:3 depending on soil (~C20-25). Reinforced ground floor slabs: 1:1.5:3 (~C25). Anything exposed to weather + freeze-thaw: air-entrained ready-mix (never site-batched). Reinforced structural elements (lintels, ground beams): C32/40 minimum per Approved Doc A. When you cross above 0.5 m³ pour size, ordering ready-mix is usually cheaper AND stronger than site-batching by ratio.',
 array['concrete-mix','slab-domestic','slab-driveway','foundation-strip'],
 array['building-merchant','concrete-supplier'],
 array['bricklayer','groundworker','concrete-contractor'],
 'https://www.concretecentre.com/', 'trade-body', 'Concrete Centre', 0.95),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='curing'),
 'best-practice', 'Hot + cold weather concreting',
 'HOT (>20°C or windy): cover with damp hessian/polythene for first 3 days; add retarder; pour early morning or evening. COLD (<5°C): use heated shelter or insulating blankets; avoid pouring if <3°C for 24h post-pour; never on frozen ground.',
 'Concrete cures via a chemical reaction that slows dramatically below 5°C and stops below 0°C. In WINTER (November-March UK): check 24-hour forecast before pouring; insulate exposed edges with 25mm poly board + hessian + polythene tent; consider CEM I rapid-hardening cement (52.5R) for faster early strength; delay 24 hours if forecast temp drops below 3°C. In SUMMER (>20°C): sub-cool aggregates with water spray before mixing; wet formwork before pour; keep the mix covered from delivery to placement; wet cure for 3-5 days with hessian OR spray a curing membrane. Failed hot/cold pours are the #1 avoidable cause of surface cracking — a £30 hessian blanket + free weather-check prevents thousands in remedial work.',
 array['concrete-cure','concrete-pour'],
 array['building-merchant','concrete-supplier'],
 array['concrete-contractor','groundworker'],
 'https://www.concretecentre.com/', 'trade-body', 'Concrete Centre', 0.93),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='mix-design'),
 'faq', 'What''s the concrete for a shed base?',
 'Standard shed base: 100mm C20 concrete slab on 100mm compacted MOT Type 1 sub-base, extending 100mm beyond the shed footprint. No mesh needed for sheds under 3m × 3m.',
 'For a 3m × 3m shed (9m² footprint): excavate 200mm below finished level; lay + compact 100mm MOT Type 1; lay 100mm slab of C20 (1:2:4 mix by ratio, or ready-mix C20 S2 20mm). Total concrete needed: ~1 m³ (a small ready-mix load or ~40 × 25kg bags). For larger sheds (>6m² footprint) or workshops with any tool storage add A142 mesh on 50mm spacers. Slope the slab away from the shed door by 1:80 (~12mm across 1m) for drainage. Cure 7 days before installing the shed. No planning or Building Regs required for detached outbuildings under 30m² floor area + <2.5m height.',
 array['slab-domestic','concrete-mix'],
 array['building-merchant','concrete-supplier'],
 array['bricklayer','groundworker'],
 'https://www.planningportal.co.uk/', 'gov', 'Planning Portal', 0.94),

('concrete',
 (select id from hammerex_knowledge_topics where trade_slug='concrete' and slug='materials'),
 'material', 'Sand grades — sharp vs building sand',
 'SHARP sand (also "washed" or "grit sand"): coarse, angular grains for concrete + screed. BUILDING sand (also "soft" or "bricklaying" sand): fine, rounded for mortar. Using the wrong one = weak concrete OR poor bricklaying.',
 'Sharp sand (0-4mm graded, sharp/angular grains, low fines <5%) is the ONLY correct sand for concrete + cement screed. Building sand (very fine, rounded grains, higher fines content) is for mortar and pointing — using it in concrete gives a weak, dusty mix. Check the bag: sharp sand feels gritty between fingers, building sand feels smooth. Colour is NOT a reliable guide (both come yellow, red, or grey depending on quarry). Sharp sand should meet BS EN 12620 for concrete aggregate. For coloured decorative concrete choose kiln-dried silica sand for consistent tone.',
 array['concrete-mix'],
 array['building-merchant','builders-supplies'],
 array['bricklayer','groundworker'],
 'https://www.mineralproducts.org/', 'trade-body', 'MPA', 0.94)

on conflict do nothing;
