// Material Intelligence Platform · seed catalog.
//
// 15 authored materials · every field Rule-c attributable to Philip O'Farrell
// (numeric values from standard construction references cited in provenance).
// Extended by domain packs · never inlined outside this catalog.
//
// Doctrine: docs/brains/nex-phase-e3-e8-roadmap-and-design-history-philip-2026-08-04.md

import type { MaterialIntelligence } from "./types";

const PHILIP = "Philip O'Farrell";
const AUTHORED = "2026-08-04";

export const MATERIAL_CATALOG: readonly MaterialIntelligence[] = [
  // ─── Timbers ────────────────────────────────────────────────────────
  {
    id: "oak_american_white_satin_lacquer",
    display_name: "American White Oak · satin lacquer",
    category: "timber",
    base_color_hex: "#F7E0B8",
    density_kg_per_m3: 720,
    roughness: 0.55,
    fire_rating: "D",
    carbon_kg_co2e_per_kg: 0.42,
    recyclability_pct: 95,
    fsc_certified: true,
    cost_per_m3_gbp: 2400,
    cost_per_linear_m_gbp: 42,
    price_stability: "moderate",
    care_frequency: "5_year",
    care_notes: "Re-oil or re-lacquer every 5 years in high-traffic areas.",
    expected_lifespan_years: 80,
    patina_behaviour: "gentle amber deepening with UV over years",
    manufacturers: [{ name: "AHEC UK Distributors", region: "UK", lead_time_weeks: 4 }],
    provenance: { named_expert: PHILIP, authored: AUTHORED, sources: ["AHEC American White Oak spec sheet"] },
    tags: ["oak", "timber", "traditional", "luxury", "staircase", "joinery"],
  },
  {
    id: "european_walnut_matt_lacquer",
    display_name: "European Walnut · matt lacquer",
    category: "timber",
    base_color_hex: "#5C4033",
    density_kg_per_m3: 640,
    roughness: 0.6,
    fire_rating: "D",
    carbon_kg_co2e_per_kg: 0.46,
    fsc_certified: true,
    cost_per_m3_gbp: 4800,
    price_stability: "volatile",
    care_frequency: "5_year",
    care_notes: "Warm undertones deepen with age. Wax annually in luxury interiors.",
    expected_lifespan_years: 100,
    patina_behaviour: "cool undertones warm to reddish-brown over decades",
    manufacturers: [{ name: "Specialist EU Walnut Merchants", region: "EU", lead_time_weeks: 6 }],
    provenance: { named_expert: PHILIP, authored: AUTHORED },
    tags: ["walnut", "timber", "luxury", "heritage"],
  },
  {
    id: "scandinavian_pine",
    display_name: "Scandinavian Pine",
    category: "timber",
    base_color_hex: "#F0DCAA",
    density_kg_per_m3: 500,
    fire_rating: "D",
    carbon_kg_co2e_per_kg: 0.37,
    fsc_certified: true,
    cost_per_m3_gbp: 620,
    price_stability: "stable",
    care_frequency: "annual",
    expected_lifespan_years: 40,
    provenance: { named_expert: PHILIP, authored: AUTHORED },
    tags: ["pine", "timber", "budget", "sales_event"],
  },
  {
    id: "mahogany_polished",
    display_name: "Mahogany · high polish",
    category: "timber",
    base_color_hex: "#722F1D",
    density_kg_per_m3: 700,
    fire_rating: "D",
    carbon_kg_co2e_per_kg: 0.55,
    fsc_certified: true,
    cost_per_m3_gbp: 5500,
    price_stability: "volatile",
    care_frequency: "5_year",
    expected_lifespan_years: 120,
    provenance: { named_expert: PHILIP, authored: AUTHORED },
    tags: ["mahogany", "timber", "heritage", "luxury"],
  },
  {
    id: "ash_white",
    display_name: "White Ash",
    category: "timber",
    base_color_hex: "#EFDDBE",
    density_kg_per_m3: 700,
    fire_rating: "D",
    carbon_kg_co2e_per_kg: 0.40,
    fsc_certified: true,
    cost_per_m3_gbp: 1800,
    price_stability: "moderate",
    provenance: { named_expert: PHILIP, authored: AUTHORED },
    tags: ["ash", "timber", "modern"],
  },
  // ─── Metals ─────────────────────────────────────────────────────────
  {
    id: "steel_black_powder_coated",
    display_name: "Steel · black powder coated",
    category: "metal",
    base_color_hex: "#111111",
    density_kg_per_m3: 7850,
    roughness: 0.35,
    reflectivity: 0.3,
    fire_rating: "A1",
    carbon_kg_co2e_per_kg: 2.0,
    recyclability_pct: 98,
    cost_per_linear_m_gbp: 22,
    price_stability: "volatile",
    care_frequency: "10_year",
    expected_lifespan_years: 60,
    provenance: { named_expert: PHILIP, authored: AUTHORED },
    tags: ["steel", "metal", "industrial", "modern", "balustrade"],
  },
  {
    id: "brass_polished",
    display_name: "Brass · polished",
    category: "metal",
    base_color_hex: "#C9A34E",
    density_kg_per_m3: 8500,
    roughness: 0.15,
    reflectivity: 0.7,
    fire_rating: "A1",
    carbon_kg_co2e_per_kg: 3.6,
    cost_per_linear_m_gbp: 60,
    price_stability: "moderate",
    care_frequency: "annual",
    care_notes: "Requires polishing to maintain shine or allow to patina naturally.",
    expected_lifespan_years: 100,
    patina_behaviour: "develops rich brown/verdigris patina",
    provenance: { named_expert: PHILIP, authored: AUTHORED },
    tags: ["brass", "metal", "luxury", "heritage"],
  },
  {
    id: "aluminium_anodised",
    display_name: "Aluminium · anodised",
    category: "metal",
    base_color_hex: "#B8B8BE",
    density_kg_per_m3: 2700,
    roughness: 0.4,
    fire_rating: "A1",
    carbon_kg_co2e_per_kg: 8.24,
    recyclability_pct: 95,
    cost_per_linear_m_gbp: 18,
    price_stability: "volatile",
    expected_lifespan_years: 40,
    provenance: { named_expert: PHILIP, authored: AUTHORED },
    tags: ["aluminium", "metal", "modern"],
  },
  // ─── Glass ──────────────────────────────────────────────────────────
  {
    id: "glass_toughened_10mm",
    display_name: "Toughened glass · 10mm",
    category: "glass",
    base_color_hex: "#E8F1F2",
    density_kg_per_m3: 2500,
    roughness: 0.05,
    reflectivity: 0.9,
    transparency: 0.85,
    fire_rating: "A1",
    carbon_kg_co2e_per_kg: 0.9,
    recyclability_pct: 100,
    cost_per_m2_gbp: 180,
    price_stability: "stable",
    care_frequency: "none",
    expected_lifespan_years: 50,
    provenance: { named_expert: PHILIP, authored: AUTHORED, sources: ["BS EN 12150 · toughened glass"] },
    tags: ["glass", "balustrade", "modern", "luxury"],
  },
  // ─── Stone + Composite ─────────────────────────────────────────────
  {
    id: "quartz_worktop",
    display_name: "Engineered Quartz Worktop",
    category: "composite",
    base_color_hex: "#EEEEEE",
    density_kg_per_m3: 2650,
    roughness: 0.15,
    fire_rating: "A1",
    carbon_kg_co2e_per_kg: 1.2,
    cost_per_m2_gbp: 380,
    price_stability: "moderate",
    care_frequency: "none",
    expected_lifespan_years: 40,
    provenance: { named_expert: PHILIP, authored: AUTHORED },
    tags: ["quartz", "worktop", "kitchen", "luxury"],
  },
  {
    id: "granite_black",
    display_name: "Black Granite",
    category: "stone",
    base_color_hex: "#222222",
    density_kg_per_m3: 2700,
    fire_rating: "A1",
    carbon_kg_co2e_per_kg: 0.7,
    cost_per_m2_gbp: 320,
    price_stability: "stable",
    expected_lifespan_years: 100,
    provenance: { named_expert: PHILIP, authored: AUTHORED },
    tags: ["granite", "stone", "worktop", "luxury"],
  },
  // ─── Concrete + Paint + Lacquer ────────────────────────────────────
  {
    id: "concrete_polished",
    display_name: "Polished Concrete Floor",
    category: "concrete",
    base_color_hex: "#8A8A88",
    density_kg_per_m3: 2400,
    slip_rating: "R10",
    fire_rating: "A1",
    carbon_kg_co2e_per_kg: 0.12,
    cost_per_m2_gbp: 90,
    price_stability: "stable",
    care_frequency: "5_year",
    expected_lifespan_years: 60,
    provenance: { named_expert: PHILIP, authored: AUTHORED },
    tags: ["concrete", "flooring", "industrial", "modern"],
  },
  {
    id: "paint_matt_emulsion_white",
    display_name: "Matt Emulsion · white",
    category: "paint",
    base_color_hex: "#FAFAF8",
    roughness: 0.9,
    fire_rating: "B",
    voc_g_per_l: 30,
    carbon_kg_co2e_per_kg: 1.1,
    cost_per_m2_gbp: 4,
    price_stability: "stable",
    care_frequency: "5_year",
    expected_lifespan_years: 8,
    provenance: { named_expert: PHILIP, authored: AUTHORED },
    tags: ["paint", "wall_finish"],
  },
  {
    id: "led_warm_2700k_strip",
    display_name: "Warm White LED Strip · 2700K",
    category: "led",
    base_color_hex: "#FFCC88",
    fire_rating: "B",
    carbon_kg_co2e_per_kg: 4.5,
    recyclability_pct: 30,
    cost_per_linear_m_gbp: 12,
    price_stability: "stable",
    care_frequency: "none",
    expected_lifespan_years: 15,
    provenance: { named_expert: PHILIP, authored: AUTHORED },
    tags: ["led", "lighting", "staircase", "warm"],
  },
  // ─── Insulation ────────────────────────────────────────────────────
  {
    id: "wood_fibre_insulation",
    display_name: "Wood-Fibre Insulation Board",
    category: "insulation",
    base_color_hex: "#B08C68",
    density_kg_per_m3: 160,
    fire_rating: "E",
    carbon_kg_co2e_per_kg: -1.6,          // negative embodied carbon (biogenic)
    recyclability_pct: 100,
    fsc_certified: true,
    cost_per_m2_gbp: 22,
    expected_lifespan_years: 60,
    provenance: { named_expert: PHILIP, authored: AUTHORED, sources: ["Steico product data"] },
    tags: ["insulation", "sustainability", "biogenic"],
  },
];

const CATALOG_INDEX = new Map<string, MaterialIntelligence>(MATERIAL_CATALOG.map((m) => [m.id, m]));

export function getMaterial(id: string): MaterialIntelligence | undefined { return CATALOG_INDEX.get(id); }
export function listMaterials(): readonly MaterialIntelligence[] { return MATERIAL_CATALOG; }
export function countMaterials(): number { return MATERIAL_CATALOG.length; }
