// NEX Centre — mock feed fallback.
//
// Purpose: keep /nex-app/centre populated during the cold-start phase
// before real merchants publish products. Same shape as the live feed
// (CentreFeedItem) so the UI renders them without any special-case
// logic. The feed endpoint returns these when the real DB read comes
// back empty.
//
// Pattern borrowed from the platform's existing PRODUCT_FIXTURES
// fallback used by /tc/trade-center (see comment there):
//   "…the tab never looks abandoned."
//
// Replace / retire this file once real merchants have published enough
// products that the feed is naturally full.

import type { CentreFeedItem } from "./types";

const nowIso = "2026-07-27T00:00:00Z";

/** Build a CentreFeedItem with sensible defaults for the mock feed. */
function mk(overrides: Partial<CentreFeedItem>): CentreFeedItem {
  return {
    kind: "product",
    offer_id: `mock-offer-${Math.random().toString(36).slice(2, 10)}`,
    canonical_id: `mock-canon-${Math.random().toString(36).slice(2, 10)}`,
    name: "Sample product",
    brand_name: "Sample Brand",
    slug: "sample/sample-product",
    description: null,
    price_pence: 0,
    vat_rate: 0.2,
    stock_status: "in_stock",
    hero_image_url: null,
    category_path: [],
    merchant_id: "mock-merchant",
    merchant_slug: null,
    merchant_display_name: "Sample Merchant",
    merchant_city: "UK",
    merchant_postcode_prefix: null,
    merchant_lat: null,
    merchant_lng: null,
    merchant_avatar_url: null,
    merchant_whatsapp: null,
    merchant_email: null,
    merchant_phone: null,
    merchant_website: null,
    merchant_verification_level: "listed",
    // Philip 2026-08-02 · Trade Center v2 · mock defaults.
    merchant_tier: null,
    merchant_google_rating: null,
    merchant_google_review_count: null,
    merchant_services: [],
    merchant_years_in_trade: null,
    merchant_photos: [],
    merchant_instagram: null,
    merchant_facebook: null,
    distance_km: null,
    region_match_score: null,
    is_promoted: false,
    active_banner_headline: null,
    active_banner_visual_style: null,
    published_at: nowIso,
    ...overrides,
  };
}

/** 16 realistic UK-trade mock cards covering the categories customers
 *  are most likely to search on day one. */
export const MOCK_CENTRE_FEED: CentreFeedItem[] = [
  mk({
    offer_id: "mock-offer-oak-tread-001",
    canonical_id: "mock-canon-oak-tread-001",
    name: "Premium White Oak Stair Tread — 900 × 275 × 40mm",
    brand_name: "OakCo",
    slug: "oakco/premium-white-oak-stair-tread",
    description:
      "Hand-finished solid American White Oak, kiln-dried to 8-10% moisture. Cut to your riser count. Matte hardwax oil finish available on request.",
    price_pence: 8900,
    hero_image_url:
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80",
    category_path: ["staircase", "treads", "oak"],
    merchant_id: "mock-merchant-oakco",
    merchant_slug: "oakco-uk",
    merchant_display_name: "OakCo Timber Ltd",
    merchant_city: "Leeds",
    merchant_postcode_prefix: "LS",
    merchant_avatar_url:
      "https://images.unsplash.com/photo-1560785496-3c9d27877182?w=80&q=80&fit=crop",
    merchant_whatsapp: "+447700900001",
    merchant_email: "hello@oakco.example",
    merchant_website: "oakco.example",
    merchant_verification_level: "verified",
    is_promoted: true,
    active_banner_headline: "Solid oak craftsmanship",
    active_banner_visual_style: "premium",
  }),
  mk({
    offer_id: "mock-offer-glass-balustrade-001",
    canonical_id: "mock-canon-glass-balustrade-001",
    name: "12mm Toughened Glass Balustrade Panel",
    brand_name: "ClearLine",
    slug: "clearline/toughened-balustrade-panel",
    description:
      "12mm toughened safety glass, polished edges, drilled to your stair spec. Complies with BS 6180.",
    price_pence: 24500,
    hero_image_url:
      "https://images.unsplash.com/photo-1541123437800-1bb1317badc2?w=800&q=80",
    category_path: ["staircase", "balustrade", "glass"],
    merchant_id: "mock-merchant-clearline",
    merchant_slug: "clearline-glass",
    merchant_display_name: "ClearLine Glass Ltd",
    merchant_city: "Manchester",
    merchant_postcode_prefix: "M",
    merchant_whatsapp: "+447700900002",
    merchant_email: "sales@clearline.example",
    merchant_verification_level: "verified",
  }),
  mk({
    offer_id: "mock-offer-walnut-handrail",
    canonical_id: "mock-canon-walnut-handrail",
    name: "American Black Walnut Handrail — 2.4m",
    brand_name: "Timberwright",
    slug: "timberwright/walnut-handrail",
    description:
      "Rich, dark American Black Walnut handrail. Profile: square-edge modern. Sanded to 320 grit, ready for oil or lacquer.",
    price_pence: 21500,
    hero_image_url:
      "https://images.unsplash.com/photo-1503174971373-b1f69850bded?w=800&q=80",
    category_path: ["staircase", "handrail", "walnut"],
    merchant_id: "mock-merchant-timberwright",
    merchant_slug: "timberwright",
    merchant_display_name: "Timberwright Joinery",
    merchant_city: "Bristol",
    merchant_postcode_prefix: "BS",
    merchant_whatsapp: "+447700900003",
    merchant_website: "timberwright.example",
    merchant_verification_level: "partner",
    is_promoted: true,
  }),
  mk({
    offer_id: "mock-offer-reclaimed-brick",
    canonical_id: "mock-canon-reclaimed-brick",
    name: "Reclaimed London Stock Brick — Pallet of 500",
    brand_name: "Salvage Yard",
    slug: "salvage-yard/reclaimed-london-stock-brick",
    description:
      "Genuine reclaimed London Stock bricks, hand-cleaned. Perfect for character extensions and heritage matching.",
    price_pence: 34000,
    hero_image_url:
      "https://images.unsplash.com/photo-1590247813693-5541d1c609fd?w=800&q=80",
    category_path: ["building", "brick", "reclaimed"],
    merchant_id: "mock-merchant-salvage",
    merchant_slug: "salvage-yard-uk",
    merchant_display_name: "The Salvage Yard",
    merchant_city: "London",
    merchant_postcode_prefix: "N",
    merchant_email: "yard@salvage.example",
    merchant_verification_level: "claimed",
  }),
  mk({
    offer_id: "mock-offer-slate-roof-tile",
    canonical_id: "mock-canon-slate-roof-tile",
    name: "Welsh Slate Roof Tile — 500 × 250mm",
    brand_name: "Snowdonia Slate",
    slug: "snowdonia-slate/welsh-roof-tile",
    description:
      "Natural Welsh slate roof tiles, hand-riven. 100-year expected life. Priced per tile.",
    price_pence: 420,
    hero_image_url:
      "https://images.unsplash.com/photo-1508433957232-3107f5fd5995?w=800&q=80",
    category_path: ["roofing", "slate"],
    merchant_id: "mock-merchant-snowdonia",
    merchant_slug: "snowdonia-slate",
    merchant_display_name: "Snowdonia Slate Co",
    merchant_city: "North Wales",
    merchant_postcode_prefix: "LL",
    merchant_whatsapp: "+447700900005",
    merchant_website: "snowdoniaslate.example",
    merchant_verification_level: "verified",
  }),
  mk({
    offer_id: "mock-offer-quartz-worktop",
    canonical_id: "mock-canon-quartz-worktop",
    name: "Carrara Quartz Worktop — 3m × 620mm",
    brand_name: "StoneCraft",
    slug: "stonecraft/carrara-quartz-worktop",
    description:
      "20mm Carrara-look quartz, template-fitted and templated for your kitchen. Includes edge polish and sink cut-out.",
    price_pence: 89000,
    hero_image_url:
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    category_path: ["kitchen", "worktop", "quartz"],
    merchant_id: "mock-merchant-stonecraft",
    merchant_slug: "stonecraft-uk",
    merchant_display_name: "StoneCraft Fabrication",
    merchant_city: "Birmingham",
    merchant_postcode_prefix: "B",
    merchant_email: "hello@stonecraft.example",
    merchant_whatsapp: "+447700900006",
    merchant_verification_level: "verified",
  }),
  mk({
    offer_id: "mock-offer-oak-door-reclaimed",
    canonical_id: "mock-canon-oak-door-reclaimed",
    name: "Reclaimed Oak Cottage Door — 1980 × 762mm",
    brand_name: "Barn Doors Direct",
    slug: "barn-doors-direct/reclaimed-oak-cottage",
    description:
      "Genuine reclaimed oak cottage door with iron latch. Ledged and braced. Each door unique.",
    price_pence: 62000,
    hero_image_url:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    category_path: ["doors", "oak", "reclaimed"],
    merchant_id: "mock-merchant-barn-doors",
    merchant_slug: "barn-doors-direct",
    merchant_display_name: "Barn Doors Direct",
    merchant_city: "York",
    merchant_postcode_prefix: "YO",
    merchant_verification_level: "claimed",
  }),
  mk({
    offer_id: "mock-offer-oak-flooring",
    canonical_id: "mock-canon-oak-flooring",
    name: "Engineered Oak Flooring — 190mm plank",
    brand_name: "FloorWorks",
    slug: "floorworks/engineered-oak-190",
    description:
      "190mm × 14mm European oak on birch ply base. Matt lacquered. UFH-compatible. Sold per m².",
    price_pence: 4850,
    hero_image_url:
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
    category_path: ["flooring", "oak", "engineered"],
    merchant_id: "mock-merchant-floorworks",
    merchant_slug: "floorworks",
    merchant_display_name: "FloorWorks UK",
    merchant_city: "Manchester",
    merchant_postcode_prefix: "M",
    merchant_whatsapp: "+447700900008",
    merchant_email: "orders@floorworks.example",
    merchant_website: "floorworks.example",
    merchant_verification_level: "verified",
    is_promoted: true,
  }),
  mk({
    offer_id: "mock-offer-victorian-tile",
    canonical_id: "mock-canon-victorian-tile",
    name: "Victorian Encaustic Floor Tile — Bloomsbury Pattern",
    brand_name: "Heritage Tiles",
    slug: "heritage-tiles/bloomsbury-victorian",
    description:
      "Traditional encaustic Victorian floor tile in the Bloomsbury pattern. 200 × 200mm. Perfect for period entrance halls.",
    price_pence: 8500,
    hero_image_url:
      "https://images.unsplash.com/photo-1615873968403-89e068629265?w=800&q=80",
    category_path: ["tiles", "victorian", "floor"],
    merchant_id: "mock-merchant-heritage",
    merchant_slug: "heritage-tiles",
    merchant_display_name: "Heritage Tiles Ltd",
    merchant_city: "London",
    merchant_postcode_prefix: "SW",
    merchant_email: "sales@heritagetiles.example",
    merchant_verification_level: "verified",
  }),
  mk({
    offer_id: "mock-offer-cast-iron-radiator",
    canonical_id: "mock-canon-cast-iron-radiator",
    name: "Cast Iron Column Radiator — 4-column, 600mm",
    brand_name: "Foundry Heating",
    slug: "foundry-heating/4-column-cast-iron-600",
    description:
      "Traditional 4-column cast iron radiator, polished antique brass finish. Full 10-year guarantee. BSP 1/2\" connections.",
    price_pence: 34500,
    hero_image_url:
      "https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=800&q=80",
    category_path: ["plumbing", "heating", "radiator"],
    merchant_id: "mock-merchant-foundry",
    merchant_slug: "foundry-heating",
    merchant_display_name: "Foundry Heating",
    merchant_city: "Sheffield",
    merchant_postcode_prefix: "S",
    merchant_whatsapp: "+447700900010",
    merchant_website: "foundry-heating.example",
    merchant_verification_level: "verified",
  }),
  mk({
    offer_id: "mock-offer-composite-decking",
    canonical_id: "mock-canon-composite-decking",
    name: "Composite Decking Board — Ash Grey, 3.6m",
    brand_name: "Deckwise",
    slug: "deckwise/composite-ash-grey-3600",
    description:
      "Grooved composite decking, ash grey. 25-year warranty. Slip-resistant surface tested to BS 7976.",
    price_pence: 4200,
    hero_image_url:
      "https://images.unsplash.com/photo-1591474200742-8e512e6f98f8?w=800&q=80",
    category_path: ["landscaping", "decking", "composite"],
    merchant_id: "mock-merchant-deckwise",
    merchant_slug: "deckwise",
    merchant_display_name: "Deckwise UK",
    merchant_city: "Bristol",
    merchant_postcode_prefix: "BS",
    merchant_email: "orders@deckwise.example",
    merchant_verification_level: "verified",
  }),
  mk({
    offer_id: "mock-offer-cotswold-stone",
    canonical_id: "mock-canon-cotswold-stone",
    name: "Cotswold Dry-Stone Walling Stone — Bulk Bag",
    brand_name: "Cotswold Stone",
    slug: "cotswold-stone/dry-stone-walling",
    description:
      "Traditional Cotswold limestone, sorted for dry-stone walling. Approx 500kg bulk bag. Local delivery available.",
    price_pence: 12000,
    hero_image_url:
      "https://images.unsplash.com/photo-1601979031925-424e53b6caaa?w=800&q=80",
    category_path: ["landscaping", "walling", "stone"],
    merchant_id: "mock-merchant-cotswold",
    merchant_slug: "cotswold-stone",
    merchant_display_name: "Cotswold Stone Co",
    merchant_city: "Cirencester",
    merchant_postcode_prefix: "GL",
    merchant_whatsapp: "+447700900012",
    merchant_verification_level: "claimed",
  }),
  mk({
    offer_id: "mock-offer-brass-tap",
    canonical_id: "mock-canon-brass-tap",
    name: "Solid Brass Kitchen Mixer Tap — Aged Finish",
    brand_name: "Brasscraft",
    slug: "brasscraft/aged-brass-kitchen-mixer",
    description:
      "Solid brass single-lever kitchen mixer with pull-out spray. Aged brass finish. WRAS approved.",
    price_pence: 28500,
    hero_image_url:
      "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80",
    category_path: ["kitchen", "taps", "brass"],
    merchant_id: "mock-merchant-brasscraft",
    merchant_slug: "brasscraft",
    merchant_display_name: "Brasscraft UK",
    merchant_city: "Birmingham",
    merchant_postcode_prefix: "B",
    merchant_email: "hello@brasscraft.example",
    merchant_website: "brasscraft.example",
    merchant_verification_level: "verified",
  }),
  mk({
    offer_id: "mock-offer-shaker-kitchen",
    canonical_id: "mock-canon-shaker-kitchen",
    name: "Shaker Kitchen Door — In-Frame, Painted",
    brand_name: "Cabinetry Co",
    slug: "cabinetry-co/shaker-in-frame-painted",
    description:
      "Bespoke in-frame shaker door in any Farrow & Ball colour. Solid tulip wood, hand-finished. Priced per door.",
    price_pence: 16500,
    hero_image_url:
      "https://images.unsplash.com/photo-1556909114-11c3ad4d7bb5?w=800&q=80",
    category_path: ["kitchen", "cabinetry", "shaker"],
    merchant_id: "mock-merchant-cabinetry",
    merchant_slug: "cabinetry-co",
    merchant_display_name: "Cabinetry Co",
    merchant_city: "Oxford",
    merchant_postcode_prefix: "OX",
    merchant_whatsapp: "+447700900014",
    merchant_email: "studio@cabinetry.example",
    merchant_verification_level: "partner",
    is_promoted: true,
  }),
  mk({
    offer_id: "mock-offer-oak-beam",
    canonical_id: "mock-canon-oak-beam",
    name: "Green Oak Beam — 200 × 200 × 3000mm",
    brand_name: "Beamworks",
    slug: "beamworks/green-oak-beam-200-200",
    description:
      "Fresh sawn green oak beam. Ideal for structural work, feature ceilings, oak-framed extensions.",
    price_pence: 45000,
    hero_image_url:
      "https://images.unsplash.com/photo-1615873968403-89e068629265?w=800&q=80",
    category_path: ["timber", "oak", "structural"],
    merchant_id: "mock-merchant-beamworks",
    merchant_slug: "beamworks",
    merchant_display_name: "Beamworks Timber",
    merchant_city: "Devon",
    merchant_postcode_prefix: "EX",
    merchant_website: "beamworks.example",
    merchant_verification_level: "verified",
  }),
  mk({
    offer_id: "mock-offer-black-metal-baluster",
    canonical_id: "mock-canon-black-metal-baluster",
    name: "Square Black Steel Baluster — 12mm × 900mm",
    brand_name: "IronForge",
    slug: "ironforge/black-steel-baluster-12mm",
    description:
      "Powder-coated matte black square steel baluster. Ideal for modern industrial staircases. Priced each.",
    price_pence: 1850,
    hero_image_url:
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&q=80",
    category_path: ["staircase", "balustrade", "metal"],
    merchant_id: "mock-merchant-ironforge",
    merchant_slug: "ironforge",
    merchant_display_name: "IronForge Metalwork",
    merchant_city: "Sheffield",
    merchant_postcode_prefix: "S",
    merchant_whatsapp: "+447700900016",
    merchant_email: "sales@ironforge.example",
    merchant_verification_level: "verified",
    is_promoted: true,
  }),
];
