import { NextResponse } from "next/server";
import { performRefactorAnalysis, refactorVocabGuard } from "@/lib/nex-refactor-engineer/engine";
import { validateEvidence } from "@/lib/nex-evidence-validation/validator";
export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET() {
  const cases: { id: string; ok: boolean; detail: string }[] = [];
  const run = (id: string, fn: () => { ok: boolean; detail: string }) => { try { cases.push({ id, ...fn() }); } catch (e) { cases.push({ id, ok: false, detail: "harness: " + (e as Error).message }); } };
  run("REF.candidate-produced", () => { const r = performRefactorAnalysis({ seed: "s", target_scope: "src/x", baseline_metrics: { duplication: 10 }, projected_metrics: { duplication: 3 }, test_coverage_present: true, test_coverage_ratio: 0.9, minimum_coverage_ratio: 0.7 }); return { ok: r.outcome === "REFACTOR_CANDIDATE", detail: r.outcome }; });
  run("REF.dont-refactor-target-acceptable", () => { const r = performRefactorAnalysis({ seed: "s", target_scope: "src/x", baseline_metrics: { duplication: 3 }, projected_metrics: { duplication: 3 }, test_coverage_present: true, test_coverage_ratio: 0.9, minimum_coverage_ratio: 0.7 }); return { ok: r.outcome === "TARGET_ALREADY_ACCEPTABLE", detail: r.outcome }; });
  run("REF.no-measurable-benefit", () => { const r = performRefactorAnalysis({ seed: "s", target_scope: "src/x", baseline_metrics: { duplication: 3 }, projected_metrics: { duplication: 10 }, test_coverage_present: true, test_coverage_ratio: 0.9, minimum_coverage_ratio: 0.7 }); return { ok: r.outcome === "NO_MEASURABLE_BENEFIT", detail: r.outcome }; });
  run("REF.risk-exceeds-benefit-low-coverage", () => { const r = performRefactorAnalysis({ seed: "s", target_scope: "src/x", baseline_metrics: { duplication: 10 }, projected_metrics: { duplication: 3 }, test_coverage_present: true, test_coverage_ratio: 0.3, minimum_coverage_ratio: 0.7 }); return { ok: r.outcome === "RISK_EXCEEDS_BENEFIT", detail: r.outcome }; });
  run("REF.insufficient-no-projected", () => { const r = performRefactorAnalysis({ seed: "s", target_scope: "src/x", baseline_metrics: { duplication: 10 }, test_coverage_present: true, test_coverage_ratio: 0.9, minimum_coverage_ratio: 0.7 }); return { ok: r.outcome === "INSUFFICIENT_EVIDENCE", detail: r.outcome }; });
  run("REF.llm-rejected", () => { const r = performRefactorAnalysis({ seed: "s", target_scope: "src/x", baseline_metrics: { duplication: 10 }, projected_metrics: { duplication: 3 }, test_coverage_present: true, test_coverage_ratio: 0.9, minimum_coverage_ratio: 0.7, reject_llm_attempt: true }); return { ok: r.outcome === "INSUFFICIENT_EVIDENCE", detail: r.outcome }; });
  run("REF.attribution", () => { const r = performRefactorAnalysis({ seed: "s", target_scope: "src/x", baseline_metrics: {}, test_coverage_present: true, test_coverage_ratio: 0.9, minimum_coverage_ratio: 0.7 }); return { ok: r.attribution.produced_by === "nex_refactor_engineer_evidence_specialist", detail: r.attribution.authority }; });
  run("REF.no-forbidden-vocab", () => { const r = performRefactorAnalysis({ seed: "s", target_scope: "src/x", baseline_metrics: { duplication: 10 }, projected_metrics: { duplication: 3 }, test_coverage_present: true, test_coverage_ratio: 0.9, minimum_coverage_ratio: 0.7 }); const chk = refactorVocabGuard.walkForForbiddenVocab(r); return { ok: !chk.hit, detail: chk.hit ? "HIT " + chk.word : "clean" }; });
  run("REF.evidence-validation-passes", () => { const r = performRefactorAnalysis({ seed: "s", target_scope: "src/x", baseline_metrics: { duplication: 10 }, projected_metrics: { duplication: 3 }, test_coverage_present: true, test_coverage_ratio: 0.9, minimum_coverage_ratio: 0.7 }); const aer = validateEvidence(r as any); return { ok: aer.validation_verdict === "VALIDATED", detail: aer.validation_verdict }; });
  run("REF.deterministic", () => { const p: any = { seed: "s", target_scope: "src/x", baseline_metrics: { duplication: 10 }, projected_metrics: { duplication: 3 }, test_coverage_present: true, test_coverage_ratio: 0.9, minimum_coverage_ratio: 0.7 }; const a = performRefactorAnalysis(p); const b = performRefactorAnalysis(p); return { ok: a.determinism_witness.first_run_hash === b.determinism_witness.first_run_hash, detail: a.determinism_witness.first_run_hash }; });
  const pass = cases.filter(c => c.ok).length;
  return NextResponse.json({ at: new Date().toISOString(), total: cases.length, pass, fail: cases.length - pass, cases }, { headers: { "Cache-Control": "no-store" } });
}
